// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/BeatReduce.v
// Created: 2026-03-18 09:48:18
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BeatReduce
// Source Path: rmsNormalization/DUT/BeatReduce
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BeatReduce
          (clk,
           reset,
           enb,
           squaredBeat_0,
           squaredBeat_1,
           squaredBeat_2,
           squaredBeat_3,
           squaredBeat_4,
           squaredBeat_5,
           squaredBeat_6,
           squaredBeat_7,
           beatSum);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] squaredBeat_0;  // single
  input   [31:0] squaredBeat_1;  // single
  input   [31:0] squaredBeat_2;  // single
  input   [31:0] squaredBeat_3;  // single
  input   [31:0] squaredBeat_4;  // single
  input   [31:0] squaredBeat_5;  // single
  input   [31:0] squaredBeat_6;  // single
  input   [31:0] squaredBeat_7;  // single
  output  [31:0] beatSum;  // single


  wire [31:0] Add01_out1;  // ufix32
  wire [31:0] Add23_out1;  // ufix32
  wire [31:0] Add0123_out1;  // ufix32
  wire [31:0] Add45_out1;  // ufix32
  wire [31:0] Add67_out1;  // ufix32
  wire [31:0] Add4567_out1;  // ufix32
  wire [31:0] AddAll_out1;  // ufix32


  nfp_add_single u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(squaredBeat_0),  // single
                                 .nfp_in2(squaredBeat_1),  // single
                                 .nfp_out(Add01_out1)  // single
                                 );
  nfp_add_single u_nfp_add_comp_1 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(squaredBeat_2),  // single
                                   .nfp_in2(squaredBeat_3),  // single
                                   .nfp_out(Add23_out1)  // single
                                   );
  nfp_add_single u_nfp_add_comp_2 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Add01_out1),  // single
                                   .nfp_in2(Add23_out1),  // single
                                   .nfp_out(Add0123_out1)  // single
                                   );
  nfp_add_single u_nfp_add_comp_3 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(squaredBeat_4),  // single
                                   .nfp_in2(squaredBeat_5),  // single
                                   .nfp_out(Add45_out1)  // single
                                   );
  nfp_add_single u_nfp_add_comp_4 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(squaredBeat_6),  // single
                                   .nfp_in2(squaredBeat_7),  // single
                                   .nfp_out(Add67_out1)  // single
                                   );
  nfp_add_single u_nfp_add_comp_5 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Add45_out1),  // single
                                   .nfp_in2(Add67_out1),  // single
                                   .nfp_out(Add4567_out1)  // single
                                   );
  nfp_add_single u_nfp_add_comp_6 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Add0123_out1),  // single
                                   .nfp_in2(Add4567_out1),  // single
                                   .nfp_out(AddAll_out1)  // single
                                   );
  assign beatSum = AddAll_out1;

endmodule  // BeatReduce

