// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/BeatAccumulator.v
// Created: 2026-03-18 09:48:18
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BeatAccumulator
// Source Path: rmsNormalization/DUT/BeatAccumulator
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BeatAccumulator
          (clk,
           reset,
           enb,
           beatSum,
           accumulate,
           clear,
           currentSum);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] beatSum;  // single
  input   accumulate;
  input   clear;
  output  [31:0] currentSum;  // single


  wire stateControl;
  reg  [67:0] delayMatch135_reg;  // ufix1 [68]
  wire stateControl_1;
  reg  [26:0] reduced_reg;  // ufix1 [27]
  wire ClearBool_out1;
  wire stateControl_3;
  reg  [40:0] delayMatch134_reg;  // ufix1 [41]
  wire stateControl_4;
  wire [7:0] BankIndexOne_out1;  // uint8
  wire [7:0] BankIndexZero_out1;  // uint8
  reg [7:0] BankIndexState_out1;  // uint8
  wire [7:0] BankIndexAdd_out1;  // uint8
  wire BankIndexIsLast_out1;
  wire [7:0] BankIndexWrap_out1;  // uint8
  wire [7:0] BankIndexAdvance_out1;  // uint8
  wire [7:0] BankIndexClear_out1;  // uint8
  wire [7:0] BankIndexClear_out1_1;  // uint8
  wire Sel00_out1;
  wire UpdateEn00_out1;
  reg  [26:0] delayMatch_reg;  // ufix1 [27]
  wire UpdateEn00_out1_1;
  wire stateControl_5;
  reg  [66:0] delayMatch146_reg;  // ufix1 [67]
  wire stateControl_6;
  wire [31:0] AccumulateSingle_out1;  // ufix32
  wire [31:0] AccumulateSingle_out1_1;  // ufix32
  wire [31:0] AccumulateSingle_out1_2;  // ufix32
  wire [31:0] Gate00_out_1;  // ufix32
  wire [31:0] SelSingle00_out1;  // ufix32
  wire [31:0] SelSingle00_out1_1;  // ufix32
  wire [31:0] SelSingle00_out1_2;  // ufix32
  reg [31:0] delayMatch66_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch66_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle00_out1_3;  // ufix32
  wire [31:0] Gate00_out1;  // ufix32
  wire [31:0] ZeroSingle_out1;  // ufix32
  reg [31:0] reduced_reg_1 [0:26];  // ufix32 [27]
  reg [31:0] reduced_reg_next [0:26];  // ufix32 [27]
  reg [31:0] ZeroSingle_out1_1;  // ufix32
  wire [31:0] FeedbackDelay00_out1;  // ufix32
  reg [31:0] FeedbackDelay00_out1_last_value;  // ufix32
  wire [31:0] BankState00_out1;  // ufix32
  wire [31:0] AccumulateAdd00_out1;  // ufix32
  reg [31:0] BankState00_out1_1;  // ufix32
  wire [31:0] HoldOrAcc00_out1;  // ufix32
  wire [31:0] BankState00_out1_2;  // ufix32
  wire stateControl_7;
  reg  [67:0] delayMatch136_reg;  // ufix1 [68]
  wire stateControl_8;
  wire Sel01_out1;
  wire UpdateEn01_out1;
  reg  [26:0] delayMatch6_reg;  // ufix1 [27]
  wire UpdateEn01_out1_1;
  wire stateControl_9;
  reg  [66:0] delayMatch147_reg;  // ufix1 [67]
  wire stateControl_10;
  wire [31:0] Gate01_out_1;  // ufix32
  wire [31:0] SelSingle01_out1;  // ufix32
  wire [31:0] SelSingle01_out1_1;  // ufix32
  wire [31:0] SelSingle01_out1_2;  // ufix32
  reg [31:0] delayMatch72_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch72_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle01_out1_3;  // ufix32
  wire [31:0] Gate01_out1;  // ufix32
  wire [31:0] FeedbackDelay01_out1;  // ufix32
  reg [31:0] FeedbackDelay01_out1_last_value;  // ufix32
  wire [31:0] BankState01_out1;  // ufix32
  wire [31:0] AccumulateAdd01_out1;  // ufix32
  reg [31:0] BankState01_out1_1;  // ufix32
  wire [31:0] HoldOrAcc01_out1;  // ufix32
  wire [31:0] BankState01_out1_2;  // ufix32
  wire [31:0] Sum01_out1;  // ufix32
  wire stateControl_11;
  reg  [67:0] delayMatch137_reg;  // ufix1 [68]
  wire stateControl_12;
  wire Sel02_out1;
  wire UpdateEn02_out1;
  reg  [26:0] delayMatch12_reg;  // ufix1 [27]
  wire UpdateEn02_out1_1;
  wire stateControl_13;
  reg  [66:0] delayMatch148_reg;  // ufix1 [67]
  wire stateControl_14;
  wire [31:0] Gate02_out_1;  // ufix32
  wire [31:0] SelSingle02_out1;  // ufix32
  wire [31:0] SelSingle02_out1_1;  // ufix32
  wire [31:0] SelSingle02_out1_2;  // ufix32
  reg [31:0] delayMatch73_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch73_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle02_out1_3;  // ufix32
  wire [31:0] Gate02_out1;  // ufix32
  wire [31:0] FeedbackDelay02_out1;  // ufix32
  reg [31:0] FeedbackDelay02_out1_last_value;  // ufix32
  wire [31:0] BankState02_out1;  // ufix32
  wire [31:0] AccumulateAdd02_out1;  // ufix32
  reg [31:0] BankState02_out1_1;  // ufix32
  wire [31:0] HoldOrAcc02_out1;  // ufix32
  wire [31:0] BankState02_out1_2;  // ufix32
  wire stateControl_15;
  reg  [67:0] delayMatch138_reg;  // ufix1 [68]
  wire stateControl_16;
  wire Sel03_out1;
  wire UpdateEn03_out1;
  reg  [26:0] delayMatch18_reg;  // ufix1 [27]
  wire UpdateEn03_out1_1;
  wire stateControl_17;
  reg  [66:0] delayMatch149_reg;  // ufix1 [67]
  wire stateControl_18;
  wire [31:0] Gate03_out_1;  // ufix32
  wire [31:0] SelSingle03_out1;  // ufix32
  wire [31:0] SelSingle03_out1_1;  // ufix32
  wire [31:0] SelSingle03_out1_2;  // ufix32
  reg [31:0] delayMatch79_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch79_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle03_out1_3;  // ufix32
  wire [31:0] Gate03_out1;  // ufix32
  wire [31:0] FeedbackDelay03_out1;  // ufix32
  reg [31:0] FeedbackDelay03_out1_last_value;  // ufix32
  wire [31:0] BankState03_out1;  // ufix32
  wire [31:0] AccumulateAdd03_out1;  // ufix32
  reg [31:0] BankState03_out1_1;  // ufix32
  wire [31:0] HoldOrAcc03_out1;  // ufix32
  wire [31:0] BankState03_out1_2;  // ufix32
  wire [31:0] Sum23_out1;  // ufix32
  wire [31:0] Sum0123_out1;  // ufix32
  wire stateControl_19;
  reg  [67:0] delayMatch139_reg;  // ufix1 [68]
  wire stateControl_20;
  wire Sel04_out1;
  wire UpdateEn04_out1;
  reg  [26:0] delayMatch24_reg;  // ufix1 [27]
  wire UpdateEn04_out1_1;
  wire stateControl_21;
  reg  [66:0] delayMatch150_reg;  // ufix1 [67]
  wire stateControl_22;
  wire [31:0] Gate04_out_1;  // ufix32
  wire [31:0] SelSingle04_out1;  // ufix32
  wire [31:0] SelSingle04_out1_1;  // ufix32
  wire [31:0] SelSingle04_out1_2;  // ufix32
  reg [31:0] delayMatch80_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch80_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle04_out1_3;  // ufix32
  wire [31:0] Gate04_out1;  // ufix32
  wire [31:0] FeedbackDelay04_out1;  // ufix32
  reg [31:0] FeedbackDelay04_out1_last_value;  // ufix32
  wire [31:0] BankState04_out1;  // ufix32
  wire [31:0] AccumulateAdd04_out1;  // ufix32
  reg [31:0] BankState04_out1_1;  // ufix32
  wire [31:0] HoldOrAcc04_out1;  // ufix32
  wire [31:0] BankState04_out1_2;  // ufix32
  wire stateControl_23;
  reg  [67:0] delayMatch140_reg;  // ufix1 [68]
  wire stateControl_24;
  wire Sel05_out1;
  wire UpdateEn05_out1;
  reg  [26:0] delayMatch30_reg;  // ufix1 [27]
  wire UpdateEn05_out1_1;
  wire stateControl_25;
  reg  [66:0] delayMatch151_reg;  // ufix1 [67]
  wire stateControl_26;
  wire [31:0] Gate05_out_1;  // ufix32
  wire [31:0] SelSingle05_out1;  // ufix32
  wire [31:0] SelSingle05_out1_1;  // ufix32
  wire [31:0] SelSingle05_out1_2;  // ufix32
  reg [31:0] delayMatch86_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch86_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle05_out1_3;  // ufix32
  wire [31:0] Gate05_out1;  // ufix32
  wire [31:0] FeedbackDelay05_out1;  // ufix32
  reg [31:0] FeedbackDelay05_out1_last_value;  // ufix32
  wire [31:0] BankState05_out1;  // ufix32
  wire [31:0] AccumulateAdd05_out1;  // ufix32
  reg [31:0] BankState05_out1_1;  // ufix32
  wire [31:0] HoldOrAcc05_out1;  // ufix32
  wire [31:0] BankState05_out1_2;  // ufix32
  wire [31:0] Sum45_out1;  // ufix32
  wire stateControl_27;
  reg  [67:0] delayMatch141_reg;  // ufix1 [68]
  wire stateControl_28;
  wire Sel06_out1;
  wire UpdateEn06_out1;
  reg  [26:0] delayMatch36_reg;  // ufix1 [27]
  wire UpdateEn06_out1_1;
  wire stateControl_29;
  reg  [66:0] delayMatch152_reg;  // ufix1 [67]
  wire stateControl_30;
  wire [31:0] Gate06_out_1;  // ufix32
  wire [31:0] SelSingle06_out1;  // ufix32
  wire [31:0] SelSingle06_out1_1;  // ufix32
  wire [31:0] SelSingle06_out1_2;  // ufix32
  reg [31:0] delayMatch87_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch87_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle06_out1_3;  // ufix32
  wire [31:0] Gate06_out1;  // ufix32
  wire [31:0] FeedbackDelay06_out1;  // ufix32
  reg [31:0] FeedbackDelay06_out1_last_value;  // ufix32
  wire [31:0] BankState06_out1;  // ufix32
  wire [31:0] AccumulateAdd06_out1;  // ufix32
  reg [31:0] BankState06_out1_1;  // ufix32
  wire [31:0] HoldOrAcc06_out1;  // ufix32
  wire [31:0] BankState06_out1_2;  // ufix32
  wire stateControl_31;
  reg  [67:0] delayMatch142_reg;  // ufix1 [68]
  wire stateControl_32;
  wire Sel07_out1;
  wire UpdateEn07_out1;
  reg  [26:0] delayMatch42_reg;  // ufix1 [27]
  wire UpdateEn07_out1_1;
  wire stateControl_33;
  reg  [66:0] delayMatch153_reg;  // ufix1 [67]
  wire stateControl_34;
  wire [31:0] Gate07_out_1;  // ufix32
  wire [31:0] SelSingle07_out1;  // ufix32
  wire [31:0] SelSingle07_out1_1;  // ufix32
  wire [31:0] SelSingle07_out1_2;  // ufix32
  reg [31:0] delayMatch93_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch93_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle07_out1_3;  // ufix32
  wire [31:0] Gate07_out1;  // ufix32
  wire [31:0] FeedbackDelay07_out1;  // ufix32
  reg [31:0] FeedbackDelay07_out1_last_value;  // ufix32
  wire [31:0] BankState07_out1;  // ufix32
  wire [31:0] AccumulateAdd07_out1;  // ufix32
  reg [31:0] BankState07_out1_1;  // ufix32
  wire [31:0] HoldOrAcc07_out1;  // ufix32
  wire [31:0] BankState07_out1_2;  // ufix32
  wire [31:0] Sum67_out1;  // ufix32
  wire [31:0] Sum4567_out1;  // ufix32
  wire [31:0] Sum01234567_out1;  // ufix32
  wire stateControl_35;
  reg  [67:0] delayMatch143_reg;  // ufix1 [68]
  wire stateControl_36;
  wire Sel08_out1;
  wire UpdateEn08_out1;
  reg  [26:0] delayMatch48_reg;  // ufix1 [27]
  wire UpdateEn08_out1_1;
  wire stateControl_37;
  reg  [66:0] delayMatch154_reg;  // ufix1 [67]
  wire stateControl_38;
  wire [31:0] Gate08_out_1;  // ufix32
  wire [31:0] SelSingle08_out1;  // ufix32
  wire [31:0] SelSingle08_out1_1;  // ufix32
  wire [31:0] SelSingle08_out1_2;  // ufix32
  reg [31:0] delayMatch94_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch94_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle08_out1_3;  // ufix32
  wire [31:0] Gate08_out1;  // ufix32
  wire [31:0] FeedbackDelay08_out1;  // ufix32
  reg [31:0] FeedbackDelay08_out1_last_value;  // ufix32
  wire [31:0] BankState08_out1;  // ufix32
  wire [31:0] AccumulateAdd08_out1;  // ufix32
  reg [31:0] BankState08_out1_1;  // ufix32
  wire [31:0] HoldOrAcc08_out1;  // ufix32
  wire [31:0] BankState08_out1_2;  // ufix32
  wire stateControl_39;
  reg  [67:0] delayMatch144_reg;  // ufix1 [68]
  wire stateControl_40;
  wire Sel09_out1;
  wire UpdateEn09_out1;
  reg  [26:0] delayMatch54_reg;  // ufix1 [27]
  wire UpdateEn09_out1_1;
  wire stateControl_41;
  reg  [66:0] delayMatch155_reg;  // ufix1 [67]
  wire stateControl_42;
  wire [31:0] Gate09_out_1;  // ufix32
  wire [31:0] SelSingle09_out1;  // ufix32
  wire [31:0] SelSingle09_out1_1;  // ufix32
  wire [31:0] SelSingle09_out1_2;  // ufix32
  reg [31:0] delayMatch100_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch100_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle09_out1_3;  // ufix32
  wire [31:0] Gate09_out1;  // ufix32
  wire [31:0] FeedbackDelay09_out1;  // ufix32
  reg [31:0] FeedbackDelay09_out1_last_value;  // ufix32
  wire [31:0] BankState09_out1;  // ufix32
  wire [31:0] AccumulateAdd09_out1;  // ufix32
  reg [31:0] BankState09_out1_1;  // ufix32
  wire [31:0] HoldOrAcc09_out1;  // ufix32
  wire [31:0] BankState09_out1_2;  // ufix32
  wire [31:0] Sum89_out1;  // ufix32
  wire stateControl_43;
  reg  [67:0] delayMatch145_reg;  // ufix1 [68]
  wire stateControl_44;
  wire Sel10_out1;
  wire UpdateEn10_out1;
  reg  [26:0] delayMatch60_reg;  // ufix1 [27]
  wire UpdateEn10_out1_1;
  wire stateControl_45;
  reg  [66:0] delayMatch156_reg;  // ufix1 [67]
  wire stateControl_46;
  wire [31:0] Gate10_out_1;  // ufix32
  wire [31:0] SelSingle10_out1;  // ufix32
  wire [31:0] SelSingle10_out1_1;  // ufix32
  wire [31:0] SelSingle10_out1_2;  // ufix32
  reg [31:0] delayMatch106_reg [0:7];  // ufix32 [8]
  reg [31:0] delayMatch106_reg_next [0:7];  // ufix32 [8]
  reg [31:0] SelSingle10_out1_3;  // ufix32
  wire [31:0] Gate10_out1;  // ufix32
  wire [31:0] FeedbackDelay10_out1;  // ufix32
  reg [31:0] FeedbackDelay10_out1_last_value;  // ufix32
  wire [31:0] BankState10_out1;  // ufix32
  wire [31:0] AccumulateAdd10_out1;  // ufix32
  reg [31:0] BankState10_out1_1;  // ufix32
  wire [31:0] HoldOrAcc10_out1;  // ufix32
  wire [31:0] BankState10_out1_2;  // ufix32
  reg [31:0] reduced_reg_2 [0:9];  // ufix32 [10]
  reg [31:0] reduced_reg_next_1 [0:9];  // ufix32 [10]
  reg [31:0] BankState10_out1_3;  // ufix32
  wire [31:0] Sum8910_out1;  // ufix32
  reg [31:0] delayMatch133_reg [0:10];  // ufix32 [11]
  reg [31:0] delayMatch133_reg_next [0:10];  // ufix32 [11]
  reg [31:0] Sum8910_out1_1;  // ufix32
  wire [31:0] SumAll_out1;  // ufix32
  reg signed [31:0] delayMatch66_t_0_0;  // int32
  reg signed [31:0] delayMatch66_t_0_1;  // int32
  reg signed [31:0] delayMatch66_t_1;  // int32
  reg signed [31:0] reduced_t_0_0;  // int32
  reg signed [31:0] reduced_t_0_1;  // int32
  reg signed [31:0] reduced_t_1;  // int32
  reg signed [31:0] delayMatch72_t_0_0;  // int32
  reg signed [31:0] delayMatch72_t_0_1;  // int32
  reg signed [31:0] delayMatch72_t_1;  // int32
  reg signed [31:0] delayMatch73_t_0_0;  // int32
  reg signed [31:0] delayMatch73_t_0_1;  // int32
  reg signed [31:0] delayMatch73_t_1;  // int32
  reg signed [31:0] delayMatch79_t_0_0;  // int32
  reg signed [31:0] delayMatch79_t_0_1;  // int32
  reg signed [31:0] delayMatch79_t_1;  // int32
  reg signed [31:0] delayMatch80_t_0_0;  // int32
  reg signed [31:0] delayMatch80_t_0_1;  // int32
  reg signed [31:0] delayMatch80_t_1;  // int32
  reg signed [31:0] delayMatch86_t_0_0;  // int32
  reg signed [31:0] delayMatch86_t_0_1;  // int32
  reg signed [31:0] delayMatch86_t_1;  // int32
  reg signed [31:0] delayMatch87_t_0_0;  // int32
  reg signed [31:0] delayMatch87_t_0_1;  // int32
  reg signed [31:0] delayMatch87_t_1;  // int32
  reg signed [31:0] delayMatch93_t_0_0;  // int32
  reg signed [31:0] delayMatch93_t_0_1;  // int32
  reg signed [31:0] delayMatch93_t_1;  // int32
  reg signed [31:0] delayMatch94_t_0_0;  // int32
  reg signed [31:0] delayMatch94_t_0_1;  // int32
  reg signed [31:0] delayMatch94_t_1;  // int32
  reg signed [31:0] delayMatch100_t_0_0;  // int32
  reg signed [31:0] delayMatch100_t_0_1;  // int32
  reg signed [31:0] delayMatch100_t_1;  // int32
  reg signed [31:0] delayMatch106_t_0_0;  // int32
  reg signed [31:0] delayMatch106_t_0_1;  // int32
  reg signed [31:0] delayMatch106_t_1;  // int32
  reg signed [31:0] reduced_t_0_0_1;  // int32
  reg signed [31:0] reduced_t_0_1_1;  // int32
  reg signed [31:0] reduced_t_1_1;  // int32
  reg signed [31:0] delayMatch133_t_0_0;  // int32
  reg signed [31:0] delayMatch133_t_0_1;  // int32
  reg signed [31:0] delayMatch133_t_1;  // int32


  assign stateControl = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch135_process
      if (reset == 1'b1) begin
        delayMatch135_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch135_reg[0] <= stateControl;
          delayMatch135_reg[32'sd67:32'sd1] <= delayMatch135_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_1 = delayMatch135_reg[67];

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        reduced_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          reduced_reg[0] <= clear;
          reduced_reg[32'sd26:32'sd1] <= reduced_reg[32'sd25:32'sd0];
        end
      end
    end

  assign ClearBool_out1 = reduced_reg[26];
  assign stateControl_3 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch134_process
      if (reset == 1'b1) begin
        delayMatch134_reg <= {41{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch134_reg[0] <= stateControl_3;
          delayMatch134_reg[32'sd40:32'sd1] <= delayMatch134_reg[32'sd39:32'sd0];
        end
      end
    end

  assign stateControl_4 = delayMatch134_reg[40];

  assign BankIndexOne_out1 = 8'b00000001;
  assign BankIndexZero_out1 = 8'b00000000;
  assign BankIndexAdd_out1 = BankIndexState_out1 + BankIndexOne_out1;
  assign BankIndexIsLast_out1 = BankIndexState_out1 == 8'b00001010;
  assign BankIndexWrap_out1 = (BankIndexIsLast_out1 == 1'b0 ? BankIndexAdd_out1 :
              BankIndexZero_out1);
  assign BankIndexAdvance_out1 = (accumulate == 1'b0 ? BankIndexState_out1 :
              BankIndexWrap_out1);
  assign BankIndexClear_out1 = (clear == 1'b0 ? BankIndexAdvance_out1 :
              BankIndexZero_out1);
  assign BankIndexClear_out1_1 = (stateControl_4 == 1'b0 ? BankIndexState_out1 :
              BankIndexClear_out1);

  always @(posedge clk or posedge reset)
    begin : BankIndexState_process
      if (reset == 1'b1) begin
        BankIndexState_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          BankIndexState_out1 <= BankIndexClear_out1_1;
        end
      end
    end
  assign Sel00_out1 = BankIndexState_out1 == 8'b00000000;
  assign UpdateEn00_out1 = Sel00_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= UpdateEn00_out1;
          delayMatch_reg[32'sd26:32'sd1] <= delayMatch_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn00_out1_1 = delayMatch_reg[26];

  assign stateControl_5 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch146_process
      if (reset == 1'b1) begin
        delayMatch146_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch146_reg[0] <= stateControl_5;
          delayMatch146_reg[32'sd66:32'sd1] <= delayMatch146_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_6 = delayMatch146_reg[66];

  assign AccumulateSingle_out1 = 32'h00000000;

  assign AccumulateSingle_out1_1 = 32'h3f800000;

  assign AccumulateSingle_out1_2 = (accumulate == 1'b0 ? AccumulateSingle_out1 :
              AccumulateSingle_out1_1);

  // mul #1
  nfp_mul_single u_nfp_mul_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(beatSum),  // single
                                 .nfp_in2(AccumulateSingle_out1_2),  // single
                                 .nfp_out(Gate00_out_1)  // single
                                 );
  assign SelSingle00_out1 = 32'h00000000;

  assign SelSingle00_out1_1 = 32'h3f800000;

  assign SelSingle00_out1_2 = (Sel00_out1 == 1'b0 ? SelSingle00_out1 :
              SelSingle00_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch66_process
      if (reset == 1'b1) begin
        for(delayMatch66_t_1 = 32'sd0; delayMatch66_t_1 <= 32'sd7; delayMatch66_t_1 = delayMatch66_t_1 + 32'sd1) begin
          delayMatch66_reg[delayMatch66_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch66_t_0_1 = 32'sd0; delayMatch66_t_0_1 <= 32'sd7; delayMatch66_t_0_1 = delayMatch66_t_0_1 + 32'sd1) begin
            delayMatch66_reg[delayMatch66_t_0_1] <= delayMatch66_reg_next[delayMatch66_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle00_out1_3 = delayMatch66_reg[7];
    delayMatch66_reg_next[0] = SelSingle00_out1_2;

    for(delayMatch66_t_0_0 = 32'sd0; delayMatch66_t_0_0 <= 32'sd6; delayMatch66_t_0_0 = delayMatch66_t_0_0 + 32'sd1) begin
      delayMatch66_reg_next[delayMatch66_t_0_0 + 32'sd1] = delayMatch66_reg[delayMatch66_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_1 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Gate00_out_1),  // single
                                   .nfp_in2(SelSingle00_out1_3),  // single
                                   .nfp_out(Gate00_out1)  // single
                                   );
  assign ZeroSingle_out1 = 32'h00000000;
  always @(posedge clk or posedge reset)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        for(reduced_t_1 = 32'sd0; reduced_t_1 <= 32'sd26; reduced_t_1 = reduced_t_1 + 32'sd1) begin
          reduced_reg_1[reduced_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(reduced_t_0_1 = 32'sd0; reduced_t_0_1 <= 32'sd26; reduced_t_0_1 = reduced_t_0_1 + 32'sd1) begin
            reduced_reg_1[reduced_t_0_1] <= reduced_reg_next[reduced_t_0_1];
          end
        end
      end
    end

  always @* begin
    ZeroSingle_out1_1 = reduced_reg_1[26];
    reduced_reg_next[0] = ZeroSingle_out1;

    for(reduced_t_0_0 = 32'sd0; reduced_t_0_0 <= 32'sd25; reduced_t_0_0 = reduced_t_0_0 + 32'sd1) begin
      reduced_reg_next[reduced_t_0_0 + 32'sd1] = reduced_reg_1[reduced_t_0_0];
    end

  end

  always @(posedge clk or posedge reset)
    begin : out0_bypass1_process
      if (reset == 1'b1) begin
        FeedbackDelay00_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay00_out1_last_value <= FeedbackDelay00_out1;
        end
      end
    end

  assign FeedbackDelay00_out1 = (stateControl_6 == 1'b0 ? FeedbackDelay00_out1_last_value :
              BankState00_out1);

  nfp_add_single u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(FeedbackDelay00_out1),  // single
                                 .nfp_in2(Gate00_out1),  // single
                                 .nfp_out(AccumulateAdd00_out1)  // single
                                 );
  assign HoldOrAcc00_out1 = (UpdateEn00_out1_1 == 1'b0 ? BankState00_out1_1 :
              AccumulateAdd00_out1);
  assign BankState00_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc00_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        BankState00_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState00_out1_1 <= BankState00_out1;
        end
      end
    end

  assign BankState00_out1 = (stateControl_1 == 1'b0 ? BankState00_out1_1 :
              BankState00_out1_2);

  assign stateControl_7 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch136_process
      if (reset == 1'b1) begin
        delayMatch136_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch136_reg[0] <= stateControl_7;
          delayMatch136_reg[32'sd67:32'sd1] <= delayMatch136_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_8 = delayMatch136_reg[67];

  assign Sel01_out1 = BankIndexState_out1 == 8'b00000001;
  assign UpdateEn01_out1 = Sel01_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch6_process
      if (reset == 1'b1) begin
        delayMatch6_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch6_reg[0] <= UpdateEn01_out1;
          delayMatch6_reg[32'sd26:32'sd1] <= delayMatch6_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn01_out1_1 = delayMatch6_reg[26];

  assign stateControl_9 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch147_process
      if (reset == 1'b1) begin
        delayMatch147_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch147_reg[0] <= stateControl_9;
          delayMatch147_reg[32'sd66:32'sd1] <= delayMatch147_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_10 = delayMatch147_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_2 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(beatSum),  // single
                                   .nfp_in2(AccumulateSingle_out1_2),  // single
                                   .nfp_out(Gate01_out_1)  // single
                                   );
  assign SelSingle01_out1 = 32'h00000000;

  assign SelSingle01_out1_1 = 32'h3f800000;

  assign SelSingle01_out1_2 = (Sel01_out1 == 1'b0 ? SelSingle01_out1 :
              SelSingle01_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch72_process
      if (reset == 1'b1) begin
        for(delayMatch72_t_1 = 32'sd0; delayMatch72_t_1 <= 32'sd7; delayMatch72_t_1 = delayMatch72_t_1 + 32'sd1) begin
          delayMatch72_reg[delayMatch72_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch72_t_0_1 = 32'sd0; delayMatch72_t_0_1 <= 32'sd7; delayMatch72_t_0_1 = delayMatch72_t_0_1 + 32'sd1) begin
            delayMatch72_reg[delayMatch72_t_0_1] <= delayMatch72_reg_next[delayMatch72_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle01_out1_3 = delayMatch72_reg[7];
    delayMatch72_reg_next[0] = SelSingle01_out1_2;

    for(delayMatch72_t_0_0 = 32'sd0; delayMatch72_t_0_0 <= 32'sd6; delayMatch72_t_0_0 = delayMatch72_t_0_0 + 32'sd1) begin
      delayMatch72_reg_next[delayMatch72_t_0_0 + 32'sd1] = delayMatch72_reg[delayMatch72_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_3 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Gate01_out_1),  // single
                                   .nfp_in2(SelSingle01_out1_3),  // single
                                   .nfp_out(Gate01_out1)  // single
                                   );
  always @(posedge clk or posedge reset)
    begin : out0_bypass3_process
      if (reset == 1'b1) begin
        FeedbackDelay01_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay01_out1_last_value <= FeedbackDelay01_out1;
        end
      end
    end

  assign FeedbackDelay01_out1 = (stateControl_10 == 1'b0 ? FeedbackDelay01_out1_last_value :
              BankState01_out1);

  nfp_add_single u_nfp_add_comp_1 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(FeedbackDelay01_out1),  // single
                                   .nfp_in2(Gate01_out1),  // single
                                   .nfp_out(AccumulateAdd01_out1)  // single
                                   );
  assign HoldOrAcc01_out1 = (UpdateEn01_out1_1 == 1'b0 ? BankState01_out1_1 :
              AccumulateAdd01_out1);
  assign BankState01_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc01_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_3_process
      if (reset == 1'b1) begin
        BankState01_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState01_out1_1 <= BankState01_out1;
        end
      end
    end

  assign BankState01_out1 = (stateControl_8 == 1'b0 ? BankState01_out1_1 :
              BankState01_out1_2);

  nfp_add_single u_nfp_add_comp_2 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(BankState00_out1),  // single
                                   .nfp_in2(BankState01_out1),  // single
                                   .nfp_out(Sum01_out1)  // single
                                   );
  assign stateControl_11 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch137_process
      if (reset == 1'b1) begin
        delayMatch137_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch137_reg[0] <= stateControl_11;
          delayMatch137_reg[32'sd67:32'sd1] <= delayMatch137_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_12 = delayMatch137_reg[67];

  assign Sel02_out1 = BankIndexState_out1 == 8'b00000010;
  assign UpdateEn02_out1 = Sel02_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch12_process
      if (reset == 1'b1) begin
        delayMatch12_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch12_reg[0] <= UpdateEn02_out1;
          delayMatch12_reg[32'sd26:32'sd1] <= delayMatch12_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn02_out1_1 = delayMatch12_reg[26];

  assign stateControl_13 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch148_process
      if (reset == 1'b1) begin
        delayMatch148_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch148_reg[0] <= stateControl_13;
          delayMatch148_reg[32'sd66:32'sd1] <= delayMatch148_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_14 = delayMatch148_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_4 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(beatSum),  // single
                                   .nfp_in2(AccumulateSingle_out1_2),  // single
                                   .nfp_out(Gate02_out_1)  // single
                                   );
  assign SelSingle02_out1 = 32'h00000000;

  assign SelSingle02_out1_1 = 32'h3f800000;

  assign SelSingle02_out1_2 = (Sel02_out1 == 1'b0 ? SelSingle02_out1 :
              SelSingle02_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch73_process
      if (reset == 1'b1) begin
        for(delayMatch73_t_1 = 32'sd0; delayMatch73_t_1 <= 32'sd7; delayMatch73_t_1 = delayMatch73_t_1 + 32'sd1) begin
          delayMatch73_reg[delayMatch73_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch73_t_0_1 = 32'sd0; delayMatch73_t_0_1 <= 32'sd7; delayMatch73_t_0_1 = delayMatch73_t_0_1 + 32'sd1) begin
            delayMatch73_reg[delayMatch73_t_0_1] <= delayMatch73_reg_next[delayMatch73_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle02_out1_3 = delayMatch73_reg[7];
    delayMatch73_reg_next[0] = SelSingle02_out1_2;

    for(delayMatch73_t_0_0 = 32'sd0; delayMatch73_t_0_0 <= 32'sd6; delayMatch73_t_0_0 = delayMatch73_t_0_0 + 32'sd1) begin
      delayMatch73_reg_next[delayMatch73_t_0_0 + 32'sd1] = delayMatch73_reg[delayMatch73_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_5 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Gate02_out_1),  // single
                                   .nfp_in2(SelSingle02_out1_3),  // single
                                   .nfp_out(Gate02_out1)  // single
                                   );
  always @(posedge clk or posedge reset)
    begin : out0_bypass5_process
      if (reset == 1'b1) begin
        FeedbackDelay02_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay02_out1_last_value <= FeedbackDelay02_out1;
        end
      end
    end

  assign FeedbackDelay02_out1 = (stateControl_14 == 1'b0 ? FeedbackDelay02_out1_last_value :
              BankState02_out1);

  nfp_add_single u_nfp_add_comp_3 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(FeedbackDelay02_out1),  // single
                                   .nfp_in2(Gate02_out1),  // single
                                   .nfp_out(AccumulateAdd02_out1)  // single
                                   );
  assign HoldOrAcc02_out1 = (UpdateEn02_out1_1 == 1'b0 ? BankState02_out1_1 :
              AccumulateAdd02_out1);
  assign BankState02_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc02_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_4_process
      if (reset == 1'b1) begin
        BankState02_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState02_out1_1 <= BankState02_out1;
        end
      end
    end

  assign BankState02_out1 = (stateControl_12 == 1'b0 ? BankState02_out1_1 :
              BankState02_out1_2);

  assign stateControl_15 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch138_process
      if (reset == 1'b1) begin
        delayMatch138_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch138_reg[0] <= stateControl_15;
          delayMatch138_reg[32'sd67:32'sd1] <= delayMatch138_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_16 = delayMatch138_reg[67];

  assign Sel03_out1 = BankIndexState_out1 == 8'b00000011;
  assign UpdateEn03_out1 = Sel03_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch18_process
      if (reset == 1'b1) begin
        delayMatch18_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch18_reg[0] <= UpdateEn03_out1;
          delayMatch18_reg[32'sd26:32'sd1] <= delayMatch18_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn03_out1_1 = delayMatch18_reg[26];

  assign stateControl_17 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch149_process
      if (reset == 1'b1) begin
        delayMatch149_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch149_reg[0] <= stateControl_17;
          delayMatch149_reg[32'sd66:32'sd1] <= delayMatch149_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_18 = delayMatch149_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_6 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(beatSum),  // single
                                   .nfp_in2(AccumulateSingle_out1_2),  // single
                                   .nfp_out(Gate03_out_1)  // single
                                   );
  assign SelSingle03_out1 = 32'h00000000;

  assign SelSingle03_out1_1 = 32'h3f800000;

  assign SelSingle03_out1_2 = (Sel03_out1 == 1'b0 ? SelSingle03_out1 :
              SelSingle03_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch79_process
      if (reset == 1'b1) begin
        for(delayMatch79_t_1 = 32'sd0; delayMatch79_t_1 <= 32'sd7; delayMatch79_t_1 = delayMatch79_t_1 + 32'sd1) begin
          delayMatch79_reg[delayMatch79_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch79_t_0_1 = 32'sd0; delayMatch79_t_0_1 <= 32'sd7; delayMatch79_t_0_1 = delayMatch79_t_0_1 + 32'sd1) begin
            delayMatch79_reg[delayMatch79_t_0_1] <= delayMatch79_reg_next[delayMatch79_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle03_out1_3 = delayMatch79_reg[7];
    delayMatch79_reg_next[0] = SelSingle03_out1_2;

    for(delayMatch79_t_0_0 = 32'sd0; delayMatch79_t_0_0 <= 32'sd6; delayMatch79_t_0_0 = delayMatch79_t_0_0 + 32'sd1) begin
      delayMatch79_reg_next[delayMatch79_t_0_0 + 32'sd1] = delayMatch79_reg[delayMatch79_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_7 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Gate03_out_1),  // single
                                   .nfp_in2(SelSingle03_out1_3),  // single
                                   .nfp_out(Gate03_out1)  // single
                                   );
  always @(posedge clk or posedge reset)
    begin : out0_bypass7_process
      if (reset == 1'b1) begin
        FeedbackDelay03_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay03_out1_last_value <= FeedbackDelay03_out1;
        end
      end
    end

  assign FeedbackDelay03_out1 = (stateControl_18 == 1'b0 ? FeedbackDelay03_out1_last_value :
              BankState03_out1);

  nfp_add_single u_nfp_add_comp_4 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(FeedbackDelay03_out1),  // single
                                   .nfp_in2(Gate03_out1),  // single
                                   .nfp_out(AccumulateAdd03_out1)  // single
                                   );
  assign HoldOrAcc03_out1 = (UpdateEn03_out1_1 == 1'b0 ? BankState03_out1_1 :
              AccumulateAdd03_out1);
  assign BankState03_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc03_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_5_process
      if (reset == 1'b1) begin
        BankState03_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState03_out1_1 <= BankState03_out1;
        end
      end
    end

  assign BankState03_out1 = (stateControl_16 == 1'b0 ? BankState03_out1_1 :
              BankState03_out1_2);

  nfp_add_single u_nfp_add_comp_5 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(BankState02_out1),  // single
                                   .nfp_in2(BankState03_out1),  // single
                                   .nfp_out(Sum23_out1)  // single
                                   );
  nfp_add_single u_nfp_add_comp_6 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Sum01_out1),  // single
                                   .nfp_in2(Sum23_out1),  // single
                                   .nfp_out(Sum0123_out1)  // single
                                   );
  assign stateControl_19 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch139_process
      if (reset == 1'b1) begin
        delayMatch139_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch139_reg[0] <= stateControl_19;
          delayMatch139_reg[32'sd67:32'sd1] <= delayMatch139_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_20 = delayMatch139_reg[67];

  assign Sel04_out1 = BankIndexState_out1 == 8'b00000100;
  assign UpdateEn04_out1 = Sel04_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch24_process
      if (reset == 1'b1) begin
        delayMatch24_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch24_reg[0] <= UpdateEn04_out1;
          delayMatch24_reg[32'sd26:32'sd1] <= delayMatch24_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn04_out1_1 = delayMatch24_reg[26];

  assign stateControl_21 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch150_process
      if (reset == 1'b1) begin
        delayMatch150_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch150_reg[0] <= stateControl_21;
          delayMatch150_reg[32'sd66:32'sd1] <= delayMatch150_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_22 = delayMatch150_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_8 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(beatSum),  // single
                                   .nfp_in2(AccumulateSingle_out1_2),  // single
                                   .nfp_out(Gate04_out_1)  // single
                                   );
  assign SelSingle04_out1 = 32'h00000000;

  assign SelSingle04_out1_1 = 32'h3f800000;

  assign SelSingle04_out1_2 = (Sel04_out1 == 1'b0 ? SelSingle04_out1 :
              SelSingle04_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch80_process
      if (reset == 1'b1) begin
        for(delayMatch80_t_1 = 32'sd0; delayMatch80_t_1 <= 32'sd7; delayMatch80_t_1 = delayMatch80_t_1 + 32'sd1) begin
          delayMatch80_reg[delayMatch80_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch80_t_0_1 = 32'sd0; delayMatch80_t_0_1 <= 32'sd7; delayMatch80_t_0_1 = delayMatch80_t_0_1 + 32'sd1) begin
            delayMatch80_reg[delayMatch80_t_0_1] <= delayMatch80_reg_next[delayMatch80_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle04_out1_3 = delayMatch80_reg[7];
    delayMatch80_reg_next[0] = SelSingle04_out1_2;

    for(delayMatch80_t_0_0 = 32'sd0; delayMatch80_t_0_0 <= 32'sd6; delayMatch80_t_0_0 = delayMatch80_t_0_0 + 32'sd1) begin
      delayMatch80_reg_next[delayMatch80_t_0_0 + 32'sd1] = delayMatch80_reg[delayMatch80_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_9 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Gate04_out_1),  // single
                                   .nfp_in2(SelSingle04_out1_3),  // single
                                   .nfp_out(Gate04_out1)  // single
                                   );
  always @(posedge clk or posedge reset)
    begin : out0_bypass9_process
      if (reset == 1'b1) begin
        FeedbackDelay04_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay04_out1_last_value <= FeedbackDelay04_out1;
        end
      end
    end

  assign FeedbackDelay04_out1 = (stateControl_22 == 1'b0 ? FeedbackDelay04_out1_last_value :
              BankState04_out1);

  nfp_add_single u_nfp_add_comp_7 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(FeedbackDelay04_out1),  // single
                                   .nfp_in2(Gate04_out1),  // single
                                   .nfp_out(AccumulateAdd04_out1)  // single
                                   );
  assign HoldOrAcc04_out1 = (UpdateEn04_out1_1 == 1'b0 ? BankState04_out1_1 :
              AccumulateAdd04_out1);
  assign BankState04_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc04_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_6_process
      if (reset == 1'b1) begin
        BankState04_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState04_out1_1 <= BankState04_out1;
        end
      end
    end

  assign BankState04_out1 = (stateControl_20 == 1'b0 ? BankState04_out1_1 :
              BankState04_out1_2);

  assign stateControl_23 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch140_process
      if (reset == 1'b1) begin
        delayMatch140_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch140_reg[0] <= stateControl_23;
          delayMatch140_reg[32'sd67:32'sd1] <= delayMatch140_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_24 = delayMatch140_reg[67];

  assign Sel05_out1 = BankIndexState_out1 == 8'b00000101;
  assign UpdateEn05_out1 = Sel05_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch30_process
      if (reset == 1'b1) begin
        delayMatch30_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch30_reg[0] <= UpdateEn05_out1;
          delayMatch30_reg[32'sd26:32'sd1] <= delayMatch30_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn05_out1_1 = delayMatch30_reg[26];

  assign stateControl_25 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch151_process
      if (reset == 1'b1) begin
        delayMatch151_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch151_reg[0] <= stateControl_25;
          delayMatch151_reg[32'sd66:32'sd1] <= delayMatch151_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_26 = delayMatch151_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_10 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(beatSum),  // single
                                    .nfp_in2(AccumulateSingle_out1_2),  // single
                                    .nfp_out(Gate05_out_1)  // single
                                    );
  assign SelSingle05_out1 = 32'h00000000;

  assign SelSingle05_out1_1 = 32'h3f800000;

  assign SelSingle05_out1_2 = (Sel05_out1 == 1'b0 ? SelSingle05_out1 :
              SelSingle05_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch86_process
      if (reset == 1'b1) begin
        for(delayMatch86_t_1 = 32'sd0; delayMatch86_t_1 <= 32'sd7; delayMatch86_t_1 = delayMatch86_t_1 + 32'sd1) begin
          delayMatch86_reg[delayMatch86_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch86_t_0_1 = 32'sd0; delayMatch86_t_0_1 <= 32'sd7; delayMatch86_t_0_1 = delayMatch86_t_0_1 + 32'sd1) begin
            delayMatch86_reg[delayMatch86_t_0_1] <= delayMatch86_reg_next[delayMatch86_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle05_out1_3 = delayMatch86_reg[7];
    delayMatch86_reg_next[0] = SelSingle05_out1_2;

    for(delayMatch86_t_0_0 = 32'sd0; delayMatch86_t_0_0 <= 32'sd6; delayMatch86_t_0_0 = delayMatch86_t_0_0 + 32'sd1) begin
      delayMatch86_reg_next[delayMatch86_t_0_0 + 32'sd1] = delayMatch86_reg[delayMatch86_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_11 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Gate05_out_1),  // single
                                    .nfp_in2(SelSingle05_out1_3),  // single
                                    .nfp_out(Gate05_out1)  // single
                                    );
  always @(posedge clk or posedge reset)
    begin : out0_bypass11_process
      if (reset == 1'b1) begin
        FeedbackDelay05_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay05_out1_last_value <= FeedbackDelay05_out1;
        end
      end
    end

  assign FeedbackDelay05_out1 = (stateControl_26 == 1'b0 ? FeedbackDelay05_out1_last_value :
              BankState05_out1);

  nfp_add_single u_nfp_add_comp_8 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(FeedbackDelay05_out1),  // single
                                   .nfp_in2(Gate05_out1),  // single
                                   .nfp_out(AccumulateAdd05_out1)  // single
                                   );
  assign HoldOrAcc05_out1 = (UpdateEn05_out1_1 == 1'b0 ? BankState05_out1_1 :
              AccumulateAdd05_out1);
  assign BankState05_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc05_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_7_process
      if (reset == 1'b1) begin
        BankState05_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState05_out1_1 <= BankState05_out1;
        end
      end
    end

  assign BankState05_out1 = (stateControl_24 == 1'b0 ? BankState05_out1_1 :
              BankState05_out1_2);

  nfp_add_single u_nfp_add_comp_9 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(BankState04_out1),  // single
                                   .nfp_in2(BankState05_out1),  // single
                                   .nfp_out(Sum45_out1)  // single
                                   );
  assign stateControl_27 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch141_process
      if (reset == 1'b1) begin
        delayMatch141_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch141_reg[0] <= stateControl_27;
          delayMatch141_reg[32'sd67:32'sd1] <= delayMatch141_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_28 = delayMatch141_reg[67];

  assign Sel06_out1 = BankIndexState_out1 == 8'b00000110;
  assign UpdateEn06_out1 = Sel06_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch36_process
      if (reset == 1'b1) begin
        delayMatch36_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch36_reg[0] <= UpdateEn06_out1;
          delayMatch36_reg[32'sd26:32'sd1] <= delayMatch36_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn06_out1_1 = delayMatch36_reg[26];

  assign stateControl_29 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch152_process
      if (reset == 1'b1) begin
        delayMatch152_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch152_reg[0] <= stateControl_29;
          delayMatch152_reg[32'sd66:32'sd1] <= delayMatch152_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_30 = delayMatch152_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_12 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(beatSum),  // single
                                    .nfp_in2(AccumulateSingle_out1_2),  // single
                                    .nfp_out(Gate06_out_1)  // single
                                    );
  assign SelSingle06_out1 = 32'h00000000;

  assign SelSingle06_out1_1 = 32'h3f800000;

  assign SelSingle06_out1_2 = (Sel06_out1 == 1'b0 ? SelSingle06_out1 :
              SelSingle06_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch87_process
      if (reset == 1'b1) begin
        for(delayMatch87_t_1 = 32'sd0; delayMatch87_t_1 <= 32'sd7; delayMatch87_t_1 = delayMatch87_t_1 + 32'sd1) begin
          delayMatch87_reg[delayMatch87_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch87_t_0_1 = 32'sd0; delayMatch87_t_0_1 <= 32'sd7; delayMatch87_t_0_1 = delayMatch87_t_0_1 + 32'sd1) begin
            delayMatch87_reg[delayMatch87_t_0_1] <= delayMatch87_reg_next[delayMatch87_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle06_out1_3 = delayMatch87_reg[7];
    delayMatch87_reg_next[0] = SelSingle06_out1_2;

    for(delayMatch87_t_0_0 = 32'sd0; delayMatch87_t_0_0 <= 32'sd6; delayMatch87_t_0_0 = delayMatch87_t_0_0 + 32'sd1) begin
      delayMatch87_reg_next[delayMatch87_t_0_0 + 32'sd1] = delayMatch87_reg[delayMatch87_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_13 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Gate06_out_1),  // single
                                    .nfp_in2(SelSingle06_out1_3),  // single
                                    .nfp_out(Gate06_out1)  // single
                                    );
  always @(posedge clk or posedge reset)
    begin : out0_bypass13_process
      if (reset == 1'b1) begin
        FeedbackDelay06_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay06_out1_last_value <= FeedbackDelay06_out1;
        end
      end
    end

  assign FeedbackDelay06_out1 = (stateControl_30 == 1'b0 ? FeedbackDelay06_out1_last_value :
              BankState06_out1);

  nfp_add_single u_nfp_add_comp_10 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(FeedbackDelay06_out1),  // single
                                    .nfp_in2(Gate06_out1),  // single
                                    .nfp_out(AccumulateAdd06_out1)  // single
                                    );
  assign HoldOrAcc06_out1 = (UpdateEn06_out1_1 == 1'b0 ? BankState06_out1_1 :
              AccumulateAdd06_out1);
  assign BankState06_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc06_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_8_process
      if (reset == 1'b1) begin
        BankState06_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState06_out1_1 <= BankState06_out1;
        end
      end
    end

  assign BankState06_out1 = (stateControl_28 == 1'b0 ? BankState06_out1_1 :
              BankState06_out1_2);

  assign stateControl_31 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch142_process
      if (reset == 1'b1) begin
        delayMatch142_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch142_reg[0] <= stateControl_31;
          delayMatch142_reg[32'sd67:32'sd1] <= delayMatch142_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_32 = delayMatch142_reg[67];

  assign Sel07_out1 = BankIndexState_out1 == 8'b00000111;
  assign UpdateEn07_out1 = Sel07_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch42_process
      if (reset == 1'b1) begin
        delayMatch42_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch42_reg[0] <= UpdateEn07_out1;
          delayMatch42_reg[32'sd26:32'sd1] <= delayMatch42_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn07_out1_1 = delayMatch42_reg[26];

  assign stateControl_33 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch153_process
      if (reset == 1'b1) begin
        delayMatch153_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch153_reg[0] <= stateControl_33;
          delayMatch153_reg[32'sd66:32'sd1] <= delayMatch153_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_34 = delayMatch153_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_14 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(beatSum),  // single
                                    .nfp_in2(AccumulateSingle_out1_2),  // single
                                    .nfp_out(Gate07_out_1)  // single
                                    );
  assign SelSingle07_out1 = 32'h00000000;

  assign SelSingle07_out1_1 = 32'h3f800000;

  assign SelSingle07_out1_2 = (Sel07_out1 == 1'b0 ? SelSingle07_out1 :
              SelSingle07_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch93_process
      if (reset == 1'b1) begin
        for(delayMatch93_t_1 = 32'sd0; delayMatch93_t_1 <= 32'sd7; delayMatch93_t_1 = delayMatch93_t_1 + 32'sd1) begin
          delayMatch93_reg[delayMatch93_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch93_t_0_1 = 32'sd0; delayMatch93_t_0_1 <= 32'sd7; delayMatch93_t_0_1 = delayMatch93_t_0_1 + 32'sd1) begin
            delayMatch93_reg[delayMatch93_t_0_1] <= delayMatch93_reg_next[delayMatch93_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle07_out1_3 = delayMatch93_reg[7];
    delayMatch93_reg_next[0] = SelSingle07_out1_2;

    for(delayMatch93_t_0_0 = 32'sd0; delayMatch93_t_0_0 <= 32'sd6; delayMatch93_t_0_0 = delayMatch93_t_0_0 + 32'sd1) begin
      delayMatch93_reg_next[delayMatch93_t_0_0 + 32'sd1] = delayMatch93_reg[delayMatch93_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_15 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Gate07_out_1),  // single
                                    .nfp_in2(SelSingle07_out1_3),  // single
                                    .nfp_out(Gate07_out1)  // single
                                    );
  always @(posedge clk or posedge reset)
    begin : out0_bypass15_process
      if (reset == 1'b1) begin
        FeedbackDelay07_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay07_out1_last_value <= FeedbackDelay07_out1;
        end
      end
    end

  assign FeedbackDelay07_out1 = (stateControl_34 == 1'b0 ? FeedbackDelay07_out1_last_value :
              BankState07_out1);

  nfp_add_single u_nfp_add_comp_11 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(FeedbackDelay07_out1),  // single
                                    .nfp_in2(Gate07_out1),  // single
                                    .nfp_out(AccumulateAdd07_out1)  // single
                                    );
  assign HoldOrAcc07_out1 = (UpdateEn07_out1_1 == 1'b0 ? BankState07_out1_1 :
              AccumulateAdd07_out1);
  assign BankState07_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc07_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_9_process
      if (reset == 1'b1) begin
        BankState07_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState07_out1_1 <= BankState07_out1;
        end
      end
    end

  assign BankState07_out1 = (stateControl_32 == 1'b0 ? BankState07_out1_1 :
              BankState07_out1_2);

  nfp_add_single u_nfp_add_comp_12 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(BankState06_out1),  // single
                                    .nfp_in2(BankState07_out1),  // single
                                    .nfp_out(Sum67_out1)  // single
                                    );
  nfp_add_single u_nfp_add_comp_13 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Sum45_out1),  // single
                                    .nfp_in2(Sum67_out1),  // single
                                    .nfp_out(Sum4567_out1)  // single
                                    );
  nfp_add_single u_nfp_add_comp_14 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Sum0123_out1),  // single
                                    .nfp_in2(Sum4567_out1),  // single
                                    .nfp_out(Sum01234567_out1)  // single
                                    );
  assign stateControl_35 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch143_process
      if (reset == 1'b1) begin
        delayMatch143_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch143_reg[0] <= stateControl_35;
          delayMatch143_reg[32'sd67:32'sd1] <= delayMatch143_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_36 = delayMatch143_reg[67];

  assign Sel08_out1 = BankIndexState_out1 == 8'b00001000;
  assign UpdateEn08_out1 = Sel08_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch48_process
      if (reset == 1'b1) begin
        delayMatch48_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch48_reg[0] <= UpdateEn08_out1;
          delayMatch48_reg[32'sd26:32'sd1] <= delayMatch48_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn08_out1_1 = delayMatch48_reg[26];

  assign stateControl_37 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch154_process
      if (reset == 1'b1) begin
        delayMatch154_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch154_reg[0] <= stateControl_37;
          delayMatch154_reg[32'sd66:32'sd1] <= delayMatch154_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_38 = delayMatch154_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_16 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(beatSum),  // single
                                    .nfp_in2(AccumulateSingle_out1_2),  // single
                                    .nfp_out(Gate08_out_1)  // single
                                    );
  assign SelSingle08_out1 = 32'h00000000;

  assign SelSingle08_out1_1 = 32'h3f800000;

  assign SelSingle08_out1_2 = (Sel08_out1 == 1'b0 ? SelSingle08_out1 :
              SelSingle08_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch94_process
      if (reset == 1'b1) begin
        for(delayMatch94_t_1 = 32'sd0; delayMatch94_t_1 <= 32'sd7; delayMatch94_t_1 = delayMatch94_t_1 + 32'sd1) begin
          delayMatch94_reg[delayMatch94_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch94_t_0_1 = 32'sd0; delayMatch94_t_0_1 <= 32'sd7; delayMatch94_t_0_1 = delayMatch94_t_0_1 + 32'sd1) begin
            delayMatch94_reg[delayMatch94_t_0_1] <= delayMatch94_reg_next[delayMatch94_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle08_out1_3 = delayMatch94_reg[7];
    delayMatch94_reg_next[0] = SelSingle08_out1_2;

    for(delayMatch94_t_0_0 = 32'sd0; delayMatch94_t_0_0 <= 32'sd6; delayMatch94_t_0_0 = delayMatch94_t_0_0 + 32'sd1) begin
      delayMatch94_reg_next[delayMatch94_t_0_0 + 32'sd1] = delayMatch94_reg[delayMatch94_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_17 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Gate08_out_1),  // single
                                    .nfp_in2(SelSingle08_out1_3),  // single
                                    .nfp_out(Gate08_out1)  // single
                                    );
  always @(posedge clk or posedge reset)
    begin : out0_bypass17_process
      if (reset == 1'b1) begin
        FeedbackDelay08_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay08_out1_last_value <= FeedbackDelay08_out1;
        end
      end
    end

  assign FeedbackDelay08_out1 = (stateControl_38 == 1'b0 ? FeedbackDelay08_out1_last_value :
              BankState08_out1);

  nfp_add_single u_nfp_add_comp_15 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(FeedbackDelay08_out1),  // single
                                    .nfp_in2(Gate08_out1),  // single
                                    .nfp_out(AccumulateAdd08_out1)  // single
                                    );
  assign HoldOrAcc08_out1 = (UpdateEn08_out1_1 == 1'b0 ? BankState08_out1_1 :
              AccumulateAdd08_out1);
  assign BankState08_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc08_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_10_process
      if (reset == 1'b1) begin
        BankState08_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState08_out1_1 <= BankState08_out1;
        end
      end
    end

  assign BankState08_out1 = (stateControl_36 == 1'b0 ? BankState08_out1_1 :
              BankState08_out1_2);

  assign stateControl_39 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch144_process
      if (reset == 1'b1) begin
        delayMatch144_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch144_reg[0] <= stateControl_39;
          delayMatch144_reg[32'sd67:32'sd1] <= delayMatch144_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_40 = delayMatch144_reg[67];

  assign Sel09_out1 = BankIndexState_out1 == 8'b00001001;
  assign UpdateEn09_out1 = Sel09_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch54_process
      if (reset == 1'b1) begin
        delayMatch54_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch54_reg[0] <= UpdateEn09_out1;
          delayMatch54_reg[32'sd26:32'sd1] <= delayMatch54_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn09_out1_1 = delayMatch54_reg[26];

  assign stateControl_41 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch155_process
      if (reset == 1'b1) begin
        delayMatch155_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch155_reg[0] <= stateControl_41;
          delayMatch155_reg[32'sd66:32'sd1] <= delayMatch155_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_42 = delayMatch155_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_18 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(beatSum),  // single
                                    .nfp_in2(AccumulateSingle_out1_2),  // single
                                    .nfp_out(Gate09_out_1)  // single
                                    );
  assign SelSingle09_out1 = 32'h00000000;

  assign SelSingle09_out1_1 = 32'h3f800000;

  assign SelSingle09_out1_2 = (Sel09_out1 == 1'b0 ? SelSingle09_out1 :
              SelSingle09_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch100_process
      if (reset == 1'b1) begin
        for(delayMatch100_t_1 = 32'sd0; delayMatch100_t_1 <= 32'sd7; delayMatch100_t_1 = delayMatch100_t_1 + 32'sd1) begin
          delayMatch100_reg[delayMatch100_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch100_t_0_1 = 32'sd0; delayMatch100_t_0_1 <= 32'sd7; delayMatch100_t_0_1 = delayMatch100_t_0_1 + 32'sd1) begin
            delayMatch100_reg[delayMatch100_t_0_1] <= delayMatch100_reg_next[delayMatch100_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle09_out1_3 = delayMatch100_reg[7];
    delayMatch100_reg_next[0] = SelSingle09_out1_2;

    for(delayMatch100_t_0_0 = 32'sd0; delayMatch100_t_0_0 <= 32'sd6; delayMatch100_t_0_0 = delayMatch100_t_0_0 + 32'sd1) begin
      delayMatch100_reg_next[delayMatch100_t_0_0 + 32'sd1] = delayMatch100_reg[delayMatch100_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_19 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Gate09_out_1),  // single
                                    .nfp_in2(SelSingle09_out1_3),  // single
                                    .nfp_out(Gate09_out1)  // single
                                    );
  always @(posedge clk or posedge reset)
    begin : out0_bypass19_process
      if (reset == 1'b1) begin
        FeedbackDelay09_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay09_out1_last_value <= FeedbackDelay09_out1;
        end
      end
    end

  assign FeedbackDelay09_out1 = (stateControl_42 == 1'b0 ? FeedbackDelay09_out1_last_value :
              BankState09_out1);

  nfp_add_single u_nfp_add_comp_16 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(FeedbackDelay09_out1),  // single
                                    .nfp_in2(Gate09_out1),  // single
                                    .nfp_out(AccumulateAdd09_out1)  // single
                                    );
  assign HoldOrAcc09_out1 = (UpdateEn09_out1_1 == 1'b0 ? BankState09_out1_1 :
              AccumulateAdd09_out1);
  assign BankState09_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc09_out1 :
              ZeroSingle_out1_1);
  always @(posedge clk or posedge reset)
    begin : reduced_11_process
      if (reset == 1'b1) begin
        BankState09_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState09_out1_1 <= BankState09_out1;
        end
      end
    end

  assign BankState09_out1 = (stateControl_40 == 1'b0 ? BankState09_out1_1 :
              BankState09_out1_2);

  nfp_add_single u_nfp_add_comp_17 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(BankState08_out1),  // single
                                    .nfp_in2(BankState09_out1),  // single
                                    .nfp_out(Sum89_out1)  // single
                                    );
  assign stateControl_43 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch145_process
      if (reset == 1'b1) begin
        delayMatch145_reg <= {68{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch145_reg[0] <= stateControl_43;
          delayMatch145_reg[32'sd67:32'sd1] <= delayMatch145_reg[32'sd66:32'sd0];
        end
      end
    end

  assign stateControl_44 = delayMatch145_reg[67];

  assign Sel10_out1 = BankIndexState_out1 == 8'b00001010;
  assign UpdateEn10_out1 = Sel10_out1 & accumulate;
  always @(posedge clk or posedge reset)
    begin : delayMatch60_process
      if (reset == 1'b1) begin
        delayMatch60_reg <= {27{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch60_reg[0] <= UpdateEn10_out1;
          delayMatch60_reg[32'sd26:32'sd1] <= delayMatch60_reg[32'sd25:32'sd0];
        end
      end
    end

  assign UpdateEn10_out1_1 = delayMatch60_reg[26];

  assign stateControl_45 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch156_process
      if (reset == 1'b1) begin
        delayMatch156_reg <= {67{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch156_reg[0] <= stateControl_45;
          delayMatch156_reg[32'sd66:32'sd1] <= delayMatch156_reg[32'sd65:32'sd0];
        end
      end
    end

  assign stateControl_46 = delayMatch156_reg[66];

  // mul #1
  nfp_mul_single u_nfp_mul_comp_20 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(beatSum),  // single
                                    .nfp_in2(AccumulateSingle_out1_2),  // single
                                    .nfp_out(Gate10_out_1)  // single
                                    );
  assign SelSingle10_out1 = 32'h00000000;

  assign SelSingle10_out1_1 = 32'h3f800000;

  assign SelSingle10_out1_2 = (Sel10_out1 == 1'b0 ? SelSingle10_out1 :
              SelSingle10_out1_1);

  always @(posedge clk or posedge reset)
    begin : delayMatch106_process
      if (reset == 1'b1) begin
        for(delayMatch106_t_1 = 32'sd0; delayMatch106_t_1 <= 32'sd7; delayMatch106_t_1 = delayMatch106_t_1 + 32'sd1) begin
          delayMatch106_reg[delayMatch106_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch106_t_0_1 = 32'sd0; delayMatch106_t_0_1 <= 32'sd7; delayMatch106_t_0_1 = delayMatch106_t_0_1 + 32'sd1) begin
            delayMatch106_reg[delayMatch106_t_0_1] <= delayMatch106_reg_next[delayMatch106_t_0_1];
          end
        end
      end
    end

  always @* begin
    SelSingle10_out1_3 = delayMatch106_reg[7];
    delayMatch106_reg_next[0] = SelSingle10_out1_2;

    for(delayMatch106_t_0_0 = 32'sd0; delayMatch106_t_0_0 <= 32'sd6; delayMatch106_t_0_0 = delayMatch106_t_0_0 + 32'sd1) begin
      delayMatch106_reg_next[delayMatch106_t_0_0 + 32'sd1] = delayMatch106_reg[delayMatch106_t_0_0];
    end

  end

  // mul #2
  nfp_mul_single u_nfp_mul_comp_21 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Gate10_out_1),  // single
                                    .nfp_in2(SelSingle10_out1_3),  // single
                                    .nfp_out(Gate10_out1)  // single
                                    );
  always @(posedge clk or posedge reset)
    begin : out0_bypass21_process
      if (reset == 1'b1) begin
        FeedbackDelay10_out1_last_value <= 32'h00000000;
      end
      else begin
        if (enb) begin
          FeedbackDelay10_out1_last_value <= FeedbackDelay10_out1;
        end
      end
    end

  assign FeedbackDelay10_out1 = (stateControl_46 == 1'b0 ? FeedbackDelay10_out1_last_value :
              BankState10_out1);

  nfp_add_single u_nfp_add_comp_18 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(FeedbackDelay10_out1),  // single
                                    .nfp_in2(Gate10_out1),  // single
                                    .nfp_out(AccumulateAdd10_out1)  // single
                                    );
  assign HoldOrAcc10_out1 = (UpdateEn10_out1_1 == 1'b0 ? BankState10_out1_1 :
              AccumulateAdd10_out1);
  assign BankState10_out1_2 = (ClearBool_out1 == 1'b0 ? HoldOrAcc10_out1 :
              ZeroSingle_out1_1);
  assign BankState10_out1 = (stateControl_44 == 1'b0 ? BankState10_out1_1 :
              BankState10_out1_2);

  always @(posedge clk or posedge reset)
    begin : reduced_12_process
      if (reset == 1'b1) begin
        BankState10_out1_1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          BankState10_out1_1 <= BankState10_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : reduced_13_process
      if (reset == 1'b1) begin
        for(reduced_t_1_1 = 32'sd0; reduced_t_1_1 <= 32'sd9; reduced_t_1_1 = reduced_t_1_1 + 32'sd1) begin
          reduced_reg_2[reduced_t_1_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(reduced_t_0_1_1 = 32'sd0; reduced_t_0_1_1 <= 32'sd9; reduced_t_0_1_1 = reduced_t_0_1_1 + 32'sd1) begin
            reduced_reg_2[reduced_t_0_1_1] <= reduced_reg_next_1[reduced_t_0_1_1];
          end
        end
      end
    end

  always @* begin
    BankState10_out1_3 = reduced_reg_2[9];
    reduced_reg_next_1[0] = BankState10_out1_1;

    for(reduced_t_0_0_1 = 32'sd0; reduced_t_0_0_1 <= 32'sd8; reduced_t_0_0_1 = reduced_t_0_0_1 + 32'sd1) begin
      reduced_reg_next_1[reduced_t_0_0_1 + 32'sd1] = reduced_reg_2[reduced_t_0_0_1];
    end

  end

  nfp_add_single u_nfp_add_comp_19 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Sum89_out1),  // single
                                    .nfp_in2(BankState10_out1_3),  // single
                                    .nfp_out(Sum8910_out1)  // single
                                    );
  always @(posedge clk or posedge reset)
    begin : delayMatch133_process
      if (reset == 1'b1) begin
        for(delayMatch133_t_1 = 32'sd0; delayMatch133_t_1 <= 32'sd10; delayMatch133_t_1 = delayMatch133_t_1 + 32'sd1) begin
          delayMatch133_reg[delayMatch133_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch133_t_0_1 = 32'sd0; delayMatch133_t_0_1 <= 32'sd10; delayMatch133_t_0_1 = delayMatch133_t_0_1 + 32'sd1) begin
            delayMatch133_reg[delayMatch133_t_0_1] <= delayMatch133_reg_next[delayMatch133_t_0_1];
          end
        end
      end
    end

  always @* begin
    Sum8910_out1_1 = delayMatch133_reg[10];
    delayMatch133_reg_next[0] = Sum8910_out1;

    for(delayMatch133_t_0_0 = 32'sd0; delayMatch133_t_0_0 <= 32'sd9; delayMatch133_t_0_0 = delayMatch133_t_0_0 + 32'sd1) begin
      delayMatch133_reg_next[delayMatch133_t_0_0 + 32'sd1] = delayMatch133_reg[delayMatch133_t_0_0];
    end

  end

  nfp_add_single u_nfp_add_comp_20 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(Sum01234567_out1),  // single
                                    .nfp_in2(Sum8910_out1_1),  // single
                                    .nfp_out(SumAll_out1)  // single
                                    );
  assign currentSum = SumAll_out1;

endmodule  // BeatAccumulator

