// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/BeatReduce.sv
// Created: 2026-03-20 10:42:02
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: BeatReduce
// Source Path: rmsNormalization/DUTPacked/CoreDUT/BeatReduce
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BeatReduce
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] squaredBeat[0:7]  /* single [8] */,
             input logic squaredBeatValid,
             output logic [31:0] beatSum  /* single */,
             output logic beatSumValid);


  logic [31:0] Add01_out1;  /* ufix32 */
  logic [31:0] Add23_out1;  /* ufix32 */
  logic [31:0] Add0123_out1;  /* ufix32 */
  logic [31:0] Add45_out1;  /* ufix32 */
  logic [31:0] Add67_out1;  /* ufix32 */
  logic [31:0] Add4567_out1;  /* ufix32 */
  logic [31:0] AddAll_out1;  /* ufix32 */
  logic [32:0] delayMatch_reg;  /* ufix1 [33] */
  logic squaredBeatValid_1;


  nfp_add_single u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(squaredBeat[0]),  /* single */
                                 .nfp_in2(squaredBeat[1]),  /* single */
                                 .nfp_out(Add01_out1)  /* single */
                                 );

  nfp_add_single u_nfp_add_comp_1 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(squaredBeat[2]),  /* single */
                                   .nfp_in2(squaredBeat[3]),  /* single */
                                   .nfp_out(Add23_out1)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_2 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Add01_out1),  /* single */
                                   .nfp_in2(Add23_out1),  /* single */
                                   .nfp_out(Add0123_out1)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_3 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(squaredBeat[4]),  /* single */
                                   .nfp_in2(squaredBeat[5]),  /* single */
                                   .nfp_out(Add45_out1)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_4 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(squaredBeat[6]),  /* single */
                                   .nfp_in2(squaredBeat[7]),  /* single */
                                   .nfp_out(Add67_out1)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_5 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Add45_out1),  /* single */
                                   .nfp_in2(Add67_out1),  /* single */
                                   .nfp_out(Add4567_out1)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_6 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(Add0123_out1),  /* single */
                                   .nfp_in2(Add4567_out1),  /* single */
                                   .nfp_out(AddAll_out1)  /* single */
                                   );

  assign beatSum = AddAll_out1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= '{33{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= squaredBeatValid;
          delayMatch_reg[32'sd32:32'sd1] <= delayMatch_reg[32'sd31:32'sd0];
        end
      end
    end

  assign squaredBeatValid_1 = delayMatch_reg[32];

  assign beatSumValid = squaredBeatValid_1;

endmodule  // BeatReduce

