// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/Controller.sv
// Created: 2026-03-20 10:42:02
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Controller
// Source Path: rmsNormalization/DUTPacked/CoreDUT/Controller
// Hierarchy Level: 2
// Model version: 1.1
// 
// #codegen
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Controller
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic start,
             input logic [31:0] cfgGammaBeat[0:7]  /* single [8] */,
             input logic cfgGammaValid,
             input logic ddrDataValid,
             input logic invRmsAccepted,
             output logic [31:0] gBeat[0:7]  /* single [8] */,
             output logic gBeatValid,
             output logic captureInvRms,
             output logic [15:0] sramWriteAddr  /* uint16 */,
             output logic sramWriteBank,
             output logic sramWriteValid,
             output logic [15:0] sramReadAddr  /* uint16 */,
             output logic sramReadBank,
             output logic sramReadValid,
             output logic [15:0] ddrReadAddr  /* uint16 */,
             output logic ddrReadEn,
             output logic done,
             output logic busy);


  logic [15:0] const_expression;  /* uint16 */
  logic out0;
  logic out0_1;
  logic [15:0] receiveBeatIndex;  /* uint16 */
  logic out0_2;
  logic out0_3;
  logic [15:0] gammaWriteBeat;  /* uint16 */
  logic [15:0] gammaWriteBeat_1;  /* uint16 */
  logic [16:0] adder_add_temp;  /* ufix17 */
  logic [16:0] adder_1;  /* ufix17 */
  logic [16:0] adder_2;  /* ufix17 */
  logic [15:0] gammaWriteBeat_2;  /* uint16 */
  logic out0_4;
  logic [15:0] gammaWriteBeat_3;  /* uint16 */
  logic [15:0] gammaWriteBeat_4;  /* uint16 */
  logic gammaLoaded;
  logic gammaLoaded_1;
  logic gammaLoaded_2;
  logic gammaLoaded_3;
  logic out0_5;
  logic readyTokenValid;
  logic readyTokenValid_1;
  logic bank0Occupied;
  logic bank1Occupied;
  logic bank1Occupied_1;
  logic freeBank;
  logic freeBank_1;
  logic loadBank;
  logic bank0Occupied_1;
  logic canStartLoad;
  logic canStartLoad_1;
  logic loadActive;
  logic [7:0] const_expression_1;  /* uint8 */
  logic [7:0] nextLoadTokenIndex;  /* uint8 */
  logic [7:0] nextLoadTokenIndex_1;  /* uint8 */
  logic loadActive_1;
  logic pendingInvRms;
  logic pendingInvRms_1;
  logic [7:0] loadTokenIndex;  /* uint8 */
  logic [15:0] outputBeatIndex;  /* uint16 */
  logic outputActive;
  logic outputActive_1;
  logic [7:0] state;  /* uint8 */
  logic [7:0] state_1;  /* uint8 */
  logic [7:0] state_2;  /* uint8 */
  logic [7:0] state_3;  /* uint8 */
  logic out0_6;
  logic [7:0] state_4;  /* uint8 */
  logic out0_7;
  logic [7:0] state_5;  /* uint8 */
  logic outputActive_2;
  logic outputActive_3;
  logic outputActive_4;
  logic [15:0] outputBeatIndex_1;  /* uint16 */
  logic [15:0] outputBeatIndex_2;  /* uint16 */
  logic [7:0] pendingTokenIndex;  /* uint8 */
  logic [7:0] loadTokenIndex_1;  /* uint8 */
  logic canStartLoad_2;
  logic [7:0] loadTokenIndex_2;  /* uint8 */
  logic [7:0] loadTokenIndex_3;  /* uint8 */
  logic out0_8;
  logic [7:0] loadTokenIndex_4;  /* uint8 */
  logic out0_9;
  logic [7:0] loadTokenIndex_5;  /* uint8 */
  logic out0_10;
  logic [7:0] readyTokenIndex;  /* uint8 */
  logic [7:0] pendingTokenIndex_1;  /* uint8 */
  logic [7:0] pendingTokenIndex_2;  /* uint8 */
  logic loadActive_2;
  logic [7:0] pendingTokenIndex_3;  /* uint8 */
  logic [7:0] pendingTokenIndex_4;  /* uint8 */
  logic [7:0] outputTokenIndex;  /* uint8 */
  logic [7:0] readyTokenIndex_1;  /* uint8 */
  logic [7:0] readyTokenIndex_2;  /* uint8 */
  logic pendingInvRms_2;
  logic pendingInvRms_3;
  logic pendingInvRms_4;
  logic pendingInvRms_5;
  logic pendingInvRms_6;
  logic pendingInvRms_7;
  logic pendingInvRms_8;
  logic pendingInvRms_9;
  logic out0_11;
  logic loadActive_3;
  logic loadActive_4;
  logic loadActive_5;
  logic [7:0] nextLoadTokenIndex_2;  /* uint8 */
  logic [7:0] nextLoadTokenIndex_3;  /* uint8 */
  logic [7:0] nextLoadTokenIndex_4;  /* uint8 */
  logic [7:0] nextLoadTokenIndex_5;  /* uint8 */
  logic [8:0] adder_add_temp_1;  /* ufix9 */
  logic [8:0] adder_4;  /* ufix9 */
  logic [8:0] adder_5;  /* ufix9 */
  logic [7:0] nextLoadTokenIndex_6;  /* uint8 */
  logic [7:0] nextLoadTokenIndex_7;  /* uint8 */
  logic [7:0] nextLoadTokenIndex_8;  /* uint8 */
  logic [7:0] nextLoadTokenIndex_9;  /* uint8 */
  logic outputActive_5;
  logic out0_12;
  logic pendingInvRms_10;
  logic out0_13;
  logic loadActive_6;
  logic loadActive_7;
  logic loadActive_8;
  logic [15:0] sramWriteAddr_1;  /* uint16 */
  logic [15:0] receiveBeatIndex_1;  /* uint16 */
  logic out0_14;
  logic out0_15;
  logic outputBank;
  logic bank0Occupied_2;
  logic bank0Occupied_3;
  logic pendingBank;
  logic bank0Occupied_4;
  logic bank0Occupied_5;
  logic pendingBank_1;
  logic loadBank_1;
  logic bank1Occupied_2;
  logic bank1Occupied_3;
  logic bank1Occupied_4;
  logic bank1Occupied_5;
  logic sramReadBank_1;
  logic bank1Occupied_6;
  logic outputActive_6;
  logic readyTokenValid_2;
  logic bank1Occupied_7;
  logic out0_16;
  logic out0_17;
  logic loadBank_2;
  logic loadBank_3;
  logic loadBank_4;
  logic loadBank_5;
  logic readyBank;
  logic pendingBank_2;
  logic pendingBank_3;
  logic pendingBank_4;
  logic readyBank_1;
  logic readyBank_2;
  logic outputBank_1;
  logic outputBank_2;
  logic out0_18;
  logic bank0Occupied_6;
  logic readyTokenValid_3;
  logic readyTokenValid_4;
  logic readyTokenValid_5;
  logic readyTokenValid_6;
  logic readyTokenValid_7;
  logic readyTokenValid_8;
  logic readyTokenValid_9;
  logic bank0Occupied_7;
  logic [15:0] receiveBeatIndex_2;  /* uint16 */
  logic [15:0] receiveBeatIndex_3;  /* uint16 */
  logic [15:0] receiveBeatIndex_4;  /* uint16 */
  logic [15:0] receiveBeatIndex_5;  /* uint16 */
  logic [15:0] receiveBeatIndex_6;  /* uint16 */
  logic [16:0] adder_add_temp_2;  /* ufix17 */
  logic [16:0] adder_7;  /* ufix17 */
  logic [16:0] adder_8;  /* ufix17 */
  logic [15:0] receiveBeatIndex_7;  /* uint16 */
  logic [15:0] receiveBeatIndex_8;  /* uint16 */
  logic [15:0] receiveBeatIndex_9;  /* uint16 */
  logic [15:0] receiveBeatIndex_10;  /* uint16 */
  logic [15:0] receiveBeatIndex_11;  /* uint16 */
  logic loadActive_9;
  logic loadActive_10;
  logic out0_19;
  logic [7:0] state_6;  /* uint8 */
  logic out0_20;
  logic out0_21;
  logic out0_22;
  logic loadActive_11;
  logic loadActive_12;
  logic pendingInvRms_11;
  logic [7:0] outputTokenIndex_1;  /* uint8 */
  logic [7:0] outputTokenIndex_2;  /* uint8 */
  logic [7:0] outputTokenIndex_3;  /* uint8 */
  logic [15:0] outputBeatIndex_3;  /* uint16 */
  logic [15:0] sramReadAddr_1;  /* uint16 */
  logic [16:0] adder_add_temp_3;  /* ufix17 */
  logic [16:0] adder_10;  /* ufix17 */
  logic [16:0] adder_11;  /* ufix17 */
  logic [15:0] outputBeatIndex_4;  /* uint16 */
  logic [15:0] outputBeatIndex_5;  /* uint16 */
  logic [15:0] outputBeatIndex_6;  /* uint16 */
  logic [15:0] outputBeatIndex_7;  /* uint16 */
  logic outputActive_7;
  logic outputActive_8;
  logic out0_23;
  logic [7:0] state_7;  /* uint8 */
  logic [31:0] gBeat_1 [0:7];  /* ufix32 [8] */
  logic [31:0] beat [0:7];  /* ufix32 [8] */
  logic [15:0] baseIndex;  /* uint16 */
  logic [15:0] laneIndex;  /* uint16 */
  logic [16:0] adder_add_temp_4;  /* ufix17 */
  logic [16:0] adder_13;  /* ufix17 */
  logic [16:0] adder_14;  /* ufix17 */
  logic [15:0] out0_24;  /* uint16 */
  logic [15:0] const_expression_2;  /* uint16 */
  logic [16:0] adder_add_temp_5;  /* ufix17 */
  logic [16:0] adder_16;  /* ufix17 */
  logic [16:0] adder_17;  /* ufix17 */
  logic [15:0] out0_25;  /* uint16 */
  logic [31:0] out0_26;  /* ufix32 */
  logic [15:0] baseIndex_1;  /* uint16 */
  logic [15:0] laneIndex_1;  /* uint16 */
  logic [16:0] adder_add_temp_6;  /* ufix17 */
  logic [16:0] adder_19;  /* ufix17 */
  logic [16:0] adder_20;  /* ufix17 */
  logic [15:0] out0_27;  /* uint16 */
  logic [15:0] const_expression_3;  /* uint16 */
  logic [16:0] adder_add_temp_7;  /* ufix17 */
  logic [16:0] adder_22;  /* ufix17 */
  logic [16:0] adder_23;  /* ufix17 */
  logic [15:0] out0_28;  /* uint16 */
  logic [31:0] out0_29;  /* ufix32 */
  logic [15:0] laneIndex_2;  /* uint16 */
  logic [16:0] adder_add_temp_8;  /* ufix17 */
  logic [16:0] adder_25;  /* ufix17 */
  logic [16:0] adder_26;  /* ufix17 */
  logic [15:0] out0_30;  /* uint16 */
  logic [16:0] adder_add_temp_9;  /* ufix17 */
  logic [16:0] adder_28;  /* ufix17 */
  logic [16:0] adder_29;  /* ufix17 */
  logic [15:0] out0_31;  /* uint16 */
  logic [31:0] out0_32;  /* ufix32 */
  logic [15:0] laneIndex_3;  /* uint16 */
  logic [16:0] adder_add_temp_10;  /* ufix17 */
  logic [16:0] adder_31;  /* ufix17 */
  logic [16:0] adder_32;  /* ufix17 */
  logic [15:0] out0_33;  /* uint16 */
  logic [16:0] adder_add_temp_11;  /* ufix17 */
  logic [16:0] adder_34;  /* ufix17 */
  logic [16:0] adder_35;  /* ufix17 */
  logic [15:0] out0_34;  /* uint16 */
  logic [31:0] out0_35;  /* ufix32 */
  logic [15:0] laneIndex_4;  /* uint16 */
  logic [16:0] adder_add_temp_12;  /* ufix17 */
  logic [16:0] adder_37;  /* ufix17 */
  logic [16:0] adder_38;  /* ufix17 */
  logic [15:0] out0_36;  /* uint16 */
  logic [16:0] adder_add_temp_13;  /* ufix17 */
  logic [16:0] adder_40;  /* ufix17 */
  logic [16:0] adder_41;  /* ufix17 */
  logic [15:0] out0_37;  /* uint16 */
  logic [31:0] out0_38;  /* ufix32 */
  logic [15:0] laneIndex_5;  /* uint16 */
  logic [16:0] adder_add_temp_14;  /* ufix17 */
  logic [16:0] adder_43;  /* ufix17 */
  logic [16:0] adder_44;  /* ufix17 */
  logic [15:0] out0_39;  /* uint16 */
  logic [16:0] adder_add_temp_15;  /* ufix17 */
  logic [16:0] adder_46;  /* ufix17 */
  logic [16:0] adder_47;  /* ufix17 */
  logic [15:0] out0_40;  /* uint16 */
  logic [31:0] out0_41;  /* ufix32 */
  logic [15:0] laneIndex_6;  /* uint16 */
  logic [16:0] adder_add_temp_16;  /* ufix17 */
  logic [16:0] adder_49;  /* ufix17 */
  logic [16:0] adder_50;  /* ufix17 */
  logic [15:0] out0_42;  /* uint16 */
  logic [16:0] adder_add_temp_17;  /* ufix17 */
  logic [16:0] adder_52;  /* ufix17 */
  logic [16:0] adder_53;  /* ufix17 */
  logic [15:0] out0_43;  /* uint16 */
  logic [31:0] out0_44;  /* ufix32 */
  logic [15:0] laneIndex_7;  /* uint16 */
  logic [16:0] adder_add_temp_18;  /* ufix17 */
  logic [16:0] adder_55;  /* ufix17 */
  logic [16:0] adder_56;  /* ufix17 */
  logic [15:0] out0_45;  /* uint16 */
  logic [16:0] adder_add_temp_19;  /* ufix17 */
  logic [16:0] adder_58;  /* ufix17 */
  logic [16:0] adder_59;  /* ufix17 */
  logic [15:0] out0_46;  /* uint16 */
  logic [31:0] out0_47;  /* ufix32 */
  logic [15:0] laneIndex_8;  /* uint16 */
  logic [16:0] adder_add_temp_20;  /* ufix17 */
  logic [16:0] adder_61;  /* ufix17 */
  logic [16:0] adder_62;  /* ufix17 */
  logic [15:0] out0_48;  /* uint16 */
  logic [16:0] adder_add_temp_21;  /* ufix17 */
  logic [16:0] adder_64;  /* ufix17 */
  logic [16:0] adder_65;  /* ufix17 */
  logic [15:0] out0_49;  /* uint16 */
  logic [31:0] gammaMem [0:1535];  /* ufix32 [1536] */
  logic [31:0] mem [0:1535];  /* ufix32 [1536] */
  logic [31:0] mem_1 [0:1535];  /* ufix32 [1536] */
  logic [31:0] mem_2 [0:1535];  /* ufix32 [1536] */
  logic [31:0] mem_3 [0:1535];  /* ufix32 [1536] */
  logic [31:0] mem_4 [0:1535];  /* ufix32 [1536] */
  logic [31:0] mem_5 [0:1535];  /* ufix32 [1536] */
  logic [31:0] mem_6 [0:1535];  /* ufix32 [1536] */
  logic [31:0] gammaMem_1 [0:1535];  /* ufix32 [1536] */
  logic [31:0] gammaMem_2 [0:1535];  /* ufix32 [1536] */
  logic signed [31:0] Selector_idx;  /* int32 */
  logic [31:0] out0_50;  /* ufix32 */
  logic [31:0] beat_1 [0:7];  /* ufix32 [8] */
  logic [15:0] laneIndex_9;  /* uint16 */
  logic [16:0] adder_add_temp_22;  /* ufix17 */
  logic [16:0] adder_67;  /* ufix17 */
  logic [16:0] adder_68;  /* ufix17 */
  logic [15:0] out0_51;  /* uint16 */
  logic [16:0] adder_add_temp_23;  /* ufix17 */
  logic [16:0] adder_70;  /* ufix17 */
  logic [16:0] adder_71;  /* ufix17 */
  logic [15:0] out0_52;  /* uint16 */
  logic signed [31:0] Selector_idx_1;  /* int32 */
  logic [31:0] out0_53;  /* ufix32 */
  logic [31:0] beat_2 [0:7];  /* ufix32 [8] */
  logic [15:0] laneIndex_10;  /* uint16 */
  logic [16:0] adder_add_temp_24;  /* ufix17 */
  logic [16:0] adder_73;  /* ufix17 */
  logic [16:0] adder_74;  /* ufix17 */
  logic [15:0] out0_54;  /* uint16 */
  logic [16:0] adder_add_temp_25;  /* ufix17 */
  logic [16:0] adder_76;  /* ufix17 */
  logic [16:0] adder_77;  /* ufix17 */
  logic [15:0] out0_55;  /* uint16 */
  logic signed [31:0] Selector_idx_2;  /* int32 */
  logic [31:0] out0_56;  /* ufix32 */
  logic [31:0] beat_3 [0:7];  /* ufix32 [8] */
  logic [15:0] laneIndex_11;  /* uint16 */
  logic [16:0] adder_add_temp_26;  /* ufix17 */
  logic [16:0] adder_79;  /* ufix17 */
  logic [16:0] adder_80;  /* ufix17 */
  logic [15:0] out0_57;  /* uint16 */
  logic [16:0] adder_add_temp_27;  /* ufix17 */
  logic [16:0] adder_82;  /* ufix17 */
  logic [16:0] adder_83;  /* ufix17 */
  logic [15:0] out0_58;  /* uint16 */
  logic signed [31:0] Selector_idx_3;  /* int32 */
  logic [31:0] out0_59;  /* ufix32 */
  logic [31:0] beat_4 [0:7];  /* ufix32 [8] */
  logic [15:0] laneIndex_12;  /* uint16 */
  logic [16:0] adder_add_temp_28;  /* ufix17 */
  logic [16:0] adder_85;  /* ufix17 */
  logic [16:0] adder_86;  /* ufix17 */
  logic [15:0] out0_60;  /* uint16 */
  logic [16:0] adder_add_temp_29;  /* ufix17 */
  logic [16:0] adder_88;  /* ufix17 */
  logic [16:0] adder_89;  /* ufix17 */
  logic [15:0] out0_61;  /* uint16 */
  logic signed [31:0] Selector_idx_4;  /* int32 */
  logic [31:0] out0_62;  /* ufix32 */
  logic [31:0] beat_5 [0:7];  /* ufix32 [8] */
  logic [15:0] laneIndex_13;  /* uint16 */
  logic [16:0] adder_add_temp_30;  /* ufix17 */
  logic [16:0] adder_91;  /* ufix17 */
  logic [16:0] adder_92;  /* ufix17 */
  logic [15:0] out0_63;  /* uint16 */
  logic [16:0] adder_add_temp_31;  /* ufix17 */
  logic [16:0] adder_94;  /* ufix17 */
  logic [16:0] adder_95;  /* ufix17 */
  logic [15:0] out0_64;  /* uint16 */
  logic signed [31:0] Selector_idx_5;  /* int32 */
  logic [31:0] out0_65;  /* ufix32 */
  logic [31:0] beat_6 [0:7];  /* ufix32 [8] */
  logic [15:0] laneIndex_14;  /* uint16 */
  logic [16:0] adder_add_temp_32;  /* ufix17 */
  logic [16:0] adder_97;  /* ufix17 */
  logic [16:0] adder_98;  /* ufix17 */
  logic [15:0] out0_66;  /* uint16 */
  logic [16:0] adder_add_temp_33;  /* ufix17 */
  logic [16:0] adder_100;  /* ufix17 */
  logic [16:0] adder_101;  /* ufix17 */
  logic [15:0] out0_67;  /* uint16 */
  logic signed [31:0] Selector_idx_6;  /* int32 */
  logic [31:0] out0_68;  /* ufix32 */
  logic [31:0] beat_7 [0:7];  /* ufix32 [8] */
  logic [15:0] laneIndex_15;  /* uint16 */
  logic [16:0] adder_add_temp_34;  /* ufix17 */
  logic [16:0] adder_103;  /* ufix17 */
  logic [16:0] adder_104;  /* ufix17 */
  logic [15:0] out0_69;  /* uint16 */
  logic [16:0] adder_add_temp_35;  /* ufix17 */
  logic [16:0] adder_106;  /* ufix17 */
  logic [16:0] adder_107;  /* ufix17 */
  logic [15:0] out0_70;  /* uint16 */
  logic signed [31:0] Selector_idx_7;  /* int32 */
  logic [31:0] out0_71;  /* ufix32 */
  logic [31:0] gBeat_2 [0:7];  /* ufix32 [8] */
  logic [31:0] gBeat_3 [0:7];  /* ufix32 [8] */
  logic gBeatValid_1;
  logic gBeatValid_2;
  logic gBeatValid_3;
  logic [7:0] sumFlushCount;  /* uint8 */
  logic [7:0] sumFlushCount_1;  /* uint8 */
  logic [7:0] sumFlushCount_2;  /* uint8 */
  logic [7:0] sumFlushCount_3;  /* uint8 */
  logic [7:0] sumFlushCount_4;  /* uint8 */
  logic [7:0] sumFlushCount_5;  /* uint8 */
  logic [7:0] sumFlushCount_6;  /* uint8 */
  logic [7:0] sumFlushCount_7;  /* uint8 */
  logic [7:0] sumFlushCount_8;  /* uint8 */
  logic [7:0] sumFlushCount_9;  /* uint8 */
  logic signed [8:0] subtract_sub_temp;  /* sfix9 */
  logic signed [8:0] subtract_1;  /* sfix9 */
  logic signed [8:0] subtract_2;  /* sfix9 */
  logic [7:0] sumFlushCount_10;  /* uint8 */
  logic out0_72;
  logic [7:0] sumFlushCount_11;  /* uint8 */
  logic [7:0] sumFlushCount_12;  /* uint8 */
  logic out0_73;
  logic captureInvRms_1;
  logic out0_74;
  logic captureInvRms_2;
  logic captureInvRms_3;
  logic captureInvRms_4;
  logic [15:0] sramWriteAddr_2;  /* uint16 */
  logic [15:0] sramWriteAddr_3;  /* uint16 */
  logic [15:0] sramWriteAddr_4;  /* uint16 */
  logic sramWriteBank_1;
  logic sramWriteBank_2;
  logic sramWriteBank_3;
  logic sramWriteValid_1;
  logic sramWriteValid_2;
  logic sramWriteValid_3;
  logic sramWriteValid_4;
  logic [15:0] sramReadAddr_2;  /* uint16 */
  logic [15:0] sramReadAddr_3;  /* uint16 */
  logic sramReadBank_2;
  logic sramReadBank_3;
  logic sramReadValid_1;
  logic sramReadValid_2;
  logic sramReadValid_3;
  logic [15:0] ddrReadAddr_1;  /* uint16 */
  logic [15:0] const_expression_4;  /* uint16 */
  logic [15:0] requestBeatIndex;  /* uint16 */
  logic [15:0] requestBeatIndex_1;  /* uint16 */
  logic [15:0] requestBeatIndex_2;  /* uint16 */
  logic [15:0] requestBeatIndex_3;  /* uint16 */
  logic [15:0] requestBeatIndex_4;  /* uint16 */
  logic [15:0] requestBeatIndex_5;  /* uint16 */
  logic [15:0] requestBeatIndex_6;  /* uint16 */
  logic [15:0] requestBeatIndex_7;  /* uint16 */
  logic [15:0] requestBeatIndex_8;  /* uint16 */
  logic [15:0] requestBeatIndex_9;  /* uint16 */
  logic [16:0] adder_add_temp_36;  /* ufix17 */
  logic [16:0] adder_109;  /* ufix17 */
  logic [16:0] adder_110;  /* ufix17 */
  logic [15:0] requestBeatIndex_10;  /* uint16 */
  logic out0_75;
  logic [15:0] requestBeatIndex_11;  /* uint16 */
  logic [15:0] requestBeatIndex_12;  /* uint16 */
  logic [15:0] requestBeatIndex_13;  /* uint16 */
  logic [15:0] ddrReadAddr_2;  /* uint16 */
  logic [15:0] out0_76;  /* uint16 */
  logic [31:0] gain_mul_temp;  /* ufix32 */
  logic [15:0] out0_77;  /* uint16 */
  logic [16:0] adder_add_temp_37;  /* ufix17 */
  logic [16:0] adder_112;  /* ufix17 */
  logic [16:0] adder_113;  /* ufix17 */
  logic [15:0] ddrReadAddr_3;  /* uint16 */
  logic [15:0] ddrReadAddr_4;  /* uint16 */
  logic [15:0] ddrReadAddr_5;  /* uint16 */
  logic ddrReadEn_1;
  logic ddrReadEn_2;
  logic ddrReadEn_3;
  logic ddrReadEn_4;
  logic ddrReadEn_5;
  logic done_1;
  logic done_2;
  logic done_3;
  logic done_4;
  logic done_5;
  logic busy_1;
  logic busy_2;
  logic busy_3;
  logic busy_4;
  logic busy_5;
  logic busy_6;
  logic busy_7;
  logic signed [31:0] Assignment_i;  /* int32 */
  logic signed [31:0] Assignment_add_temp;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_1;  /* int32 */
  logic signed [31:0] Assignment_add_temp_1;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_1 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_2;  /* int32 */
  logic signed [31:0] Assignment_add_temp_2;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_2 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_3;  /* int32 */
  logic signed [31:0] Assignment_add_temp_3;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_3 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_4;  /* int32 */
  logic signed [31:0] Assignment_add_temp_4;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_4 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_5;  /* int32 */
  logic signed [31:0] Assignment_add_temp_5;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_5 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_6;  /* int32 */
  logic signed [31:0] Assignment_add_temp_6;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_6 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_7;  /* int32 */
  logic signed [31:0] Assignment_add_temp_7;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_7 [0:1535];  /* ufix16 [1536] */


  assign const_expression = 16'b0000000000000001;

  assign out0 = invRmsAccepted != 1'b0;

  assign out0_1 = ddrDataValid != 1'b0;

  assign receiveBeatIndex = 16'b0000000000000000;

  assign out0_2 = start != 1'b0;

  assign out0_3 = cfgGammaValid != 1'b0;

  assign gammaWriteBeat = 16'b0000000000000000;

  assign adder_1 = {1'b0, gammaWriteBeat_1};
  assign adder_2 = {1'b0, const_expression};
  assign adder_add_temp = adder_1 + adder_2;
  assign gammaWriteBeat_2 = (adder_add_temp[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp[15:0]);

  assign gammaWriteBeat_3 = (out0_4 == 1'b0 ? gammaWriteBeat_2 :
              gammaWriteBeat);

  assign gammaWriteBeat_4 = (out0_3 == 1'b0 ? gammaWriteBeat_1 :
              gammaWriteBeat_3);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        gammaWriteBeat_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          gammaWriteBeat_1 <= gammaWriteBeat_4;
        end
      end
    end

  assign out0_4 = gammaWriteBeat_1 == 16'b0000000010111111;

  assign gammaLoaded = 1'b1;

  assign gammaLoaded_2 = (out0_4 == 1'b0 ? gammaLoaded_1 :
              gammaLoaded);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        gammaLoaded_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          gammaLoaded_1 <= gammaLoaded_3;
        end
      end
    end

  assign gammaLoaded_3 = (out0_3 == 1'b0 ? gammaLoaded_1 :
              gammaLoaded_2);

  assign out0_5 = out0_2 & gammaLoaded_3;

  assign readyTokenValid = 1'b0;

  assign readyTokenValid_1 = 1'b1;

  assign bank0Occupied = 1'b0;

  assign bank1Occupied = 1'b0;

  assign bank1Occupied_1 = 1'b1;

  assign freeBank = 1'b0;

  assign freeBank_1 = 1'b1;

  assign loadBank = 1'b0;

  assign bank0Occupied_1 = 1'b1;

  assign canStartLoad = 1'b0;

  assign canStartLoad_1 = 1'b1;

  assign loadActive = 1'b0;

  assign const_expression_1 = 8'b00000001;

  assign nextLoadTokenIndex = 8'b00000001;

  assign nextLoadTokenIndex_1 = 8'b00000000;

  assign loadActive_1 = 1'b1;

  assign pendingInvRms = 1'b0;

  assign pendingInvRms_1 = 1'b1;

  assign loadTokenIndex = 8'b00000000;

  assign outputBeatIndex = 16'b0000000000000000;

  assign outputActive = 1'b0;

  assign outputActive_1 = 1'b1;

  assign state = 8'b00000000;

  assign state_1 = 8'b00000001;

  assign state_3 = (out0_5 == 1'b0 ? state_2 :
              state_1);

  assign state_4 = (out0_6 == 1'b0 ? state_2 :
              state);

  assign state_5 = (out0_7 == 1'b0 ? state_2 :
              state_4);

  assign outputActive_3 = (out0_5 == 1'b0 ? outputActive_2 :
              outputActive);

  assign outputActive_4 = (out0_6 == 1'b0 ? outputActive :
              outputActive);

  assign outputBeatIndex_2 = (out0_5 == 1'b0 ? outputBeatIndex_1 :
              outputBeatIndex);

  assign loadTokenIndex_1 = (out0_5 == 1'b0 ? pendingTokenIndex :
              loadTokenIndex);

  assign loadTokenIndex_3 = (canStartLoad_2 == 1'b0 ? pendingTokenIndex :
              loadTokenIndex_2);

  assign loadTokenIndex_4 = (out0_8 == 1'b0 ? pendingTokenIndex :
              loadTokenIndex_3);

  assign loadTokenIndex_5 = (out0_9 == 1'b0 ? loadTokenIndex_4 :
              loadTokenIndex_1);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        pendingTokenIndex <= 8'b00000000;
      end
      else begin
        if (enb) begin
          pendingTokenIndex <= loadTokenIndex_5;
        end
      end
    end

  assign pendingTokenIndex_1 = (out0_10 == 1'b0 ? readyTokenIndex :
              pendingTokenIndex);

  assign pendingTokenIndex_2 = (out0_1 == 1'b0 ? readyTokenIndex :
              pendingTokenIndex_1);

  assign pendingTokenIndex_3 = (loadActive_2 == 1'b0 ? readyTokenIndex :
              pendingTokenIndex_2);

  assign pendingTokenIndex_4 = (out0_9 == 1'b0 ? pendingTokenIndex_3 :
              readyTokenIndex);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        readyTokenIndex <= 8'b00000000;
      end
      else begin
        if (enb) begin
          readyTokenIndex <= pendingTokenIndex_4;
        end
      end
    end

  assign readyTokenIndex_2 = (out0_9 == 1'b0 ? outputTokenIndex :
              readyTokenIndex_1);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        readyTokenIndex_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          readyTokenIndex_1 <= readyTokenIndex_2;
        end
      end
    end

  assign pendingInvRms_3 = (out0_5 == 1'b0 ? pendingInvRms_2 :
              pendingInvRms);

  assign pendingInvRms_5 = (out0_6 == 1'b0 ? pendingInvRms_4 :
              pendingInvRms);

  assign pendingInvRms_6 = (out0_7 == 1'b0 ? pendingInvRms_4 :
              pendingInvRms_5);

  assign pendingInvRms_8 = (out0_10 == 1'b0 ? pendingInvRms_7 :
              pendingInvRms_1);

  assign pendingInvRms_9 = (out0_1 == 1'b0 ? pendingInvRms_7 :
              pendingInvRms_8);

  assign pendingInvRms_7 = (out0_11 == 1'b0 ? pendingInvRms_2 :
              pendingInvRms);

  assign loadActive_3 = (out0_5 == 1'b0 ? loadActive_2 :
              loadActive_1);

  assign loadActive_5 = (canStartLoad_2 == 1'b0 ? loadActive_4 :
              loadActive_1);

  assign nextLoadTokenIndex_3 = (out0_6 == 1'b0 ? nextLoadTokenIndex_2 :
              nextLoadTokenIndex_1);

  assign nextLoadTokenIndex_4 = (out0_7 == 1'b0 ? nextLoadTokenIndex_2 :
              nextLoadTokenIndex_3);

  assign nextLoadTokenIndex_5 = (out0_5 == 1'b0 ? nextLoadTokenIndex_2 :
              nextLoadTokenIndex);

  assign adder_4 = {1'b0, loadTokenIndex_2};
  assign adder_5 = {1'b0, const_expression_1};
  assign adder_add_temp_1 = adder_4 + adder_5;
  assign nextLoadTokenIndex_6 = (adder_add_temp_1[8] != 1'b0 ? 8'b11111111 :
              adder_add_temp_1[7:0]);

  assign nextLoadTokenIndex_7 = (canStartLoad_2 == 1'b0 ? loadTokenIndex_2 :
              nextLoadTokenIndex_6);

  assign nextLoadTokenIndex_8 = (out0_8 == 1'b0 ? loadTokenIndex_2 :
              nextLoadTokenIndex_7);

  assign nextLoadTokenIndex_9 = (out0_9 == 1'b0 ? nextLoadTokenIndex_8 :
              nextLoadTokenIndex_5);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        nextLoadTokenIndex_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          nextLoadTokenIndex_2 <= nextLoadTokenIndex_9;
        end
      end
    end

  assign loadTokenIndex_2 = (outputActive_5 == 1'b0 ? nextLoadTokenIndex_2 :
              nextLoadTokenIndex_4);

  assign out0_12 = loadTokenIndex_2 < 8'b01000000;

  assign out0_13 =  ~ pendingInvRms_10;

  assign loadActive_7 = (out0_6 == 1'b0 ? loadActive_6 :
              loadActive);

  assign loadActive_8 = (out0_7 == 1'b0 ? loadActive_6 :
              loadActive_7);

  assign receiveBeatIndex_1 = (out0_5 == 1'b0 ? sramWriteAddr_1 :
              receiveBeatIndex);

  assign out0_15 = (out0_14 == 1'b0 ? canStartLoad :
              canStartLoad_1);

  assign bank0Occupied_3 = (outputBank == 1'b0 ? bank0Occupied_1 :
              bank0Occupied_2);

  assign bank0Occupied_5 = (pendingBank == 1'b0 ? bank0Occupied_1 :
              bank0Occupied_4);

  assign loadBank_1 = (out0_5 == 1'b0 ? pendingBank_1 :
              loadBank);

  assign bank1Occupied_3 = (outputBank == 1'b0 ? bank1Occupied_2 :
              bank1Occupied_1);

  assign bank1Occupied_5 = (pendingBank == 1'b0 ? bank1Occupied_4 :
              bank1Occupied_1);

  assign bank1Occupied_6 = (sramReadBank_1 == 1'b0 ? bank1Occupied :
              bank1Occupied_1);

  assign bank1Occupied_4 = (outputActive_6 == 1'b0 ? bank1Occupied :
              bank1Occupied_6);

  assign bank1Occupied_2 = (pendingInvRms_10 == 1'b0 ? bank1Occupied_4 :
              bank1Occupied_5);

  assign bank1Occupied_7 = (readyTokenValid_2 == 1'b0 ? bank1Occupied_2 :
              bank1Occupied_3);

  assign out0_14 =  ~ bank1Occupied_7;

  assign out0_16 = (out0_14 == 1'b0 ? freeBank :
              freeBank_1);

  assign loadBank_2 = (out0_17 == 1'b0 ? out0_16 :
              freeBank);

  assign loadBank_3 = (canStartLoad_2 == 1'b0 ? pendingBank_1 :
              loadBank_2);

  assign loadBank_4 = (out0_8 == 1'b0 ? pendingBank_1 :
              loadBank_3);

  assign loadBank_5 = (out0_9 == 1'b0 ? loadBank_4 :
              loadBank_1);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        pendingBank_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          pendingBank_1 <= loadBank_5;
        end
      end
    end

  assign pendingBank_2 = (out0_10 == 1'b0 ? readyBank :
              pendingBank_1);

  assign pendingBank_3 = (out0_1 == 1'b0 ? readyBank :
              pendingBank_2);

  assign pendingBank = (loadActive_2 == 1'b0 ? readyBank :
              pendingBank_3);

  assign pendingBank_4 = (out0_9 == 1'b0 ? pendingBank :
              readyBank);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        readyBank <= 1'b0;
      end
      else begin
        if (enb) begin
          readyBank <= pendingBank_4;
        end
      end
    end

  assign readyBank_2 = (out0_9 == 1'b0 ? outputBank :
              readyBank_1);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        readyBank_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          readyBank_1 <= readyBank_2;
        end
      end
    end

  assign outputBank = (out0_11 == 1'b0 ? readyBank_1 :
              readyBank);

  assign outputBank_2 = (out0_9 == 1'b0 ? sramReadBank_1 :
              outputBank_1);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        outputBank_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          outputBank_1 <= outputBank_2;
        end
      end
    end

  assign sramReadBank_1 = (out0_18 == 1'b0 ? outputBank_1 :
              outputBank);

  assign bank0Occupied_6 = (sramReadBank_1 == 1'b0 ? bank0Occupied_1 :
              bank0Occupied);

  assign bank0Occupied_4 = (outputActive_6 == 1'b0 ? bank0Occupied :
              bank0Occupied_6);

  assign bank0Occupied_2 = (pendingInvRms_10 == 1'b0 ? bank0Occupied_4 :
              bank0Occupied_5);

  assign readyTokenValid_4 = (out0_6 == 1'b0 ? readyTokenValid_3 :
              readyTokenValid);

  assign readyTokenValid_5 = (out0_7 == 1'b0 ? readyTokenValid_3 :
              readyTokenValid_4);

  assign readyTokenValid_7 = (out0_5 == 1'b0 ? readyTokenValid_6 :
              readyTokenValid);

  assign readyTokenValid_8 = (out0_9 == 1'b0 ? readyTokenValid_2 :
              readyTokenValid_7);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_10_process
      if (reset == 1'b1) begin
        readyTokenValid_6 <= 1'b0;
      end
      else begin
        if (enb) begin
          readyTokenValid_6 <= readyTokenValid_8;
        end
      end
    end

  assign readyTokenValid_9 = (out0_11 == 1'b0 ? readyTokenValid_6 :
              readyTokenValid_1);

  assign readyTokenValid_3 = (out0_18 == 1'b0 ? readyTokenValid_9 :
              readyTokenValid);

  assign readyTokenValid_2 = (outputActive_5 == 1'b0 ? readyTokenValid_3 :
              readyTokenValid_5);

  assign bank0Occupied_7 = (readyTokenValid_2 == 1'b0 ? bank0Occupied_2 :
              bank0Occupied_3);

  assign out0_17 =  ~ bank0Occupied_7;

  assign canStartLoad_2 = (out0_17 == 1'b0 ? out0_15 :
              canStartLoad_1);

  assign receiveBeatIndex_3 = (canStartLoad_2 == 1'b0 ? receiveBeatIndex_2 :
              receiveBeatIndex);

  assign receiveBeatIndex_5 = (out0_6 == 1'b0 ? receiveBeatIndex_4 :
              receiveBeatIndex);

  assign receiveBeatIndex_6 = (out0_7 == 1'b0 ? receiveBeatIndex_4 :
              receiveBeatIndex_5);

  assign adder_7 = {1'b0, sramWriteAddr_1};
  assign adder_8 = {1'b0, const_expression};
  assign adder_add_temp_2 = adder_7 + adder_8;
  assign receiveBeatIndex_7 = (adder_add_temp_2[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_2[15:0]);

  assign receiveBeatIndex_8 = (out0_10 == 1'b0 ? receiveBeatIndex_7 :
              receiveBeatIndex);

  assign receiveBeatIndex_9 = (out0_1 == 1'b0 ? sramWriteAddr_1 :
              receiveBeatIndex_8);

  assign receiveBeatIndex_4 = (loadActive_2 == 1'b0 ? sramWriteAddr_1 :
              receiveBeatIndex_9);

  assign receiveBeatIndex_2 = (outputActive_5 == 1'b0 ? receiveBeatIndex_4 :
              receiveBeatIndex_6);

  assign receiveBeatIndex_10 = (out0_8 == 1'b0 ? receiveBeatIndex_2 :
              receiveBeatIndex_3);

  assign receiveBeatIndex_11 = (out0_9 == 1'b0 ? receiveBeatIndex_10 :
              receiveBeatIndex_1);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_11_process
      if (reset == 1'b1) begin
        sramWriteAddr_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          sramWriteAddr_1 <= receiveBeatIndex_11;
        end
      end
    end

  assign out0_10 = sramWriteAddr_1 == 16'b0000000010111111;

  assign loadActive_9 = (out0_10 == 1'b0 ? loadActive_2 :
              loadActive);

  assign loadActive_10 = (out0_1 == 1'b0 ? loadActive_2 :
              loadActive_9);

  assign loadActive_6 = (loadActive_2 == 1'b0 ? loadActive_2 :
              loadActive_10);

  assign loadActive_4 = (outputActive_5 == 1'b0 ? loadActive_6 :
              loadActive_8);

  assign out0_19 =  ~ loadActive_4;

  assign out0_20 = state_6 != 8'b00000000;

  assign out0_21 = out0_20 & out0_19;

  assign out0_22 = out0_21 & out0_13;

  assign out0_8 = out0_22 & out0_12;

  assign loadActive_11 = (out0_8 == 1'b0 ? loadActive_4 :
              loadActive_5);

  assign loadActive_12 = (out0_9 == 1'b0 ? loadActive_11 :
              loadActive_3);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_12_process
      if (reset == 1'b1) begin
        loadActive_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          loadActive_2 <= loadActive_12;
        end
      end
    end

  assign pendingInvRms_4 = (loadActive_2 == 1'b0 ? pendingInvRms_7 :
              pendingInvRms_9);

  assign pendingInvRms_10 = (outputActive_5 == 1'b0 ? pendingInvRms_4 :
              pendingInvRms_6);

  assign pendingInvRms_11 = (out0_9 == 1'b0 ? pendingInvRms_10 :
              pendingInvRms_3);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_13_process
      if (reset == 1'b1) begin
        pendingInvRms_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          pendingInvRms_2 <= pendingInvRms_11;
        end
      end
    end

  assign out0_11 = out0 & pendingInvRms_2;

  assign outputTokenIndex = (out0_11 == 1'b0 ? readyTokenIndex_1 :
              readyTokenIndex);

  assign outputTokenIndex_3 = (out0_9 == 1'b0 ? outputTokenIndex_1 :
              outputTokenIndex_2);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_14_process
      if (reset == 1'b1) begin
        outputTokenIndex_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          outputTokenIndex_2 <= outputTokenIndex_3;
        end
      end
    end

  assign outputTokenIndex_1 = (out0_18 == 1'b0 ? outputTokenIndex_2 :
              outputTokenIndex);

  assign out0_6 = outputTokenIndex_1 == 8'b00111111;

  assign outputBeatIndex_3 = (out0_6 == 1'b0 ? outputBeatIndex :
              outputBeatIndex);

  assign adder_10 = {1'b0, sramReadAddr_1};
  assign adder_11 = {1'b0, const_expression};
  assign adder_add_temp_3 = adder_10 + adder_11;
  assign outputBeatIndex_4 = (adder_add_temp_3[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_3[15:0]);

  assign outputBeatIndex_5 = (out0_7 == 1'b0 ? outputBeatIndex_4 :
              outputBeatIndex_3);

  assign outputBeatIndex_6 = (outputActive_5 == 1'b0 ? sramReadAddr_1 :
              outputBeatIndex_5);

  assign outputBeatIndex_7 = (out0_9 == 1'b0 ? outputBeatIndex_6 :
              outputBeatIndex_2);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_15_process
      if (reset == 1'b1) begin
        outputBeatIndex_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          outputBeatIndex_1 <= outputBeatIndex_7;
        end
      end
    end

  assign sramReadAddr_1 = (out0_18 == 1'b0 ? outputBeatIndex_1 :
              outputBeatIndex);

  assign out0_7 = sramReadAddr_1 == 16'b0000000010111111;

  assign outputActive_7 = (out0_7 == 1'b0 ? outputActive_5 :
              outputActive_4);

  assign outputActive_6 = (outputActive_5 == 1'b0 ? outputActive_5 :
              outputActive_7);

  assign outputActive_8 = (out0_9 == 1'b0 ? outputActive_6 :
              outputActive_3);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_16_process
      if (reset == 1'b1) begin
        outputActive_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          outputActive_2 <= outputActive_8;
        end
      end
    end

  assign out0_23 =  ~ outputActive_2;

  assign out0_18 = out0_23 & readyTokenValid_9;

  assign outputActive_5 = (out0_18 == 1'b0 ? outputActive_2 :
              outputActive_1);

  assign state_6 = (outputActive_5 == 1'b0 ? state_2 :
              state_5);

  assign state_7 = (out0_9 == 1'b0 ? state_6 :
              state_3);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_17_process
      if (reset == 1'b1) begin
        state_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          state_2 <= state_7;
        end
      end
    end

  assign out0_9 = state_2 == 8'b00000000;

  assign gBeat_1 = '{8{32'h00000000}};

  assign beat = '{8{32'h00000000}};

  assign baseIndex = sramReadAddr_1 <<< 8'd3;

  assign laneIndex = 16'b0000000000000000;

  assign adder_13 = {1'b0, baseIndex};
  assign adder_14 = {1'b0, laneIndex};
  assign adder_add_temp_4 = adder_13 + adder_14;
  assign out0_24 = (adder_add_temp_4[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_4[15:0]);

  assign const_expression_2 = 16'b0000000000000001;

  assign adder_16 = {1'b0, out0_24};
  assign adder_17 = {1'b0, const_expression_2};
  assign adder_add_temp_5 = adder_16 + adder_17;
  assign out0_25 = (adder_add_temp_5[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_5[15:0]);

  assign out0_26 = cfgGammaBeat[0];

  assign baseIndex_1 = gammaWriteBeat_1 <<< 8'd3;

  assign laneIndex_1 = 16'b0000000000000000;

  assign adder_19 = {1'b0, baseIndex_1};
  assign adder_20 = {1'b0, laneIndex_1};
  assign adder_add_temp_6 = adder_19 + adder_20;
  assign out0_27 = (adder_add_temp_6[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_6[15:0]);

  assign const_expression_3 = 16'b0000000000000001;

  assign adder_22 = {1'b0, out0_27};
  assign adder_23 = {1'b0, const_expression_3};
  assign adder_add_temp_7 = adder_22 + adder_23;
  assign out0_28 = (adder_add_temp_7[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_7[15:0]);

  assign out0_29 = cfgGammaBeat[1];

  assign laneIndex_2 = 16'b0000000000000001;

  assign adder_25 = {1'b0, baseIndex_1};
  assign adder_26 = {1'b0, laneIndex_2};
  assign adder_add_temp_8 = adder_25 + adder_26;
  assign out0_30 = (adder_add_temp_8[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_8[15:0]);

  assign adder_28 = {1'b0, out0_30};
  assign adder_29 = {1'b0, const_expression_3};
  assign adder_add_temp_9 = adder_28 + adder_29;
  assign out0_31 = (adder_add_temp_9[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_9[15:0]);

  assign out0_32 = cfgGammaBeat[2];

  assign laneIndex_3 = 16'b0000000000000010;

  assign adder_31 = {1'b0, baseIndex_1};
  assign adder_32 = {1'b0, laneIndex_3};
  assign adder_add_temp_10 = adder_31 + adder_32;
  assign out0_33 = (adder_add_temp_10[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_10[15:0]);

  assign adder_34 = {1'b0, out0_33};
  assign adder_35 = {1'b0, const_expression_3};
  assign adder_add_temp_11 = adder_34 + adder_35;
  assign out0_34 = (adder_add_temp_11[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_11[15:0]);

  assign out0_35 = cfgGammaBeat[3];

  assign laneIndex_4 = 16'b0000000000000011;

  assign adder_37 = {1'b0, baseIndex_1};
  assign adder_38 = {1'b0, laneIndex_4};
  assign adder_add_temp_12 = adder_37 + adder_38;
  assign out0_36 = (adder_add_temp_12[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_12[15:0]);

  assign adder_40 = {1'b0, out0_36};
  assign adder_41 = {1'b0, const_expression_3};
  assign adder_add_temp_13 = adder_40 + adder_41;
  assign out0_37 = (adder_add_temp_13[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_13[15:0]);

  assign out0_38 = cfgGammaBeat[4];

  assign laneIndex_5 = 16'b0000000000000100;

  assign adder_43 = {1'b0, baseIndex_1};
  assign adder_44 = {1'b0, laneIndex_5};
  assign adder_add_temp_14 = adder_43 + adder_44;
  assign out0_39 = (adder_add_temp_14[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_14[15:0]);

  assign adder_46 = {1'b0, out0_39};
  assign adder_47 = {1'b0, const_expression_3};
  assign adder_add_temp_15 = adder_46 + adder_47;
  assign out0_40 = (adder_add_temp_15[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_15[15:0]);

  assign out0_41 = cfgGammaBeat[5];

  assign laneIndex_6 = 16'b0000000000000101;

  assign adder_49 = {1'b0, baseIndex_1};
  assign adder_50 = {1'b0, laneIndex_6};
  assign adder_add_temp_16 = adder_49 + adder_50;
  assign out0_42 = (adder_add_temp_16[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_16[15:0]);

  assign adder_52 = {1'b0, out0_42};
  assign adder_53 = {1'b0, const_expression_3};
  assign adder_add_temp_17 = adder_52 + adder_53;
  assign out0_43 = (adder_add_temp_17[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_17[15:0]);

  assign out0_44 = cfgGammaBeat[6];

  assign laneIndex_7 = 16'b0000000000000110;

  assign adder_55 = {1'b0, baseIndex_1};
  assign adder_56 = {1'b0, laneIndex_7};
  assign adder_add_temp_18 = adder_55 + adder_56;
  assign out0_45 = (adder_add_temp_18[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_18[15:0]);

  assign adder_58 = {1'b0, out0_45};
  assign adder_59 = {1'b0, const_expression_3};
  assign adder_add_temp_19 = adder_58 + adder_59;
  assign out0_46 = (adder_add_temp_19[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_19[15:0]);

  assign out0_47 = cfgGammaBeat[7];

  assign laneIndex_8 = 16'b0000000000000111;

  assign adder_61 = {1'b0, baseIndex_1};
  assign adder_62 = {1'b0, laneIndex_8};
  assign adder_add_temp_20 = adder_61 + adder_62;
  assign out0_48 = (adder_add_temp_20[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_20[15:0]);

  assign adder_64 = {1'b0, out0_48};
  assign adder_65 = {1'b0, const_expression_3};
  assign adder_add_temp_21 = adder_64 + adder_65;
  assign out0_49 = (adder_add_temp_21[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_21[15:0]);

  always_comb begin
    Assignment_add_temp = 32'sd0;

    for(Assignment_i = 32'sd0; Assignment_i <= 32'sd1535; Assignment_i = Assignment_i + 32'sd1) begin
      Assignment_add_temp = Assignment_i + 32'sd1;
      Assignment_t_0[Assignment_i] = Assignment_add_temp[15:0];
      if (out0_28 == Assignment_t_0[Assignment_i]) begin
        mem[Assignment_i] = out0_26;
      end
      else begin
        mem[Assignment_i] = gammaMem[Assignment_i];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_1 = 32'sd0;

    for(Assignment_i_1 = 32'sd0; Assignment_i_1 <= 32'sd1535; Assignment_i_1 = Assignment_i_1 + 32'sd1) begin
      Assignment_add_temp_1 = Assignment_i_1 + 32'sd1;
      Assignment_t_0_1[Assignment_i_1] = Assignment_add_temp_1[15:0];
      if (out0_31 == Assignment_t_0_1[Assignment_i_1]) begin
        mem_1[Assignment_i_1] = out0_29;
      end
      else begin
        mem_1[Assignment_i_1] = mem[Assignment_i_1];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_2 = 32'sd0;

    for(Assignment_i_2 = 32'sd0; Assignment_i_2 <= 32'sd1535; Assignment_i_2 = Assignment_i_2 + 32'sd1) begin
      Assignment_add_temp_2 = Assignment_i_2 + 32'sd1;
      Assignment_t_0_2[Assignment_i_2] = Assignment_add_temp_2[15:0];
      if (out0_34 == Assignment_t_0_2[Assignment_i_2]) begin
        mem_2[Assignment_i_2] = out0_32;
      end
      else begin
        mem_2[Assignment_i_2] = mem_1[Assignment_i_2];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_3 = 32'sd0;

    for(Assignment_i_3 = 32'sd0; Assignment_i_3 <= 32'sd1535; Assignment_i_3 = Assignment_i_3 + 32'sd1) begin
      Assignment_add_temp_3 = Assignment_i_3 + 32'sd1;
      Assignment_t_0_3[Assignment_i_3] = Assignment_add_temp_3[15:0];
      if (out0_37 == Assignment_t_0_3[Assignment_i_3]) begin
        mem_3[Assignment_i_3] = out0_35;
      end
      else begin
        mem_3[Assignment_i_3] = mem_2[Assignment_i_3];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_4 = 32'sd0;

    for(Assignment_i_4 = 32'sd0; Assignment_i_4 <= 32'sd1535; Assignment_i_4 = Assignment_i_4 + 32'sd1) begin
      Assignment_add_temp_4 = Assignment_i_4 + 32'sd1;
      Assignment_t_0_4[Assignment_i_4] = Assignment_add_temp_4[15:0];
      if (out0_40 == Assignment_t_0_4[Assignment_i_4]) begin
        mem_4[Assignment_i_4] = out0_38;
      end
      else begin
        mem_4[Assignment_i_4] = mem_3[Assignment_i_4];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_5 = 32'sd0;

    for(Assignment_i_5 = 32'sd0; Assignment_i_5 <= 32'sd1535; Assignment_i_5 = Assignment_i_5 + 32'sd1) begin
      Assignment_add_temp_5 = Assignment_i_5 + 32'sd1;
      Assignment_t_0_5[Assignment_i_5] = Assignment_add_temp_5[15:0];
      if (out0_43 == Assignment_t_0_5[Assignment_i_5]) begin
        mem_5[Assignment_i_5] = out0_41;
      end
      else begin
        mem_5[Assignment_i_5] = mem_4[Assignment_i_5];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_6 = 32'sd0;

    for(Assignment_i_6 = 32'sd0; Assignment_i_6 <= 32'sd1535; Assignment_i_6 = Assignment_i_6 + 32'sd1) begin
      Assignment_add_temp_6 = Assignment_i_6 + 32'sd1;
      Assignment_t_0_6[Assignment_i_6] = Assignment_add_temp_6[15:0];
      if (out0_46 == Assignment_t_0_6[Assignment_i_6]) begin
        mem_6[Assignment_i_6] = out0_44;
      end
      else begin
        mem_6[Assignment_i_6] = mem_5[Assignment_i_6];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_7 = 32'sd0;

    for(Assignment_i_7 = 32'sd0; Assignment_i_7 <= 32'sd1535; Assignment_i_7 = Assignment_i_7 + 32'sd1) begin
      Assignment_add_temp_7 = Assignment_i_7 + 32'sd1;
      Assignment_t_0_7[Assignment_i_7] = Assignment_add_temp_7[15:0];
      if (out0_49 == Assignment_t_0_7[Assignment_i_7]) begin
        gammaMem_1[Assignment_i_7] = out0_47;
      end
      else begin
        gammaMem_1[Assignment_i_7] = mem_6[Assignment_i_7];
      end
    end

  end

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_18_process
      if (reset == 1'b1) begin
        gammaMem <= '{1536{32'h00000000}};
      end
      else begin
        if (enb) begin
          gammaMem <= gammaMem_2;
        end
      end
    end

  assign gammaMem_2 = (out0_3 == 1'b0 ? gammaMem :
              gammaMem_1);

  assign Selector_idx = {16'b0, out0_25};
  assign out0_50 = ((Selector_idx >= 32'sd1) && (Selector_idx <= 32'sd1536) ? gammaMem_2[Selector_idx - 32'sd1] :
              gammaMem_2[1535]);

  assign beat_1[0] = out0_50;
  assign beat_1[1] = beat[1];
  assign beat_1[2] = beat[2];
  assign beat_1[3] = beat[3];
  assign beat_1[4] = beat[4];
  assign beat_1[5] = beat[5];
  assign beat_1[6] = beat[6];
  assign beat_1[7] = beat[7];

  assign laneIndex_9 = 16'b0000000000000001;

  assign adder_67 = {1'b0, baseIndex};
  assign adder_68 = {1'b0, laneIndex_9};
  assign adder_add_temp_22 = adder_67 + adder_68;
  assign out0_51 = (adder_add_temp_22[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_22[15:0]);

  assign adder_70 = {1'b0, out0_51};
  assign adder_71 = {1'b0, const_expression_2};
  assign adder_add_temp_23 = adder_70 + adder_71;
  assign out0_52 = (adder_add_temp_23[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_23[15:0]);

  assign Selector_idx_1 = {16'b0, out0_52};
  assign out0_53 = ((Selector_idx_1 >= 32'sd1) && (Selector_idx_1 <= 32'sd1536) ? gammaMem_2[Selector_idx_1 - 32'sd1] :
              gammaMem_2[1535]);

  assign beat_2[0] = beat_1[0];
  assign beat_2[1] = out0_53;
  assign beat_2[2] = beat_1[2];
  assign beat_2[3] = beat_1[3];
  assign beat_2[4] = beat_1[4];
  assign beat_2[5] = beat_1[5];
  assign beat_2[6] = beat_1[6];
  assign beat_2[7] = beat_1[7];

  assign laneIndex_10 = 16'b0000000000000010;

  assign adder_73 = {1'b0, baseIndex};
  assign adder_74 = {1'b0, laneIndex_10};
  assign adder_add_temp_24 = adder_73 + adder_74;
  assign out0_54 = (adder_add_temp_24[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_24[15:0]);

  assign adder_76 = {1'b0, out0_54};
  assign adder_77 = {1'b0, const_expression_2};
  assign adder_add_temp_25 = adder_76 + adder_77;
  assign out0_55 = (adder_add_temp_25[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_25[15:0]);

  assign Selector_idx_2 = {16'b0, out0_55};
  assign out0_56 = ((Selector_idx_2 >= 32'sd1) && (Selector_idx_2 <= 32'sd1536) ? gammaMem_2[Selector_idx_2 - 32'sd1] :
              gammaMem_2[1535]);

  assign beat_3[0] = beat_2[0];
  assign beat_3[1] = beat_2[1];
  assign beat_3[2] = out0_56;
  assign beat_3[3] = beat_2[3];
  assign beat_3[4] = beat_2[4];
  assign beat_3[5] = beat_2[5];
  assign beat_3[6] = beat_2[6];
  assign beat_3[7] = beat_2[7];

  assign laneIndex_11 = 16'b0000000000000011;

  assign adder_79 = {1'b0, baseIndex};
  assign adder_80 = {1'b0, laneIndex_11};
  assign adder_add_temp_26 = adder_79 + adder_80;
  assign out0_57 = (adder_add_temp_26[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_26[15:0]);

  assign adder_82 = {1'b0, out0_57};
  assign adder_83 = {1'b0, const_expression_2};
  assign adder_add_temp_27 = adder_82 + adder_83;
  assign out0_58 = (adder_add_temp_27[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_27[15:0]);

  assign Selector_idx_3 = {16'b0, out0_58};
  assign out0_59 = ((Selector_idx_3 >= 32'sd1) && (Selector_idx_3 <= 32'sd1536) ? gammaMem_2[Selector_idx_3 - 32'sd1] :
              gammaMem_2[1535]);

  assign beat_4[0] = beat_3[0];
  assign beat_4[1] = beat_3[1];
  assign beat_4[2] = beat_3[2];
  assign beat_4[3] = out0_59;
  assign beat_4[4] = beat_3[4];
  assign beat_4[5] = beat_3[5];
  assign beat_4[6] = beat_3[6];
  assign beat_4[7] = beat_3[7];

  assign laneIndex_12 = 16'b0000000000000100;

  assign adder_85 = {1'b0, baseIndex};
  assign adder_86 = {1'b0, laneIndex_12};
  assign adder_add_temp_28 = adder_85 + adder_86;
  assign out0_60 = (adder_add_temp_28[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_28[15:0]);

  assign adder_88 = {1'b0, out0_60};
  assign adder_89 = {1'b0, const_expression_2};
  assign adder_add_temp_29 = adder_88 + adder_89;
  assign out0_61 = (adder_add_temp_29[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_29[15:0]);

  assign Selector_idx_4 = {16'b0, out0_61};
  assign out0_62 = ((Selector_idx_4 >= 32'sd1) && (Selector_idx_4 <= 32'sd1536) ? gammaMem_2[Selector_idx_4 - 32'sd1] :
              gammaMem_2[1535]);

  assign beat_5[0] = beat_4[0];
  assign beat_5[1] = beat_4[1];
  assign beat_5[2] = beat_4[2];
  assign beat_5[3] = beat_4[3];
  assign beat_5[4] = out0_62;
  assign beat_5[5] = beat_4[5];
  assign beat_5[6] = beat_4[6];
  assign beat_5[7] = beat_4[7];

  assign laneIndex_13 = 16'b0000000000000101;

  assign adder_91 = {1'b0, baseIndex};
  assign adder_92 = {1'b0, laneIndex_13};
  assign adder_add_temp_30 = adder_91 + adder_92;
  assign out0_63 = (adder_add_temp_30[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_30[15:0]);

  assign adder_94 = {1'b0, out0_63};
  assign adder_95 = {1'b0, const_expression_2};
  assign adder_add_temp_31 = adder_94 + adder_95;
  assign out0_64 = (adder_add_temp_31[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_31[15:0]);

  assign Selector_idx_5 = {16'b0, out0_64};
  assign out0_65 = ((Selector_idx_5 >= 32'sd1) && (Selector_idx_5 <= 32'sd1536) ? gammaMem_2[Selector_idx_5 - 32'sd1] :
              gammaMem_2[1535]);

  assign beat_6[0] = beat_5[0];
  assign beat_6[1] = beat_5[1];
  assign beat_6[2] = beat_5[2];
  assign beat_6[3] = beat_5[3];
  assign beat_6[4] = beat_5[4];
  assign beat_6[5] = out0_65;
  assign beat_6[6] = beat_5[6];
  assign beat_6[7] = beat_5[7];

  assign laneIndex_14 = 16'b0000000000000110;

  assign adder_97 = {1'b0, baseIndex};
  assign adder_98 = {1'b0, laneIndex_14};
  assign adder_add_temp_32 = adder_97 + adder_98;
  assign out0_66 = (adder_add_temp_32[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_32[15:0]);

  assign adder_100 = {1'b0, out0_66};
  assign adder_101 = {1'b0, const_expression_2};
  assign adder_add_temp_33 = adder_100 + adder_101;
  assign out0_67 = (adder_add_temp_33[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_33[15:0]);

  assign Selector_idx_6 = {16'b0, out0_67};
  assign out0_68 = ((Selector_idx_6 >= 32'sd1) && (Selector_idx_6 <= 32'sd1536) ? gammaMem_2[Selector_idx_6 - 32'sd1] :
              gammaMem_2[1535]);

  assign beat_7[0] = beat_6[0];
  assign beat_7[1] = beat_6[1];
  assign beat_7[2] = beat_6[2];
  assign beat_7[3] = beat_6[3];
  assign beat_7[4] = beat_6[4];
  assign beat_7[5] = beat_6[5];
  assign beat_7[6] = out0_68;
  assign beat_7[7] = beat_6[7];

  assign laneIndex_15 = 16'b0000000000000111;

  assign adder_103 = {1'b0, baseIndex};
  assign adder_104 = {1'b0, laneIndex_15};
  assign adder_add_temp_34 = adder_103 + adder_104;
  assign out0_69 = (adder_add_temp_34[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_34[15:0]);

  assign adder_106 = {1'b0, out0_69};
  assign adder_107 = {1'b0, const_expression_2};
  assign adder_add_temp_35 = adder_106 + adder_107;
  assign out0_70 = (adder_add_temp_35[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_35[15:0]);

  assign Selector_idx_7 = {16'b0, out0_70};
  assign out0_71 = ((Selector_idx_7 >= 32'sd1) && (Selector_idx_7 <= 32'sd1536) ? gammaMem_2[Selector_idx_7 - 32'sd1] :
              gammaMem_2[1535]);

  assign gBeat_2[0] = beat_7[0];
  assign gBeat_2[1] = beat_7[1];
  assign gBeat_2[2] = beat_7[2];
  assign gBeat_2[3] = beat_7[3];
  assign gBeat_2[4] = beat_7[4];
  assign gBeat_2[5] = beat_7[5];
  assign gBeat_2[6] = beat_7[6];
  assign gBeat_2[7] = out0_71;

  assign gBeat_3 = (outputActive_5 == 1'b0 ? gBeat_1 :
              gBeat_2);

  assign gBeat = (out0_9 == 1'b0 ? gBeat_3 :
              gBeat_1);

  assign gBeatValid_1 = 1'b0;

  assign gBeatValid_2 = 1'b1;

  assign gBeatValid_3 = (outputActive_5 == 1'b0 ? gBeatValid_1 :
              gBeatValid_2);

  assign gBeatValid = (out0_9 == 1'b0 ? gBeatValid_3 :
              gBeatValid_1);

  assign sumFlushCount = 8'b10100110;

  assign sumFlushCount_1 = 8'b00000000;

  assign sumFlushCount_3 = (out0_5 == 1'b0 ? sumFlushCount_2 :
              sumFlushCount_1);

  assign sumFlushCount_5 = (out0_6 == 1'b0 ? sumFlushCount_4 :
              sumFlushCount_1);

  assign sumFlushCount_6 = (out0_7 == 1'b0 ? sumFlushCount_4 :
              sumFlushCount_5);

  assign sumFlushCount_8 = (out0_10 == 1'b0 ? sumFlushCount_7 :
              sumFlushCount);

  assign sumFlushCount_9 = (out0_1 == 1'b0 ? sumFlushCount_7 :
              sumFlushCount_8);

  assign subtract_1 = {1'b0, sumFlushCount_2};
  assign subtract_2 = {1'b0, const_expression_1};
  assign subtract_sub_temp = subtract_1 - subtract_2;
  assign sumFlushCount_10 = (subtract_sub_temp[8] == 1'b1 ? 8'b00000000 :
              subtract_sub_temp[7:0]);

  assign sumFlushCount_7 = (out0_72 == 1'b0 ? sumFlushCount_2 :
              sumFlushCount_10);

  assign sumFlushCount_4 = (loadActive_2 == 1'b0 ? sumFlushCount_7 :
              sumFlushCount_9);

  assign sumFlushCount_11 = (outputActive_5 == 1'b0 ? sumFlushCount_4 :
              sumFlushCount_6);

  assign sumFlushCount_12 = (out0_9 == 1'b0 ? sumFlushCount_11 :
              sumFlushCount_3);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_19_process
      if (reset == 1'b1) begin
        sumFlushCount_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          sumFlushCount_2 <= sumFlushCount_12;
        end
      end
    end

  assign out0_73 = sumFlushCount_2 > 8'b00000000;

  assign out0_72 = pendingInvRms_2 & out0_73;

  assign captureInvRms_1 = 1'b0;

  assign out0_74 = sumFlushCount_2 == 8'b00000001;

  assign captureInvRms_2 = 1'b1;

  assign captureInvRms_3 = (out0_74 == 1'b0 ? captureInvRms_1 :
              captureInvRms_2);

  assign captureInvRms_4 = (out0_72 == 1'b0 ? captureInvRms_1 :
              captureInvRms_3);

  assign captureInvRms = (out0_9 == 1'b0 ? captureInvRms_4 :
              captureInvRms_1);

  assign sramWriteAddr_2 = 16'b0000000000000000;

  assign sramWriteAddr_3 = (out0_1 == 1'b0 ? sramWriteAddr_2 :
              sramWriteAddr_1);

  assign sramWriteAddr_4 = (loadActive_2 == 1'b0 ? sramWriteAddr_2 :
              sramWriteAddr_3);

  assign sramWriteAddr = (out0_9 == 1'b0 ? sramWriteAddr_4 :
              sramWriteAddr_2);

  assign sramWriteBank_1 = 1'b0;

  assign sramWriteBank_2 = (out0_1 == 1'b0 ? sramWriteBank_1 :
              pendingBank_1);

  assign sramWriteBank_3 = (loadActive_2 == 1'b0 ? sramWriteBank_1 :
              sramWriteBank_2);

  assign sramWriteBank = (out0_9 == 1'b0 ? sramWriteBank_3 :
              sramWriteBank_1);

  assign sramWriteValid_1 = 1'b0;

  assign sramWriteValid_2 = 1'b1;

  assign sramWriteValid_3 = (out0_1 == 1'b0 ? sramWriteValid_1 :
              sramWriteValid_2);

  assign sramWriteValid_4 = (loadActive_2 == 1'b0 ? sramWriteValid_1 :
              sramWriteValid_3);

  assign sramWriteValid = (out0_9 == 1'b0 ? sramWriteValid_4 :
              sramWriteValid_1);

  assign sramReadAddr_2 = 16'b0000000000000000;

  assign sramReadAddr_3 = (outputActive_5 == 1'b0 ? sramReadAddr_2 :
              sramReadAddr_1);

  assign sramReadAddr = (out0_9 == 1'b0 ? sramReadAddr_3 :
              sramReadAddr_2);

  assign sramReadBank_2 = 1'b0;

  assign sramReadBank_3 = (outputActive_5 == 1'b0 ? sramReadBank_2 :
              sramReadBank_1);

  assign sramReadBank = (out0_9 == 1'b0 ? sramReadBank_3 :
              sramReadBank_2);

  assign sramReadValid_1 = 1'b0;

  assign sramReadValid_2 = 1'b1;

  assign sramReadValid_3 = (outputActive_5 == 1'b0 ? sramReadValid_1 :
              sramReadValid_2);

  assign sramReadValid = (out0_9 == 1'b0 ? sramReadValid_3 :
              sramReadValid_1);

  assign ddrReadAddr_1 = 16'b0000000000000000;

  assign const_expression_4 = 16'b0000000000000001;

  assign requestBeatIndex = 16'b0000000000000000;

  assign requestBeatIndex_2 = (out0_5 == 1'b0 ? requestBeatIndex_1 :
              requestBeatIndex);

  assign requestBeatIndex_4 = (canStartLoad_2 == 1'b0 ? requestBeatIndex_3 :
              requestBeatIndex);

  assign requestBeatIndex_6 = (out0_6 == 1'b0 ? requestBeatIndex_5 :
              requestBeatIndex);

  assign requestBeatIndex_7 = (out0_7 == 1'b0 ? requestBeatIndex_5 :
              requestBeatIndex_6);

  assign requestBeatIndex_9 = (out0_10 == 1'b0 ? requestBeatIndex_8 :
              requestBeatIndex);

  assign adder_109 = {1'b0, requestBeatIndex_1};
  assign adder_110 = {1'b0, const_expression_4};
  assign adder_add_temp_36 = adder_109 + adder_110;
  assign requestBeatIndex_10 = (adder_add_temp_36[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_36[15:0]);

  assign requestBeatIndex_8 = (out0_75 == 1'b0 ? requestBeatIndex_1 :
              requestBeatIndex_10);

  assign requestBeatIndex_11 = (out0_1 == 1'b0 ? requestBeatIndex_8 :
              requestBeatIndex_9);

  assign requestBeatIndex_5 = (loadActive_2 == 1'b0 ? requestBeatIndex_1 :
              requestBeatIndex_11);

  assign requestBeatIndex_3 = (outputActive_5 == 1'b0 ? requestBeatIndex_5 :
              requestBeatIndex_7);

  assign requestBeatIndex_12 = (out0_8 == 1'b0 ? requestBeatIndex_3 :
              requestBeatIndex_4);

  assign requestBeatIndex_13 = (out0_9 == 1'b0 ? requestBeatIndex_12 :
              requestBeatIndex_2);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_20_process
      if (reset == 1'b1) begin
        requestBeatIndex_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          requestBeatIndex_1 <= requestBeatIndex_13;
        end
      end
    end

  assign out0_75 = requestBeatIndex_1 < 16'b0000000011000000;

  assign ddrReadAddr_2 = 16'b0000000000000000;

  assign out0_76 = {8'b0, pendingTokenIndex};

  assign gain_mul_temp = 16'b0000000011000000 * out0_76;
  assign out0_77 = (gain_mul_temp[31:16] != 16'b0000000000000000 ? 16'b1111111111111111 :
              gain_mul_temp[15:0]);

  assign adder_112 = {1'b0, out0_77};
  assign adder_113 = {1'b0, requestBeatIndex_1};
  assign adder_add_temp_37 = adder_112 + adder_113;
  assign ddrReadAddr_3 = (adder_add_temp_37[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_37[15:0]);

  assign ddrReadAddr_4 = (out0_75 == 1'b0 ? ddrReadAddr_2 :
              ddrReadAddr_3);

  assign ddrReadAddr_5 = (loadActive_2 == 1'b0 ? ddrReadAddr_1 :
              ddrReadAddr_4);

  assign ddrReadAddr = (out0_9 == 1'b0 ? ddrReadAddr_5 :
              ddrReadAddr_1);

  assign ddrReadEn_1 = 1'b0;

  assign ddrReadEn_2 = 1'b0;

  assign ddrReadEn_3 = 1'b1;

  assign ddrReadEn_4 = (out0_75 == 1'b0 ? ddrReadEn_2 :
              ddrReadEn_3);

  assign ddrReadEn_5 = (loadActive_2 == 1'b0 ? ddrReadEn_1 :
              ddrReadEn_4);

  assign ddrReadEn = (out0_9 == 1'b0 ? ddrReadEn_5 :
              ddrReadEn_1);

  assign done_1 = 1'b0;

  assign done_2 = 1'b1;

  assign done_3 = (out0_6 == 1'b0 ? done_1 :
              done_2);

  assign done_4 = (out0_7 == 1'b0 ? done_1 :
              done_3);

  assign done_5 = (outputActive_5 == 1'b0 ? done_1 :
              done_4);

  assign done = (out0_9 == 1'b0 ? done_5 :
              done_1);

  assign busy_1 = 1'b1;

  assign busy_2 = 1'b0;

  assign busy_3 = (out0_6 == 1'b0 ? busy_1 :
              busy_2);

  assign busy_4 = (out0_7 == 1'b0 ? busy_1 :
              busy_3);

  assign busy_5 = (outputActive_5 == 1'b0 ? busy_1 :
              busy_4);

  assign busy_6 = state_2 != 8'b00000000;

  assign busy_7 = (out0_5 == 1'b0 ? busy_6 :
              busy_1);

  assign busy = (out0_9 == 1'b0 ? busy_5 :
              busy_7);

endmodule  // Controller

