// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/CoreDUT.sv
// Created: 2026-03-19 12:47:24
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: CoreDUT
// Source Path: rmsNormalization/DUTPacked/CoreDUT
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CoreDUT
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic reset_1,
             input logic start,
             input logic [31:0] cfgGammaBeat[0:7]  /* single [8] */,
             input logic cfgGammaValid,
             input logic [31:0] ddrDataBeat[0:7]  /* single [8] */,
             input logic ddrDataValid,
             output logic [31:0] outBeat[0:7]  /* single [8] */,
             output logic outValid,
             output logic [15:0] ddrReadAddr  /* uint16 */,
             output logic ddrReadEn,
             output logic done,
             output logic busy);


  logic [31:0] xBeat [0:7];  /* ufix32 [8] */
  logic xBeatValid;
  logic [31:0] gBeat [0:7];  /* ufix32 [8] */
  logic gBeatValid;
  logic captureInvRms;
  logic [31:0] SquareBeat_squaredBeat [0:7];  /* ufix32 [8] */
  logic SquareBeat_squaredBeatValid;
  logic [31:0] BeatReduce_beatSum;  /* ufix32 */
  logic BeatReduce_beatSumValid;
  logic InvRmsLatch_clearAccumulator;
  logic [31:0] BeatAccumulator_currentSum;  /* ufix32 */
  logic BeatAccumulator_currentSumValid;
  logic [31:0] ScalarRsqrt_invRms;  /* ufix32 */
  logic ScalarRsqrt_invRmsValid;
  logic [31:0] InvRmsLatch_invRmsLatched;  /* ufix32 */
  logic InvRmsLatch_invRmsLatchedValid;
  logic [31:0] LaneMultiply_yBeat [0:7];  /* ufix32 [8] */
  logic LaneMultiply_yBeatValid;


  Controller u_Controller (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .reset_1(reset_1),
                           .start(start),
                           .cfgGammaBeat(cfgGammaBeat),  /* single [8] */
                           .cfgGammaValid(cfgGammaValid),
                           .ddrDataBeat(ddrDataBeat),  /* single [8] */
                           .ddrDataValid(ddrDataValid),
                           .xBeat(xBeat),  /* single [8] */
                           .xBeatValid(xBeatValid),
                           .gBeat(gBeat),  /* single [8] */
                           .gBeatValid(gBeatValid),
                           .captureInvRms(captureInvRms),
                           .ddrReadAddr(ddrReadAddr),  /* uint16 */
                           .ddrReadEn(ddrReadEn),
                           .done(done),
                           .busy(busy)
                           );

  SquareBeat u_SquareBeat (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .ddrDataBeat(ddrDataBeat),  /* single [8] */
                           .ddrDataBeatValid(ddrDataValid),
                           .squaredBeat(SquareBeat_squaredBeat),  /* single [8] */
                           .squaredBeatValid(SquareBeat_squaredBeatValid)
                           );

  BeatReduce u_BeatReduce (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .squaredBeat(SquareBeat_squaredBeat),  /* single [8] */
                           .squaredBeatValid(SquareBeat_squaredBeatValid),
                           .beatSum(BeatReduce_beatSum),  /* single */
                           .beatSumValid(BeatReduce_beatSumValid)
                           );

  BeatAccumulator u_BeatAccumulator (.clk(clk),
                                     .reset(reset),
                                     .enb(enb),
                                     .beatSum(BeatReduce_beatSum),  /* single */
                                     .beatSumValid(BeatReduce_beatSumValid),
                                     .reset_1(reset_1),
                                     .clearAccumulator(InvRmsLatch_clearAccumulator),
                                     .currentSum(BeatAccumulator_currentSum),  /* single */
                                     .currentSumValid(BeatAccumulator_currentSumValid)
                                     );

  ScalarRsqrt u_ScalarRsqrt (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .currentSum(BeatAccumulator_currentSum),  /* single */
                             .currentSumValid(BeatAccumulator_currentSumValid),
                             .invRms(ScalarRsqrt_invRms),  /* single */
                             .invRmsValid(ScalarRsqrt_invRmsValid)
                             );

  InvRmsLatch u_InvRmsLatch (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .invRmsIn(ScalarRsqrt_invRms),  /* single */
                             .invRmsInValid(ScalarRsqrt_invRmsValid),
                             .capture(captureInvRms),
                             .reset_1(reset_1),
                             .invRmsLatched(InvRmsLatch_invRmsLatched),  /* single */
                             .invRmsLatchedValid(InvRmsLatch_invRmsLatchedValid),
                             .clearAccumulator(InvRmsLatch_clearAccumulator)
                             );

  LaneMultiply u_LaneMultiply (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .xBeat(xBeat),  /* single [8] */
                               .xBeatValid(xBeatValid),
                               .gBeat(gBeat),  /* single [8] */
                               .gBeatValid(gBeatValid),
                               .invRms(InvRmsLatch_invRmsLatched),  /* single */
                               .invRmsValid(InvRmsLatch_invRmsLatchedValid),
                               .yBeat(LaneMultiply_yBeat),  /* single [8] */
                               .yBeatValid(LaneMultiply_yBeatValid)
                               );

  assign outBeat = LaneMultiply_yBeat;

  assign outValid = LaneMultiply_yBeatValid;

endmodule  // CoreDUT

