// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/CoreDUT.sv
// Created: 2026-03-20 10:42:02
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: CoreDUT
// Source Path: rmsNormalization/DUTPacked/CoreDUT
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CoreDUT
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic start,
             input logic [31:0] cfgGammaBeat[0:7]  /* single [8] */,
             input logic cfgGammaValid,
             input logic [31:0] ddrDataBeat[0:7]  /* single [8] */,
             input logic ddrDataValid,
             output logic [31:0] outBeat[0:7]  /* single [8] */,
             output logic outValid,
             output logic [15:0] ddrReadAddr  /* uint16 */,
             output logic ddrReadEn,
             output logic done,
             output logic busy);


  logic [31:0] SquareBeat_squaredBeat [0:7];  /* ufix32 [8] */
  logic SquareBeat_squaredBeatValid;
  logic [31:0] BeatReduce_beatSum;  /* ufix32 */
  logic BeatReduce_beatSumValid;
  logic ClearAccumulatorFeedback_out1;
  logic [31:0] BeatAccumulator_currentSum;  /* ufix32 */
  logic BeatAccumulator_currentSumValid;
  logic [31:0] ScalarRsqrt_invRms;  /* ufix32 */
  logic ScalarRsqrt_invRmsValid;
  logic captureInvRms;
  logic [31:0] InvRmsLatch_invRmsLatched;  /* ufix32 */
  logic InvRmsLatch_invRmsLatchedValid;
  logic InvRmsLatch_clearAccumulator;
  logic [31:0] gBeat [0:7];  /* ufix32 [8] */
  logic gBeatValid;
  logic [15:0] sramWriteAddr;  /* uint16 */
  logic sramWriteBank;
  logic sramWriteValid;
  logic [15:0] sramReadAddr;  /* uint16 */
  logic sramReadBank;
  logic sramReadValid;
  logic [15:0] sramWriteAddr_1;  /* uint16 */
  logic sramWriteBank_1;
  logic [31:0] TokenSram_readBeat [0:7];  /* ufix32 [8] */
  logic TokenSram_readValid;
  logic [31:0] LaneMultiply_yBeat [0:7];  /* ufix32 [8] */
  logic LaneMultiply_yBeatValid;


  SquareBeat u_SquareBeat (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .ddrDataBeat(ddrDataBeat),  /* single [8] */
                           .ddrDataBeatValid(ddrDataValid),
                           .squaredBeat(SquareBeat_squaredBeat),  /* single [8] */
                           .squaredBeatValid(SquareBeat_squaredBeatValid)
                           );

  BeatReduce u_BeatReduce (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .squaredBeat(SquareBeat_squaredBeat),  /* single [8] */
                           .squaredBeatValid(SquareBeat_squaredBeatValid),
                           .beatSum(BeatReduce_beatSum),  /* single */
                           .beatSumValid(BeatReduce_beatSumValid)
                           );

  BeatAccumulator u_BeatAccumulator (.clk(clk),
                                     .reset(reset),
                                     .enb(enb),
                                     .beatSum(BeatReduce_beatSum),  /* single */
                                     .beatSumValid(BeatReduce_beatSumValid),
                                     .clearAccumulator(ClearAccumulatorFeedback_out1),
                                     .currentSum(BeatAccumulator_currentSum),  /* single */
                                     .currentSumValid(BeatAccumulator_currentSumValid)
                                     );

  ScalarRsqrt u_ScalarRsqrt (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .currentSum(BeatAccumulator_currentSum),  /* single */
                             .currentSumValid(BeatAccumulator_currentSumValid),
                             .invRms(ScalarRsqrt_invRms),  /* single */
                             .invRmsValid(ScalarRsqrt_invRmsValid)
                             );

  InvRmsLatch u_InvRmsLatch (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .invRmsIn(ScalarRsqrt_invRms),  /* single */
                             .invRmsInValid(ScalarRsqrt_invRmsValid),
                             .capture(captureInvRms),
                             .invRmsLatched(InvRmsLatch_invRmsLatched),  /* single */
                             .invRmsLatchedValid(InvRmsLatch_invRmsLatchedValid),
                             .clearAccumulator(InvRmsLatch_clearAccumulator)
                             );

  always_ff @(posedge clk or posedge reset)
    begin : ClearAccumulatorFeedback_process
      if (reset == 1'b1) begin
        ClearAccumulatorFeedback_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          ClearAccumulatorFeedback_out1 <= InvRmsLatch_clearAccumulator;
        end
      end
    end

  Controller u_Controller (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .start(start),
                           .cfgGammaBeat(cfgGammaBeat),  /* single [8] */
                           .cfgGammaValid(cfgGammaValid),
                           .ddrDataValid(ddrDataValid),
                           .invRmsAccepted(ClearAccumulatorFeedback_out1),
                           .gBeat(gBeat),  /* single [8] */
                           .gBeatValid(gBeatValid),
                           .captureInvRms(captureInvRms),
                           .sramWriteAddr(sramWriteAddr),  /* uint16 */
                           .sramWriteBank(sramWriteBank),
                           .sramWriteValid(sramWriteValid),
                           .sramReadAddr(sramReadAddr),  /* uint16 */
                           .sramReadBank(sramReadBank),
                           .sramReadValid(sramReadValid),
                           .ddrReadAddr(ddrReadAddr),  /* uint16 */
                           .ddrReadEn(ddrReadEn),
                           .done(done),
                           .busy(busy)
                           );

  assign sramWriteAddr_1 = sramWriteAddr;

  assign sramWriteBank_1 = sramWriteBank;

  TokenSram u_TokenSram (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .writeBeat(ddrDataBeat),  /* single [8] */
                         .writeAddr(sramWriteAddr_1),  /* uint16 */
                         .writeBank(sramWriteBank_1),
                         .writeValid(sramWriteValid),
                         .readAddr(sramReadAddr),  /* uint16 */
                         .readBank(sramReadBank),
                         .readReq(sramReadValid),
                         .readBeat(TokenSram_readBeat),  /* single [8] */
                         .readValid(TokenSram_readValid)
                         );

  LaneMultiply u_LaneMultiply (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .xBeat(TokenSram_readBeat),  /* single [8] */
                               .xBeatValid(TokenSram_readValid),
                               .gBeat(gBeat),  /* single [8] */
                               .gBeatValid(gBeatValid),
                               .invRms(InvRmsLatch_invRmsLatched),  /* single */
                               .invRmsValid(InvRmsLatch_invRmsLatchedValid),
                               .yBeat(LaneMultiply_yBeat),  /* single [8] */
                               .yBeatValid(LaneMultiply_yBeatValid)
                               );

  assign outBeat = LaneMultiply_yBeat;

  assign outValid = LaneMultiply_yBeatValid;

endmodule  // CoreDUT

