// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/CoreDUT.sv
// Created: 2026-03-20 16:46:19
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: CoreDUT
// Source Path: rmsNormalization/DUTPacked/CoreDUT
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CoreDUT
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic start,
             input logic [31:0] cfgGammaBeat[0:7]  /* single [8] */,
             input logic cfgGammaValid,
             input logic [31:0] ddrDataBeat[0:7]  /* single [8] */,
             input logic ddrDataValid,
             output logic [31:0] outBeat[0:7]  /* single [8] */,
             output logic outValid,
             output logic [15:0] ddrReadAddr  /* uint16 */,
             output logic ddrReadEn,
             output logic done,
             output logic busy);


  logic [31:0] SquareBeat_squaredBeat [0:7];  /* ufix32 [8] */
  logic SquareBeat_squaredBeatValid;
  logic [31:0] BeatReduce_beatSum;  /* ufix32 */
  logic BeatReduce_beatSumValid;
  logic captureInvRms;
  logic captureInvRmsBank;
  logic CaptureInvRmsBank1_out1;
  logic WriteBankAccumDelay_out1;
  logic BeatSumValidBank1_out1;
  logic ClearAccumulatorFeedback1_out1;
  logic [31:0] BeatAccumulator1_currentSum;  /* ufix32 */
  logic BeatAccumulator1_currentSumValid;
  logic [31:0] ScalarRsqrt1_invRms;  /* ufix32 */
  logic ScalarRsqrt1_invRmsValid;
  logic [31:0] InvRmsLatch1_invRmsLatched;  /* ufix32 */
  logic InvRmsLatch1_invRmsLatchedValid;
  logic InvRmsLatch1_clearAccumulator;
  logic captureInvRmsBank_1;
  logic CaptureBankNot_out1;
  logic CaptureInvRmsBank0_out1;
  logic sramWriteBank;
  logic sramWriteBank_1;
  logic [40:0] WriteBankAccumDelay_reg;  /* ufix1 [41] */
  logic WriteBankNot_out1;
  logic BeatSumValidBank0_out1;
  logic ClearAccumulatorFeedback0_out1;
  logic [31:0] BeatAccumulator0_currentSum;  /* ufix32 */
  logic BeatAccumulator0_currentSumValid;
  logic [31:0] ScalarRsqrt0_invRms;  /* ufix32 */
  logic ScalarRsqrt0_invRmsValid;
  logic [31:0] InvRmsLatch0_invRmsLatched;  /* ufix32 */
  logic InvRmsLatch0_invRmsLatchedValid;
  logic InvRmsLatch0_clearAccumulator;
  logic [31:0] gBeat [0:7];  /* ufix32 [8] */
  logic gBeatValid;
  logic [15:0] sramWriteAddr;  /* uint16 */
  logic sramWriteValid;
  logic [15:0] sramReadAddr;  /* uint16 */
  logic sramReadBank;
  logic sramReadValid;
  logic [15:0] sramWriteAddr_1;  /* uint16 */
  logic [31:0] TokenSram_readBeat [0:7];  /* ufix32 [8] */
  logic TokenSram_readValid;
  logic sramReadBank_1;
  logic [31:0] SelectedInvRms_out1;  /* ufix32 */
  logic SelectedInvRmsValid_out1;
  logic [15:0] sramReadAddr_1;  /* uint16 */
  logic [15:0] ReadAddrZeroConst_out1;  /* uint16 */
  logic ReadAddrIsZero_out1;
  logic OutputTokenStart_out1;
  logic [31:0] OutputInvRmsLatch_invRmsLatched;  /* ufix32 */
  logic OutputInvRmsLatch_invRmsLatchedValid;
  logic OutputInvRmsLatch_clearAccumulatordeadOut;
  logic [31:0] LaneMultiply_yBeat [0:7];  /* ufix32 [8] */
  logic LaneMultiply_yBeatValid;


  SquareBeat u_SquareBeat (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .ddrDataBeat(ddrDataBeat),  /* single [8] */
                           .ddrDataBeatValid(ddrDataValid),
                           .squaredBeat(SquareBeat_squaredBeat),  /* single [8] */
                           .squaredBeatValid(SquareBeat_squaredBeatValid)
                           );

  BeatReduce u_BeatReduce (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .squaredBeat(SquareBeat_squaredBeat),  /* single [8] */
                           .squaredBeatValid(SquareBeat_squaredBeatValid),
                           .beatSum(BeatReduce_beatSum),  /* single */
                           .beatSumValid(BeatReduce_beatSumValid)
                           );

  assign CaptureInvRmsBank1_out1 = captureInvRms & captureInvRmsBank;

  assign BeatSumValidBank1_out1 = BeatReduce_beatSumValid & WriteBankAccumDelay_out1;

  BeatAccumulator0 u_BeatAccumulator1 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .beatSum(BeatReduce_beatSum),  /* single */
                                       .beatSumValid(BeatSumValidBank1_out1),
                                       .clearAccumulator(ClearAccumulatorFeedback1_out1),
                                       .currentSum(BeatAccumulator1_currentSum),  /* single */
                                       .currentSumValid(BeatAccumulator1_currentSumValid)
                                       );

  ScalarRsqrt0 u_ScalarRsqrt1 (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .currentSum(BeatAccumulator1_currentSum),  /* single */
                               .currentSumValid(BeatAccumulator1_currentSumValid),
                               .invRms(ScalarRsqrt1_invRms),  /* single */
                               .invRmsValid(ScalarRsqrt1_invRmsValid)
                               );

  InvRmsLatch0 u_InvRmsLatch1 (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .invRmsIn(ScalarRsqrt1_invRms),  /* single */
                               .invRmsInValid(ScalarRsqrt1_invRmsValid),
                               .capture(CaptureInvRmsBank1_out1),
                               .invRmsLatched(InvRmsLatch1_invRmsLatched),  /* single */
                               .invRmsLatchedValid(InvRmsLatch1_invRmsLatchedValid),
                               .clearAccumulator(InvRmsLatch1_clearAccumulator)
                               );

  always_ff @(posedge clk or posedge reset)
    begin : ClearAccumulatorFeedback1_process
      if (reset == 1'b1) begin
        ClearAccumulatorFeedback1_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          ClearAccumulatorFeedback1_out1 <= InvRmsLatch1_clearAccumulator;
        end
      end
    end

  assign captureInvRmsBank = captureInvRmsBank_1;

  assign CaptureBankNot_out1 =  ~ captureInvRmsBank;

  assign CaptureInvRmsBank0_out1 = captureInvRms & CaptureBankNot_out1;

  assign sramWriteBank_1 = sramWriteBank;

  always_ff @(posedge clk or posedge reset)
    begin : WriteBankAccumDelay_process
      if (reset == 1'b1) begin
        WriteBankAccumDelay_reg <= '{41{1'b0}};
      end
      else begin
        if (enb) begin
          WriteBankAccumDelay_reg[0] <= sramWriteBank_1;
          WriteBankAccumDelay_reg[32'sd40:32'sd1] <= WriteBankAccumDelay_reg[32'sd39:32'sd0];
        end
      end
    end

  assign WriteBankAccumDelay_out1 = WriteBankAccumDelay_reg[40];

  assign WriteBankNot_out1 =  ~ WriteBankAccumDelay_out1;

  assign BeatSumValidBank0_out1 = BeatReduce_beatSumValid & WriteBankNot_out1;

  BeatAccumulator0 u_BeatAccumulator0 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .beatSum(BeatReduce_beatSum),  /* single */
                                       .beatSumValid(BeatSumValidBank0_out1),
                                       .clearAccumulator(ClearAccumulatorFeedback0_out1),
                                       .currentSum(BeatAccumulator0_currentSum),  /* single */
                                       .currentSumValid(BeatAccumulator0_currentSumValid)
                                       );

  ScalarRsqrt0 u_ScalarRsqrt0 (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .currentSum(BeatAccumulator0_currentSum),  /* single */
                               .currentSumValid(BeatAccumulator0_currentSumValid),
                               .invRms(ScalarRsqrt0_invRms),  /* single */
                               .invRmsValid(ScalarRsqrt0_invRmsValid)
                               );

  InvRmsLatch0 u_InvRmsLatch0 (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .invRmsIn(ScalarRsqrt0_invRms),  /* single */
                               .invRmsInValid(ScalarRsqrt0_invRmsValid),
                               .capture(CaptureInvRmsBank0_out1),
                               .invRmsLatched(InvRmsLatch0_invRmsLatched),  /* single */
                               .invRmsLatchedValid(InvRmsLatch0_invRmsLatchedValid),
                               .clearAccumulator(InvRmsLatch0_clearAccumulator)
                               );

  always_ff @(posedge clk or posedge reset)
    begin : ClearAccumulatorFeedback0_process
      if (reset == 1'b1) begin
        ClearAccumulatorFeedback0_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          ClearAccumulatorFeedback0_out1 <= InvRmsLatch0_clearAccumulator;
        end
      end
    end

  Controller u_Controller (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .start(start),
                           .cfgGammaBeat(cfgGammaBeat),  /* single [8] */
                           .cfgGammaValid(cfgGammaValid),
                           .ddrDataValid(ddrDataValid),
                           .invRmsAcceptedBank0(ClearAccumulatorFeedback0_out1),
                           .invRmsAcceptedBank1(ClearAccumulatorFeedback1_out1),
                           .gBeat(gBeat),  /* single [8] */
                           .gBeatValid(gBeatValid),
                           .captureInvRms(captureInvRms),
                           .captureInvRmsBank(captureInvRmsBank_1),
                           .sramWriteAddr(sramWriteAddr),  /* uint16 */
                           .sramWriteBank(sramWriteBank),
                           .sramWriteValid(sramWriteValid),
                           .sramReadAddr(sramReadAddr),  /* uint16 */
                           .sramReadBank(sramReadBank),
                           .sramReadValid(sramReadValid),
                           .ddrReadAddr(ddrReadAddr),  /* uint16 */
                           .ddrReadEn(ddrReadEn),
                           .done(done),
                           .busy(busy)
                           );

  assign sramWriteAddr_1 = sramWriteAddr;

  TokenSram u_TokenSram (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .writeBeat(ddrDataBeat),  /* single [8] */
                         .writeAddr(sramWriteAddr_1),  /* uint16 */
                         .writeBank(sramWriteBank),
                         .writeValid(sramWriteValid),
                         .readAddr(sramReadAddr),  /* uint16 */
                         .readBank(sramReadBank),
                         .readReq(sramReadValid),
                         .readBeat(TokenSram_readBeat),  /* single [8] */
                         .readValid(TokenSram_readValid)
                         );

  assign sramReadBank_1 = sramReadBank;

  assign SelectedInvRms_out1 = (sramReadBank_1 == 1'b0 ? InvRmsLatch0_invRmsLatched :
              InvRmsLatch1_invRmsLatched);

  assign SelectedInvRmsValid_out1 = (sramReadBank_1 == 1'b0 ? InvRmsLatch0_invRmsLatchedValid :
              InvRmsLatch1_invRmsLatchedValid);

  assign sramReadAddr_1 = sramReadAddr;

  assign ReadAddrZeroConst_out1 = 16'b0000000000000000;

  assign ReadAddrIsZero_out1 = sramReadAddr_1 == ReadAddrZeroConst_out1;

  assign OutputTokenStart_out1 = sramReadValid & ReadAddrIsZero_out1;

  InvRmsLatch0 u_OutputInvRmsLatch (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .invRmsIn(SelectedInvRms_out1),  /* single */
                                    .invRmsInValid(SelectedInvRmsValid_out1),
                                    .capture(OutputTokenStart_out1),
                                    .invRmsLatched(OutputInvRmsLatch_invRmsLatched),  /* single */
                                    .invRmsLatchedValid(OutputInvRmsLatch_invRmsLatchedValid),
                                    .clearAccumulator(OutputInvRmsLatch_clearAccumulatordeadOut)
                                    );

  LaneMultiply u_LaneMultiply (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .xBeat(TokenSram_readBeat),  /* single [8] */
                               .xBeatValid(TokenSram_readValid),
                               .gBeat(gBeat),  /* single [8] */
                               .gBeatValid(gBeatValid),
                               .invRms(OutputInvRmsLatch_invRmsLatched),  /* single */
                               .invRmsValid(OutputInvRmsLatch_invRmsLatchedValid),
                               .yBeat(LaneMultiply_yBeat),  /* single [8] */
                               .yBeatValid(LaneMultiply_yBeatValid)
                               );

  assign outBeat = LaneMultiply_yBeat;

  assign outValid = LaneMultiply_yBeatValid;

endmodule  // CoreDUT

