// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/DUT.v
// Created: 2026-03-18 09:48:18
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// outBeat_0                     ce_out        1
// outBeat_1                     ce_out        1
// outBeat_2                     ce_out        1
// outBeat_3                     ce_out        1
// outBeat_4                     ce_out        1
// outBeat_5                     ce_out        1
// outBeat_6                     ce_out        1
// outBeat_7                     ce_out        1
// outValid                      ce_out        1
// ddrReadAddr                   ce_out        1
// ddrReadEn                     ce_out        1
// done                          ce_out        1
// busy                          ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DUT
// Source Path: rmsNormalization/DUT
// Hierarchy Level: 0
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DUT
          (clk,
           reset,
           clk_enable,
           reset_1,
           start,
           cfgGammaBeat_0,
           cfgGammaBeat_1,
           cfgGammaBeat_2,
           cfgGammaBeat_3,
           cfgGammaBeat_4,
           cfgGammaBeat_5,
           cfgGammaBeat_6,
           cfgGammaBeat_7,
           cfgGammaValid,
           ddrDataBeat_0,
           ddrDataBeat_1,
           ddrDataBeat_2,
           ddrDataBeat_3,
           ddrDataBeat_4,
           ddrDataBeat_5,
           ddrDataBeat_6,
           ddrDataBeat_7,
           ddrDataValid,
           ce_out,
           outBeat_0,
           outBeat_1,
           outBeat_2,
           outBeat_3,
           outBeat_4,
           outBeat_5,
           outBeat_6,
           outBeat_7,
           outValid,
           ddrReadAddr,
           ddrReadEn,
           done,
           busy);


  input   clk;
  input   reset;
  input   clk_enable;
  input   reset_1;
  input   start;
  input   [31:0] cfgGammaBeat_0;  // single
  input   [31:0] cfgGammaBeat_1;  // single
  input   [31:0] cfgGammaBeat_2;  // single
  input   [31:0] cfgGammaBeat_3;  // single
  input   [31:0] cfgGammaBeat_4;  // single
  input   [31:0] cfgGammaBeat_5;  // single
  input   [31:0] cfgGammaBeat_6;  // single
  input   [31:0] cfgGammaBeat_7;  // single
  input   cfgGammaValid;
  input   [31:0] ddrDataBeat_0;  // single
  input   [31:0] ddrDataBeat_1;  // single
  input   [31:0] ddrDataBeat_2;  // single
  input   [31:0] ddrDataBeat_3;  // single
  input   [31:0] ddrDataBeat_4;  // single
  input   [31:0] ddrDataBeat_5;  // single
  input   [31:0] ddrDataBeat_6;  // single
  input   [31:0] ddrDataBeat_7;  // single
  input   ddrDataValid;
  output  ce_out;
  output  [31:0] outBeat_0;  // single
  output  [31:0] outBeat_1;  // single
  output  [31:0] outBeat_2;  // single
  output  [31:0] outBeat_3;  // single
  output  [31:0] outBeat_4;  // single
  output  [31:0] outBeat_5;  // single
  output  [31:0] outBeat_6;  // single
  output  [31:0] outBeat_7;  // single
  output  outValid;
  output  [15:0] ddrReadAddr;  // uint16
  output  ddrReadEn;
  output  done;
  output  busy;


  wire enb;
  reg  [40:0] delayMatch_reg;  // ufix1 [41]
  wire reset_2;
  reg  [40:0] delayMatch2_reg;  // ufix1 [41]
  wire start_1;
  wire [31:0] CfgBeatSpec_out1 [0:7];  // ufix32 [8]
  reg [31:0] delayMatch3_reg [0:327];  // ufix32 [328]
  reg [31:0] delayMatch3_reg_next [0:327];  // ufix32 [328]
  reg [31:0] CfgBeatSpec_out1_1 [0:7];  // ufix32 [8]
  reg  [40:0] delayMatch4_reg;  // ufix1 [41]
  wire cfgGammaValid_1;
  wire [31:0] DdrBeatSpec_out1 [0:7];  // ufix32 [8]
  reg [31:0] delayMatch5_reg [0:327];  // ufix32 [328]
  reg [31:0] delayMatch5_reg_next [0:327];  // ufix32 [328]
  reg [31:0] DdrBeatSpec_out1_1 [0:7];  // ufix32 [8]
  reg  [40:0] delayMatch1_reg;  // ufix1 [41]
  wire ddrDataValid_1;
  wire [31:0] SquareBeat_squaredBeat_0;  // ufix32
  wire [31:0] SquareBeat_squaredBeat_1;  // ufix32
  wire [31:0] SquareBeat_squaredBeat_2;  // ufix32
  wire [31:0] SquareBeat_squaredBeat_3;  // ufix32
  wire [31:0] SquareBeat_squaredBeat_4;  // ufix32
  wire [31:0] SquareBeat_squaredBeat_5;  // ufix32
  wire [31:0] SquareBeat_squaredBeat_6;  // ufix32
  wire [31:0] SquareBeat_squaredBeat_7;  // ufix32
  wire [31:0] BeatReduce_beatSum;  // ufix32
  wire captureInvRms;
  reg  CaptureClearDelay_out1;
  wire ClearAccumulator_out1;
  wire [31:0] BeatAccumulator_currentSum;  // ufix32
  wire [31:0] rsqrtOperand;  // ufix32
  wire [31:0] xBeatOut_0;  // ufix32
  wire [31:0] xBeatOut_1;  // ufix32
  wire [31:0] xBeatOut_2;  // ufix32
  wire [31:0] xBeatOut_3;  // ufix32
  wire [31:0] xBeatOut_4;  // ufix32
  wire [31:0] xBeatOut_5;  // ufix32
  wire [31:0] xBeatOut_6;  // ufix32
  wire [31:0] xBeatOut_7;  // ufix32
  wire [31:0] gBeatOut_0;  // ufix32
  wire [31:0] gBeatOut_1;  // ufix32
  wire [31:0] gBeatOut_2;  // ufix32
  wire [31:0] gBeatOut_3;  // ufix32
  wire [31:0] gBeatOut_4;  // ufix32
  wire [31:0] gBeatOut_5;  // ufix32
  wire [31:0] gBeatOut_6;  // ufix32
  wire [31:0] gBeatOut_7;  // ufix32
  wire outValid_1;
  wire [15:0] ddrReadAddr_1;  // uint16
  wire ddrReadEn_1;
  wire done_1;
  wire busy_1;
  wire [31:0] InvRmsDelay_out1;  // ufix32
  wire [31:0] InvRmsLatch_invRmsLatched;  // ufix32
  wire [31:0] LaneMultiply_yBeat_0;  // ufix32
  wire [31:0] LaneMultiply_yBeat_1;  // ufix32
  wire [31:0] LaneMultiply_yBeat_2;  // ufix32
  wire [31:0] LaneMultiply_yBeat_3;  // ufix32
  wire [31:0] LaneMultiply_yBeat_4;  // ufix32
  wire [31:0] LaneMultiply_yBeat_5;  // ufix32
  wire [31:0] LaneMultiply_yBeat_6;  // ufix32
  wire [31:0] LaneMultiply_yBeat_7;  // ufix32
  reg  [147:0] delayMatch6_reg;  // ufix1 [148]
  reg [15:0] delayMatch7_reg [0:147];  // ufix16 [148]
  reg [15:0] delayMatch7_reg_next [0:147];  // ufix16 [148]
  reg [15:0] ddrReadAddr_2;  // uint16
  reg  [147:0] delayMatch8_reg;  // ufix1 [148]
  reg  [147:0] delayMatch9_reg;  // ufix1 [148]
  reg  [147:0] delayMatch10_reg;  // ufix1 [148]
  reg signed [31:0] delayMatch3_t_0_0;  // int32
  reg signed [31:0] delayMatch3_t_1;  // int32
  reg signed [31:0] delayMatch3_t_0_1;  // int32
  reg signed [31:0] delayMatch3_t_1_0;  // int32
  reg signed [31:0] delayMatch5_t_0_0;  // int32
  reg signed [31:0] delayMatch5_t_1;  // int32
  reg signed [31:0] delayMatch5_t_0_1;  // int32
  reg signed [31:0] delayMatch5_t_1_0;  // int32
  reg signed [31:0] delayMatch7_t_0_0;  // int32
  reg signed [31:0] delayMatch7_t_0_1;  // int32
  reg signed [31:0] delayMatch7_t_1;  // int32


  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {41{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= reset_1;
          delayMatch_reg[32'sd40:32'sd1] <= delayMatch_reg[32'sd39:32'sd0];
        end
      end
    end

  assign reset_2 = delayMatch_reg[40];

  always @(posedge clk or posedge reset)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        delayMatch2_reg <= {41{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch2_reg[0] <= start;
          delayMatch2_reg[32'sd40:32'sd1] <= delayMatch2_reg[32'sd39:32'sd0];
        end
      end
    end

  assign start_1 = delayMatch2_reg[40];

  assign CfgBeatSpec_out1[0] = cfgGammaBeat_0;
  assign CfgBeatSpec_out1[1] = cfgGammaBeat_1;
  assign CfgBeatSpec_out1[2] = cfgGammaBeat_2;
  assign CfgBeatSpec_out1[3] = cfgGammaBeat_3;
  assign CfgBeatSpec_out1[4] = cfgGammaBeat_4;
  assign CfgBeatSpec_out1[5] = cfgGammaBeat_5;
  assign CfgBeatSpec_out1[6] = cfgGammaBeat_6;
  assign CfgBeatSpec_out1[7] = cfgGammaBeat_7;
  always @(posedge clk or posedge reset)
    begin : delayMatch3_process
      if (reset == 1'b1) begin
        for(delayMatch3_t_1_0 = 32'sd0; delayMatch3_t_1_0 <= 32'sd327; delayMatch3_t_1_0 = delayMatch3_t_1_0 + 32'sd1) begin
          delayMatch3_reg[delayMatch3_t_1_0] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch3_t_0_1 = 32'sd0; delayMatch3_t_0_1 <= 32'sd327; delayMatch3_t_0_1 = delayMatch3_t_0_1 + 32'sd1) begin
            delayMatch3_reg[delayMatch3_t_0_1] <= delayMatch3_reg_next[delayMatch3_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(delayMatch3_t_0_0 = 32'sd0; delayMatch3_t_0_0 <= 32'sd7; delayMatch3_t_0_0 = delayMatch3_t_0_0 + 32'sd1) begin
      CfgBeatSpec_out1_1[delayMatch3_t_0_0] = delayMatch3_reg[32'sd320 + delayMatch3_t_0_0];
      delayMatch3_reg_next[delayMatch3_t_0_0] = CfgBeatSpec_out1[delayMatch3_t_0_0];
    end
    for(delayMatch3_t_1 = 32'sd0; delayMatch3_t_1 <= 32'sd319; delayMatch3_t_1 = delayMatch3_t_1 + 32'sd1) begin
      delayMatch3_reg_next[delayMatch3_t_1 + 32'sd8] = delayMatch3_reg[delayMatch3_t_1];
    end

  end

  always @(posedge clk or posedge reset)
    begin : delayMatch4_process
      if (reset == 1'b1) begin
        delayMatch4_reg <= {41{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch4_reg[0] <= cfgGammaValid;
          delayMatch4_reg[32'sd40:32'sd1] <= delayMatch4_reg[32'sd39:32'sd0];
        end
      end
    end

  assign cfgGammaValid_1 = delayMatch4_reg[40];

  assign DdrBeatSpec_out1[0] = ddrDataBeat_0;
  assign DdrBeatSpec_out1[1] = ddrDataBeat_1;
  assign DdrBeatSpec_out1[2] = ddrDataBeat_2;
  assign DdrBeatSpec_out1[3] = ddrDataBeat_3;
  assign DdrBeatSpec_out1[4] = ddrDataBeat_4;
  assign DdrBeatSpec_out1[5] = ddrDataBeat_5;
  assign DdrBeatSpec_out1[6] = ddrDataBeat_6;
  assign DdrBeatSpec_out1[7] = ddrDataBeat_7;
  always @(posedge clk or posedge reset)
    begin : delayMatch5_process
      if (reset == 1'b1) begin
        for(delayMatch5_t_1_0 = 32'sd0; delayMatch5_t_1_0 <= 32'sd327; delayMatch5_t_1_0 = delayMatch5_t_1_0 + 32'sd1) begin
          delayMatch5_reg[delayMatch5_t_1_0] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch5_t_0_1 = 32'sd0; delayMatch5_t_0_1 <= 32'sd327; delayMatch5_t_0_1 = delayMatch5_t_0_1 + 32'sd1) begin
            delayMatch5_reg[delayMatch5_t_0_1] <= delayMatch5_reg_next[delayMatch5_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(delayMatch5_t_0_0 = 32'sd0; delayMatch5_t_0_0 <= 32'sd7; delayMatch5_t_0_0 = delayMatch5_t_0_0 + 32'sd1) begin
      DdrBeatSpec_out1_1[delayMatch5_t_0_0] = delayMatch5_reg[32'sd320 + delayMatch5_t_0_0];
      delayMatch5_reg_next[delayMatch5_t_0_0] = DdrBeatSpec_out1[delayMatch5_t_0_0];
    end
    for(delayMatch5_t_1 = 32'sd0; delayMatch5_t_1 <= 32'sd319; delayMatch5_t_1 = delayMatch5_t_1 + 32'sd1) begin
      delayMatch5_reg_next[delayMatch5_t_1 + 32'sd8] = delayMatch5_reg[delayMatch5_t_1];
    end

  end

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg <= {41{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= ddrDataValid;
          delayMatch1_reg[32'sd40:32'sd1] <= delayMatch1_reg[32'sd39:32'sd0];
        end
      end
    end

  assign ddrDataValid_1 = delayMatch1_reg[40];

  SquareBeat u_SquareBeat (.clk(clk),
                           .reset(reset),
                           .enb(clk_enable),
                           .ddrDataBeat_0(ddrDataBeat_0),  // single
                           .ddrDataBeat_1(ddrDataBeat_1),  // single
                           .ddrDataBeat_2(ddrDataBeat_2),  // single
                           .ddrDataBeat_3(ddrDataBeat_3),  // single
                           .ddrDataBeat_4(ddrDataBeat_4),  // single
                           .ddrDataBeat_5(ddrDataBeat_5),  // single
                           .ddrDataBeat_6(ddrDataBeat_6),  // single
                           .ddrDataBeat_7(ddrDataBeat_7),  // single
                           .squaredBeat_0(SquareBeat_squaredBeat_0),  // single
                           .squaredBeat_1(SquareBeat_squaredBeat_1),  // single
                           .squaredBeat_2(SquareBeat_squaredBeat_2),  // single
                           .squaredBeat_3(SquareBeat_squaredBeat_3),  // single
                           .squaredBeat_4(SquareBeat_squaredBeat_4),  // single
                           .squaredBeat_5(SquareBeat_squaredBeat_5),  // single
                           .squaredBeat_6(SquareBeat_squaredBeat_6),  // single
                           .squaredBeat_7(SquareBeat_squaredBeat_7)  // single
                           );
  BeatReduce u_BeatReduce (.clk(clk),
                           .reset(reset),
                           .enb(clk_enable),
                           .squaredBeat_0(SquareBeat_squaredBeat_0),  // single
                           .squaredBeat_1(SquareBeat_squaredBeat_1),  // single
                           .squaredBeat_2(SquareBeat_squaredBeat_2),  // single
                           .squaredBeat_3(SquareBeat_squaredBeat_3),  // single
                           .squaredBeat_4(SquareBeat_squaredBeat_4),  // single
                           .squaredBeat_5(SquareBeat_squaredBeat_5),  // single
                           .squaredBeat_6(SquareBeat_squaredBeat_6),  // single
                           .squaredBeat_7(SquareBeat_squaredBeat_7),  // single
                           .beatSum(BeatReduce_beatSum)  // single
                           );
  always @(posedge clk or posedge reset)
    begin : CaptureClearDelay_process
      if (reset == 1'b1) begin
        CaptureClearDelay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          CaptureClearDelay_out1 <= captureInvRms;
        end
      end
    end
  assign ClearAccumulator_out1 = reset_2 | CaptureClearDelay_out1;
  BeatAccumulator u_BeatAccumulator (.clk(clk),
                                     .reset(reset),
                                     .enb(clk_enable),
                                     .beatSum(BeatReduce_beatSum),  // single
                                     .accumulate(ddrDataValid_1),
                                     .clear(ClearAccumulator_out1),
                                     .currentSum(BeatAccumulator_currentSum)  // single
                                     );
  Controller u_Controller (.clk(clk),
                           .reset(reset),
                           .enb(clk_enable),
                           .reset_1(reset_2),
                           .start(start_1),
                           .cfgGammaBeat_0(CfgBeatSpec_out1_1[0]),  // single
                           .cfgGammaBeat_1(CfgBeatSpec_out1_1[1]),  // single
                           .cfgGammaBeat_2(CfgBeatSpec_out1_1[2]),  // single
                           .cfgGammaBeat_3(CfgBeatSpec_out1_1[3]),  // single
                           .cfgGammaBeat_4(CfgBeatSpec_out1_1[4]),  // single
                           .cfgGammaBeat_5(CfgBeatSpec_out1_1[5]),  // single
                           .cfgGammaBeat_6(CfgBeatSpec_out1_1[6]),  // single
                           .cfgGammaBeat_7(CfgBeatSpec_out1_1[7]),  // single
                           .cfgGammaValid(cfgGammaValid_1),
                           .ddrDataBeat_0(DdrBeatSpec_out1_1[0]),  // single
                           .ddrDataBeat_1(DdrBeatSpec_out1_1[1]),  // single
                           .ddrDataBeat_2(DdrBeatSpec_out1_1[2]),  // single
                           .ddrDataBeat_3(DdrBeatSpec_out1_1[3]),  // single
                           .ddrDataBeat_4(DdrBeatSpec_out1_1[4]),  // single
                           .ddrDataBeat_5(DdrBeatSpec_out1_1[5]),  // single
                           .ddrDataBeat_6(DdrBeatSpec_out1_1[6]),  // single
                           .ddrDataBeat_7(DdrBeatSpec_out1_1[7]),  // single
                           .ddrDataValid(ddrDataValid_1),
                           .currentSumIn(BeatAccumulator_currentSum),  // single
                           .rsqrtOperand(rsqrtOperand),  // single
                           .xBeatOut_0(xBeatOut_0),  // single
                           .xBeatOut_1(xBeatOut_1),  // single
                           .xBeatOut_2(xBeatOut_2),  // single
                           .xBeatOut_3(xBeatOut_3),  // single
                           .xBeatOut_4(xBeatOut_4),  // single
                           .xBeatOut_5(xBeatOut_5),  // single
                           .xBeatOut_6(xBeatOut_6),  // single
                           .xBeatOut_7(xBeatOut_7),  // single
                           .gBeatOut_0(gBeatOut_0),  // single
                           .gBeatOut_1(gBeatOut_1),  // single
                           .gBeatOut_2(gBeatOut_2),  // single
                           .gBeatOut_3(gBeatOut_3),  // single
                           .gBeatOut_4(gBeatOut_4),  // single
                           .gBeatOut_5(gBeatOut_5),  // single
                           .gBeatOut_6(gBeatOut_6),  // single
                           .gBeatOut_7(gBeatOut_7),  // single
                           .captureInvRms(captureInvRms),
                           .outValid(outValid_1),
                           .ddrReadAddr(ddrReadAddr_1),  // uint16
                           .ddrReadEn(ddrReadEn_1),
                           .done(done_1),
                           .busy(busy_1)
                           );
  ScalarRsqrt u_ScalarRsqrt (.clk(clk),
                             .reset(reset),
                             .enb(clk_enable),
                             .rsqrtOperand(rsqrtOperand),  // single
                             .invRms(InvRmsDelay_out1)  // single
                             );
  InvRmsLatch u_InvRmsLatch (.clk(clk),
                             .reset(reset),
                             .enb(clk_enable),
                             .invRmsIn(InvRmsDelay_out1),  // single
                             .capture(captureInvRms),
                             .invRmsLatched(InvRmsLatch_invRmsLatched)  // single
                             );
  LaneMultiply u_LaneMultiply (.clk(clk),
                               .reset(reset),
                               .enb(clk_enable),
                               .xBeat_0(xBeatOut_0),  // single
                               .xBeat_1(xBeatOut_1),  // single
                               .xBeat_2(xBeatOut_2),  // single
                               .xBeat_3(xBeatOut_3),  // single
                               .xBeat_4(xBeatOut_4),  // single
                               .xBeat_5(xBeatOut_5),  // single
                               .xBeat_6(xBeatOut_6),  // single
                               .xBeat_7(xBeatOut_7),  // single
                               .gBeat_0(gBeatOut_0),  // single
                               .gBeat_1(gBeatOut_1),  // single
                               .gBeat_2(gBeatOut_2),  // single
                               .gBeat_3(gBeatOut_3),  // single
                               .gBeat_4(gBeatOut_4),  // single
                               .gBeat_5(gBeatOut_5),  // single
                               .gBeat_6(gBeatOut_6),  // single
                               .gBeat_7(gBeatOut_7),  // single
                               .invRms(InvRmsLatch_invRmsLatched),  // single
                               .yBeat_0(LaneMultiply_yBeat_0),  // single
                               .yBeat_1(LaneMultiply_yBeat_1),  // single
                               .yBeat_2(LaneMultiply_yBeat_2),  // single
                               .yBeat_3(LaneMultiply_yBeat_3),  // single
                               .yBeat_4(LaneMultiply_yBeat_4),  // single
                               .yBeat_5(LaneMultiply_yBeat_5),  // single
                               .yBeat_6(LaneMultiply_yBeat_6),  // single
                               .yBeat_7(LaneMultiply_yBeat_7)  // single
                               );
  assign outBeat_0 = LaneMultiply_yBeat_0;

  assign outBeat_1 = LaneMultiply_yBeat_1;

  assign outBeat_2 = LaneMultiply_yBeat_2;

  assign outBeat_3 = LaneMultiply_yBeat_3;

  assign outBeat_4 = LaneMultiply_yBeat_4;

  assign outBeat_5 = LaneMultiply_yBeat_5;

  assign outBeat_6 = LaneMultiply_yBeat_6;

  assign outBeat_7 = LaneMultiply_yBeat_7;

  always @(posedge clk or posedge reset)
    begin : delayMatch6_process
      if (reset == 1'b1) begin
        delayMatch6_reg <= {148{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch6_reg[0] <= outValid_1;
          delayMatch6_reg[32'sd147:32'sd1] <= delayMatch6_reg[32'sd146:32'sd0];
        end
      end
    end

  assign outValid = delayMatch6_reg[147];

  always @(posedge clk or posedge reset)
    begin : delayMatch7_process
      if (reset == 1'b1) begin
        for(delayMatch7_t_1 = 32'sd0; delayMatch7_t_1 <= 32'sd147; delayMatch7_t_1 = delayMatch7_t_1 + 32'sd1) begin
          delayMatch7_reg[delayMatch7_t_1] <= 16'b0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch7_t_0_1 = 32'sd0; delayMatch7_t_0_1 <= 32'sd147; delayMatch7_t_0_1 = delayMatch7_t_0_1 + 32'sd1) begin
            delayMatch7_reg[delayMatch7_t_0_1] <= delayMatch7_reg_next[delayMatch7_t_0_1];
          end
        end
      end
    end

  always @* begin
    ddrReadAddr_2 = delayMatch7_reg[147];
    delayMatch7_reg_next[0] = ddrReadAddr_1;

    for(delayMatch7_t_0_0 = 32'sd0; delayMatch7_t_0_0 <= 32'sd146; delayMatch7_t_0_0 = delayMatch7_t_0_0 + 32'sd1) begin
      delayMatch7_reg_next[delayMatch7_t_0_0 + 32'sd1] = delayMatch7_reg[delayMatch7_t_0_0];
    end

  end

  always @(posedge clk or posedge reset)
    begin : delayMatch8_process
      if (reset == 1'b1) begin
        delayMatch8_reg <= {148{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch8_reg[0] <= ddrReadEn_1;
          delayMatch8_reg[32'sd147:32'sd1] <= delayMatch8_reg[32'sd146:32'sd0];
        end
      end
    end

  assign ddrReadEn = delayMatch8_reg[147];

  always @(posedge clk or posedge reset)
    begin : delayMatch9_process
      if (reset == 1'b1) begin
        delayMatch9_reg <= {148{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch9_reg[0] <= done_1;
          delayMatch9_reg[32'sd147:32'sd1] <= delayMatch9_reg[32'sd146:32'sd0];
        end
      end
    end

  assign done = delayMatch9_reg[147];

  always @(posedge clk or posedge reset)
    begin : delayMatch10_process
      if (reset == 1'b1) begin
        delayMatch10_reg <= {148{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch10_reg[0] <= busy_1;
          delayMatch10_reg[32'sd147:32'sd1] <= delayMatch10_reg[32'sd146:32'sd0];
        end
      end
    end

  assign busy = delayMatch10_reg[147];

  assign ce_out = clk_enable;

  assign ddrReadAddr = ddrReadAddr_2;

endmodule  // DUT

