vlib work
vmap -c
vlog  DUTPacked_pkg.sv
vlog  Unpack.sv
vlog  nfp_wire_single.sv
vlog  CfgBeatUnpack.sv
vlog  nfp_add_single.sv
vlog  BeatReduce.sv
vlog  nfp_mul_single.sv
vlog  LaneMultiply.sv
vlog  SquareBeat.sv
vlog  Controller.sv
vlog  BeatAccumulator.sv
vlog  nfp_sqrt_single.sv
vlog  nfp_div_single.sv
vlog  ScalarRsqrt.sv
vlog  InvRmsLatch.sv
vlog  CoreDUT.sv
vlog  Pack.sv
vlog  nfp_wire_single_block.sv
vlog  OutBeatPack.sv
vlog  DUTPacked.sv
