// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/DUTPacked_pkg.sv
// Created: 2026-03-20 16:46:19
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------



package DUTPacked_pkg;
  typedef  logic  [31:0] vector_of_unsigned_logic_32;

  typedef  logic  [7:0] vector_of_unsigned_logic_8;
  typedef  logic signed [27:0] vector_of_signed_logic_28;
  typedef  logic  [26:0] vector_of_unsigned_logic_27;
  typedef  logic  [22:0] vector_of_unsigned_logic_23;

  typedef  logic  [47:0] vector_of_unsigned_logic_48;
  typedef  logic signed [9:0] vector_of_signed_logic_10;

  typedef  logic  [15:0] vector_of_unsigned_logic_16;
endpackage: DUTPacked_pkg

