// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/DUTPacked.sv
// Created: 2026-03-20 16:46:19
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// outBeat                       ce_out        1
// outValid                      ce_out        1
// ddrReadAddr                   ce_out        1
// ddrReadEn                     ce_out        1
// done                          ce_out        1
// busy                          ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: DUTPacked
// Source Path: rmsNormalization/DUTPacked
// Hierarchy Level: 0
// Model version: 1.1
// 
// Simulink model description for rmsNormalization:
// 
// RMSNorm packed RTL v3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DUTPacked
          (  input logic clk,
             input logic reset,
             input logic clk_enable,
             input logic start,
             input logic [255:0] cfgGammaBeat  /* ufix256 */,
             input logic cfgGammaValid,
             input logic [255:0] ddrDataBeat  /* ufix256 */,
             input logic ddrDataValid,
             output logic ce_out,
             output logic [255:0] outBeat  /* ufix256 */,
             output logic outValid,
             output logic [15:0] ddrReadAddr  /* uint16 */,
             output logic ddrReadEn,
             output logic done,
             output logic busy);


  logic [31:0] CfgBeatUnpack_beat [0:7];  /* ufix32 [8] */
  logic [31:0] DdrBeatUnpack_beat [0:7];  /* ufix32 [8] */
  logic [31:0] CoreDUT_outBeat [0:7];  /* ufix32 [8] */
  logic CoreDUT_outValid;
  logic [15:0] CoreDUT_ddrReadAddr;  /* uint16 */
  logic CoreDUT_ddrReadEn;
  logic CoreDUT_done;
  logic CoreDUT_busy;
  logic [255:0] OutBeatPack_packedBeat;  /* ufix256 */
  logic [255:0] packedBeat;  /* ufix256 */


  CfgBeatUnpack u_CfgBeatUnpack (.packedBeat(cfgGammaBeat),  /* ufix256 */
                                 .beat(CfgBeatUnpack_beat)  /* single [8] */
                                 );

  CfgBeatUnpack u_DdrBeatUnpack (.packedBeat(ddrDataBeat),  /* ufix256 */
                                 .beat(DdrBeatUnpack_beat)  /* single [8] */
                                 );

  CoreDUT u_CoreDUT (.clk(clk),
                     .reset(reset),
                     .enb(clk_enable),
                     .start(start),
                     .cfgGammaBeat(CfgBeatUnpack_beat),  /* single [8] */
                     .cfgGammaValid(cfgGammaValid),
                     .ddrDataBeat(DdrBeatUnpack_beat),  /* single [8] */
                     .ddrDataValid(ddrDataValid),
                     .outBeat(CoreDUT_outBeat),  /* single [8] */
                     .outValid(CoreDUT_outValid),
                     .ddrReadAddr(CoreDUT_ddrReadAddr),  /* uint16 */
                     .ddrReadEn(CoreDUT_ddrReadEn),
                     .done(CoreDUT_done),
                     .busy(CoreDUT_busy)
                     );

  OutBeatPack u_OutBeatPack (.beat(CoreDUT_outBeat),  /* single [8] */
                             .packedBeat(OutBeatPack_packedBeat)  /* ufix256 */
                             );

  assign packedBeat = OutBeatPack_packedBeat;

  assign outBeat = packedBeat;

  assign outValid = CoreDUT_outValid;

  assign ddrReadAddr = CoreDUT_ddrReadAddr;

  assign ddrReadEn = CoreDUT_ddrReadEn;

  assign done = CoreDUT_done;

  assign busy = CoreDUT_busy;

  assign ce_out = clk_enable;

endmodule  // DUTPacked

