// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/InvRmsLatch.v
// Created: 2026-03-18 09:48:18
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: InvRmsLatch
// Source Path: rmsNormalization/DUT/InvRmsLatch
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module InvRmsLatch
          (clk,
           reset,
           enb,
           invRmsIn,
           capture,
           invRmsLatched);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] invRmsIn;  // single
  input   capture;
  output  [31:0] invRmsLatched;  // single


  wire stateControl_1;
  reg  [180:0] delayMatch1_reg;  // ufix1 [181]
  wire stateControl_2;
  reg  [139:0] delayMatch_reg;  // ufix1 [140]
  wire capture_1;
  reg [31:0] StoredInvRms_out1;  // ufix32
  wire [31:0] SelectNew_out1;  // ufix32
  wire [31:0] SelectNew_out1_1;  // ufix32


  assign stateControl_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg <= {181{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= stateControl_1;
          delayMatch1_reg[32'sd180:32'sd1] <= delayMatch1_reg[32'sd179:32'sd0];
        end
      end
    end

  assign stateControl_2 = delayMatch1_reg[180];

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {140{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= capture;
          delayMatch_reg[32'sd139:32'sd1] <= delayMatch_reg[32'sd138:32'sd0];
        end
      end
    end

  assign capture_1 = delayMatch_reg[139];

  assign SelectNew_out1 = (capture_1 == 1'b0 ? StoredInvRms_out1 :
              invRmsIn);
  assign SelectNew_out1_1 = (stateControl_2 == 1'b0 ? StoredInvRms_out1 :
              SelectNew_out1);

  always @(posedge clk or posedge reset)
    begin : StoredInvRms_process
      if (reset == 1'b1) begin
        StoredInvRms_out1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          StoredInvRms_out1 <= SelectNew_out1_1;
        end
      end
    end
  assign invRmsLatched = StoredInvRms_out1;

endmodule  // InvRmsLatch

