// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/InvRmsLatch.sv
// Created: 2026-03-19 12:47:24
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: InvRmsLatch
// Source Path: rmsNormalization/DUTPacked/CoreDUT/InvRmsLatch
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module InvRmsLatch
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] invRmsIn  /* single */,
             input logic invRmsInValid,
             input logic capture,
             input logic reset_1,
             output logic [31:0] invRmsLatched  /* single */,
             output logic invRmsLatchedValid,
             output logic clearAccumulator);


  logic CaptureAccepted_out1;
  logic [31:0] ZeroSingle_out1;  /* ufix32 */
  logic [31:0] StoredInvRms_out1;  /* ufix32 */
  logic [31:0] SelectNew_out1;  /* ufix32 */
  logic [31:0] ResetStored_out1;  /* ufix32 */
  logic FalseConst_out1;
  logic LatchedValidState_out1;
  logic HoldValid_out1;
  logic ResetValid_out1;
  logic CaptureAcceptedDelay_out1;


  assign CaptureAccepted_out1 = capture & invRmsInValid;

  assign ZeroSingle_out1 = 32'h00000000;

  assign SelectNew_out1 = (CaptureAccepted_out1 == 1'b0 ? StoredInvRms_out1 :
              invRmsIn);

  assign ResetStored_out1 = (reset_1 == 1'b0 ? SelectNew_out1 :
              ZeroSingle_out1);

  always_ff @(posedge clk or posedge reset)
    begin : StoredInvRms_process
      if (reset == 1'b1) begin
        StoredInvRms_out1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          StoredInvRms_out1 <= ResetStored_out1;
        end
      end
    end

  assign invRmsLatched = StoredInvRms_out1;

  assign FalseConst_out1 = 1'b0;

  assign HoldValid_out1 = CaptureAccepted_out1 | LatchedValidState_out1;

  assign ResetValid_out1 = (reset_1 == 1'b0 ? HoldValid_out1 :
              FalseConst_out1);

  always_ff @(posedge clk or posedge reset)
    begin : LatchedValidState_process
      if (reset == 1'b1) begin
        LatchedValidState_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          LatchedValidState_out1 <= ResetValid_out1;
        end
      end
    end

  assign invRmsLatchedValid = LatchedValidState_out1;

  always_ff @(posedge clk or posedge reset)
    begin : CaptureAcceptedDelay_process
      if (reset == 1'b1) begin
        CaptureAcceptedDelay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          CaptureAcceptedDelay_out1 <= CaptureAccepted_out1;
        end
      end
    end

  assign clearAccumulator = CaptureAcceptedDelay_out1;

endmodule  // InvRmsLatch

