// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/InvRmsLatch0.sv
// Created: 2026-03-20 16:46:18
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: InvRmsLatch0
// Source Path: rmsNormalization/DUTPacked/CoreDUT/InvRmsLatch0
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module InvRmsLatch0
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] invRmsIn  /* single */,
             input logic invRmsInValid,
             input logic capture,
             output logic [31:0] invRmsLatched  /* single */,
             output logic invRmsLatchedValid,
             output logic clearAccumulator);


  logic CaptureAccepted_out1;
  logic [31:0] StoredInvRms_out1;  /* ufix32 */
  logic [31:0] SelectNew_out1;  /* ufix32 */
  logic LatchedValidState_out1;
  logic HoldValid_out1;
  logic CaptureAcceptedDelay_out1;


  assign CaptureAccepted_out1 = capture & invRmsInValid;

  assign SelectNew_out1 = (CaptureAccepted_out1 == 1'b0 ? StoredInvRms_out1 :
              invRmsIn);

  always_ff @(posedge clk or posedge reset)
    begin : StoredInvRms_process
      if (reset == 1'b1) begin
        StoredInvRms_out1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          StoredInvRms_out1 <= SelectNew_out1;
        end
      end
    end

  assign invRmsLatched = StoredInvRms_out1;

  assign HoldValid_out1 = CaptureAccepted_out1 | LatchedValidState_out1;

  always_ff @(posedge clk or posedge reset)
    begin : LatchedValidState_process
      if (reset == 1'b1) begin
        LatchedValidState_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          LatchedValidState_out1 <= HoldValid_out1;
        end
      end
    end

  assign invRmsLatchedValid = LatchedValidState_out1;

  always_ff @(posedge clk or posedge reset)
    begin : CaptureAcceptedDelay_process
      if (reset == 1'b1) begin
        CaptureAcceptedDelay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          CaptureAcceptedDelay_out1 <= CaptureAccepted_out1;
        end
      end
    end

  assign clearAccumulator = CaptureAcceptedDelay_out1;

endmodule  // InvRmsLatch0

