// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/LaneMultiply.sv
// Created: 2026-03-19 12:47:24
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: LaneMultiply
// Source Path: rmsNormalization/DUTPacked/CoreDUT/LaneMultiply
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LaneMultiply
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] xBeat[0:7]  /* single [8] */,
             input logic xBeatValid,
             input logic [31:0] gBeat[0:7]  /* single [8] */,
             input logic gBeatValid,
             input logic [31:0] invRms  /* single */,
             input logic invRmsValid,
             output logic [31:0] yBeat[0:7]  /* single [8] */,
             output logic yBeatValid);


  logic [31:0] delayMatch_reg [0:63];  /* ufix32 [64] */
  logic [31:0] xBeat_1 [0:7];  /* ufix32 [8] */
  logic [31:0] kconst;  /* ufix32 */
  logic [31:0] nfp_out_1_1;  /* ufix32 */
  logic [31:0] nfp_out_1_1_1;  /* ufix32 */
  logic [31:0] reduced_reg [0:15];  /* ufix32 [16] */
  logic [31:0] InvRmsScalar_out1;  /* ufix32 */
  logic [31:0] nfp_out_1_1_2;  /* ufix32 */
  logic [31:0] nfp_out_2_1;  /* ufix32 */
  logic [31:0] nfp_out_2_1_1;  /* ufix32 */
  logic [31:0] nfp_out_2_1_2;  /* ufix32 */
  logic [31:0] nfp_out_3_1;  /* ufix32 */
  logic [31:0] nfp_out_3_1_1;  /* ufix32 */
  logic [31:0] nfp_out_3_1_2;  /* ufix32 */
  logic [31:0] nfp_out_4_1;  /* ufix32 */
  logic [31:0] nfp_out_4_1_1;  /* ufix32 */
  logic [31:0] nfp_out_4_1_2;  /* ufix32 */
  logic [31:0] nfp_out_5_1;  /* ufix32 */
  logic [31:0] nfp_out_5_1_1;  /* ufix32 */
  logic [31:0] nfp_out_5_1_2;  /* ufix32 */
  logic [31:0] nfp_out_6_1;  /* ufix32 */
  logic [31:0] nfp_out_6_1_1;  /* ufix32 */
  logic [31:0] nfp_out_6_1_2;  /* ufix32 */
  logic [31:0] nfp_out_7_1;  /* ufix32 */
  logic [31:0] nfp_out_7_1_1;  /* ufix32 */
  logic [31:0] nfp_out_7_1_2;  /* ufix32 */
  logic [31:0] nfp_out_8_1;  /* ufix32 */
  logic [31:0] nfp_out_8_1_1;  /* ufix32 */
  logic [31:0] nfp_out_8_1_2;  /* ufix32 */
  logic [31:0] ScaleMultiply_out1 [0:7];  /* ufix32 [8] */
  logic InputBeatValid_out1;
  logic YBeatValid_out1;
  logic [23:0] delayMatch_reg_1;  /* ufix1 [24] */
  logic YBeatValid_out1_1;


  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= '{64{32'h00000000}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[32'sd0:32'sd7] <= xBeat[32'sd0:32'sd7];
          delayMatch_reg[32'sd8:32'sd63] <= delayMatch_reg[32'sd0:32'sd55];
        end
      end
    end

  assign xBeat_1[32'sd0:32'sd7] = delayMatch_reg[32'sd56:32'sd63];

  assign kconst = 32'h421cc471;

  nfp_mul_single u_nfp_mul_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(gBeat[0]),  /* single */
                                 .nfp_in2(kconst),  /* single */
                                 .nfp_out(nfp_out_1_1)  /* single */
                                 );

  nfp_mul_single u_nfp_mul_comp_1 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(xBeat_1[0]),  /* single */
                                   .nfp_in2(nfp_out_1_1),  /* single */
                                   .nfp_out(nfp_out_1_1_1)  /* single */
                                   );

  always_ff @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        reduced_reg <= '{16{32'h00000000}};
      end
      else begin
        if (enb) begin
          reduced_reg[0] <= invRms;
          reduced_reg[32'sd1:32'sd15] <= reduced_reg[32'sd0:32'sd14];
        end
      end
    end

  assign InvRmsScalar_out1 = reduced_reg[15];

  nfp_mul_single u_nfp_mul_comp_2 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(nfp_out_1_1_1),  /* single */
                                   .nfp_in2(InvRmsScalar_out1),  /* single */
                                   .nfp_out(nfp_out_1_1_2)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_3 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(gBeat[1]),  /* single */
                                   .nfp_in2(kconst),  /* single */
                                   .nfp_out(nfp_out_2_1)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_4 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(xBeat_1[1]),  /* single */
                                   .nfp_in2(nfp_out_2_1),  /* single */
                                   .nfp_out(nfp_out_2_1_1)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_5 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(nfp_out_2_1_1),  /* single */
                                   .nfp_in2(InvRmsScalar_out1),  /* single */
                                   .nfp_out(nfp_out_2_1_2)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_6 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(gBeat[2]),  /* single */
                                   .nfp_in2(kconst),  /* single */
                                   .nfp_out(nfp_out_3_1)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_7 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(xBeat_1[2]),  /* single */
                                   .nfp_in2(nfp_out_3_1),  /* single */
                                   .nfp_out(nfp_out_3_1_1)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_8 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(nfp_out_3_1_1),  /* single */
                                   .nfp_in2(InvRmsScalar_out1),  /* single */
                                   .nfp_out(nfp_out_3_1_2)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_9 (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in1(gBeat[3]),  /* single */
                                   .nfp_in2(kconst),  /* single */
                                   .nfp_out(nfp_out_4_1)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_10 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(xBeat_1[3]),  /* single */
                                    .nfp_in2(nfp_out_4_1),  /* single */
                                    .nfp_out(nfp_out_4_1_1)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_11 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(nfp_out_4_1_1),  /* single */
                                    .nfp_in2(InvRmsScalar_out1),  /* single */
                                    .nfp_out(nfp_out_4_1_2)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_12 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(gBeat[4]),  /* single */
                                    .nfp_in2(kconst),  /* single */
                                    .nfp_out(nfp_out_5_1)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_13 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(xBeat_1[4]),  /* single */
                                    .nfp_in2(nfp_out_5_1),  /* single */
                                    .nfp_out(nfp_out_5_1_1)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_14 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(nfp_out_5_1_1),  /* single */
                                    .nfp_in2(InvRmsScalar_out1),  /* single */
                                    .nfp_out(nfp_out_5_1_2)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_15 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(gBeat[5]),  /* single */
                                    .nfp_in2(kconst),  /* single */
                                    .nfp_out(nfp_out_6_1)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_16 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(xBeat_1[5]),  /* single */
                                    .nfp_in2(nfp_out_6_1),  /* single */
                                    .nfp_out(nfp_out_6_1_1)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_17 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(nfp_out_6_1_1),  /* single */
                                    .nfp_in2(InvRmsScalar_out1),  /* single */
                                    .nfp_out(nfp_out_6_1_2)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_18 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(gBeat[6]),  /* single */
                                    .nfp_in2(kconst),  /* single */
                                    .nfp_out(nfp_out_7_1)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_19 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(xBeat_1[6]),  /* single */
                                    .nfp_in2(nfp_out_7_1),  /* single */
                                    .nfp_out(nfp_out_7_1_1)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_20 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(nfp_out_7_1_1),  /* single */
                                    .nfp_in2(InvRmsScalar_out1),  /* single */
                                    .nfp_out(nfp_out_7_1_2)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_21 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(gBeat[7]),  /* single */
                                    .nfp_in2(kconst),  /* single */
                                    .nfp_out(nfp_out_8_1)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_22 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(xBeat_1[7]),  /* single */
                                    .nfp_in2(nfp_out_8_1),  /* single */
                                    .nfp_out(nfp_out_8_1_1)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_23 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .nfp_in1(nfp_out_8_1_1),  /* single */
                                    .nfp_in2(InvRmsScalar_out1),  /* single */
                                    .nfp_out(nfp_out_8_1_2)  /* single */
                                    );

  assign ScaleMultiply_out1[0] = nfp_out_1_1_2;
  assign ScaleMultiply_out1[1] = nfp_out_2_1_2;
  assign ScaleMultiply_out1[2] = nfp_out_3_1_2;
  assign ScaleMultiply_out1[3] = nfp_out_4_1_2;
  assign ScaleMultiply_out1[4] = nfp_out_5_1_2;
  assign ScaleMultiply_out1[5] = nfp_out_6_1_2;
  assign ScaleMultiply_out1[6] = nfp_out_7_1_2;
  assign ScaleMultiply_out1[7] = nfp_out_8_1_2;

  assign yBeat = ScaleMultiply_out1;

  assign InputBeatValid_out1 = xBeatValid & gBeatValid;

  assign YBeatValid_out1 = InputBeatValid_out1 & invRmsValid;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_1_process
      if (reset == 1'b1) begin
        delayMatch_reg_1 <= '{24{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_1[0] <= YBeatValid_out1;
          delayMatch_reg_1[32'sd23:32'sd1] <= delayMatch_reg_1[32'sd22:32'sd0];
        end
      end
    end

  assign YBeatValid_out1_1 = delayMatch_reg_1[23];

  assign yBeatValid = YBeatValid_out1_1;

endmodule  // LaneMultiply

