// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/nfp_abs_single.v
// Created: 2026-03-18 01:12:08
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: nfp_abs_single
// Source Path: rmsNormalization/DUT/InvRmsLatch/nfp_abs_single
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nfp_abs_single
          (nfp_in,
           nfp_out);


  input   [31:0] nfp_in;  // ufix32
  output  [31:0] nfp_out;  // ufix32


  wire Constant_out1;  // ufix1
  wire XS;  // ufix1
  wire [7:0] XE;  // ufix8
  wire [22:0] XM;  // ufix23
  wire [31:0] nfp_out_pack;  // ufix32


  assign Constant_out1 = 1'b0;

  // Split 32 bit word into FP sign, exponent, mantissa
  assign XS = nfp_in[31];
  assign XE = nfp_in[30:23];
  assign XM = nfp_in[22:0];

  // Combine FP sign, exponent, mantissa into 32 bit word
  assign nfp_out_pack = {Constant_out1, XE, XM};

  assign nfp_out = nfp_out_pack;

endmodule  // nfp_abs_single

