// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/nfp_convert_fix_16_En0_to_double.v
// Created: 2026-03-18 09:43:07
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: nfp_convert_fix_16_En0_to_double
// Source Path: rmsNormalization/DUT/Controller/nfp_convert_fix_16_En0_to_double
// Hierarchy Level: 2
// Model version: 1.1
// 
// {Latency Strategy = "Max"}
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nfp_convert_fix_16_En0_to_double
          (clk,
           reset,
           enb,
           nfp_in,
           nfp_out);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] nfp_in;  // uint16
  output  [63:0] nfp_out;  // ufix64


  wire Delay1_ctrl_const_out;  // ufix1
  reg  Delay1_ctrl_delay_out;  // ufix1
  wire Delay1_Initial_Val_out;  // ufix1
  wire Constant8_out1;  // ufix1
  wire Delay4_ctrl_const_out;  // ufix1
  reg  Delay4_ctrl_delay_out;  // ufix1
  wire Delay4_Initial_Val_out;  // ufix1
  wire [5:0] Constant7_out1;  // ufix6
  reg  Relational_Operator_out1;  // ufix1
  wire Delay4_out1;  // ufix1
  wire Logical_Operator_out1;  // ufix1
  wire [5:0] Add_out1;  // ufix6
  reg [5:0] Delay3_out1;  // ufix6
  wire [5:0] Add_1;  // ufix6
  wire Relational_Operator_out1_1;  // ufix1
  wire Delay1_out1;  // ufix1
  reg [15:0] Delay_PS_1_out1;  // ufix16
  wire CompareToZero1_out1;  // ufix1
  reg  [3:0] Delay5_PS_2_5_reg;  // ufix1 [4]
  wire Delay5_PS_2_5_out1;  // ufix1
  wire Constant3_out1;  // ufix1
  wire Compare_To_Zero_out1;  // ufix1
  wire Logical_Operator_out1_1;  // ufix1
  reg  [3:0] Delay4_PS_2_5_reg;  // ufix1 [4]
  wire Delay4_PS_2_5_out1;  // ufix1
  wire Constant2_out1;  // ufix1
  wire Switch3_out1;  // ufix1
  wire Constant4_out1;  // ufix1
  wire Switch4_out1;  // ufix1
  reg  Delay2_PS_6_out1;  // ufix1
  wire signed [16:0] Unary_Minus_in0;  // sfix17
  wire signed [16:0] Unary_Minus_1;  // sfix17
  wire [15:0] Unary_Minus_out1;  // ufix16
  wire [15:0] Switch_out1;  // ufix16
  reg [15:0] Data_Type_Conversion2_out1;  // ufix16
  wire [7:0] Bit_Slice1_out1;  // ufix8
  wire Bit_Slice16_out1;  // ufix1
  wire Bit_Slice15_out1;  // ufix1
  wire Logical_Operator5_out1;  // ufix1
  wire Bit_Slice14_out1;  // ufix1
  wire Bit_Slice13_out1;  // ufix1
  wire Logical_Operator7_out1;  // ufix1
  wire Logical_Operator6_out1;  // ufix1
  wire Bit_Slice12_out1;  // ufix1
  wire Bit_Slice11_out1;  // ufix1
  wire Logical_Operator4_out1;  // ufix1
  wire Bit_Slice10_out1;  // ufix1
  wire Bit_Slice9_out1;  // ufix1
  wire Logical_Operator14_out1;  // ufix1
  wire Logical_Operator13_out1;  // ufix1
  wire [7:0] Bit_Slice4_out1;  // ufix8
  wire Bit_Slice8_out1;  // ufix1
  wire Bit_Slice7_out1;  // ufix1
  wire Logical_Operator1_out1;  // ufix1
  wire Bit_Slice6_out1;  // ufix1
  wire Bit_Slice5_out1;  // ufix1
  wire Logical_Operator3_out1;  // ufix1
  wire Bit_Slice3_out1;  // ufix1
  wire Bit_Slice2_out1;  // ufix1
  wire Bit_Slice4_out1_1;  // ufix1
  wire [7:0] Constant_out1;  // ufix8
  wire Bit_Slice1_out1_1;  // ufix1
  wire [7:0] Constant1_out1;  // ufix8
  wire [7:0] Switch2_out1;  // ufix8
  wire Logical_Operator_out1_2;  // ufix1
  wire [7:0] Constant2_out1_1;  // ufix8
  wire [7:0] Switch1_out1;  // ufix8
  wire [7:0] Constant3_out1_1;  // ufix8
  wire [7:0] Constant4_out1_1;  // ufix8
  wire Logical_Operator2_out1;  // ufix1
  wire [7:0] Switch3_out1_1;  // ufix8
  wire [7:0] Switch4_out1_1;  // ufix8
  wire [7:0] Constant5_out1;  // ufix8
  wire [7:0] Constant6_out1;  // ufix8
  wire [7:0] Switch6_out1;  // ufix8
  wire [7:0] Constant7_out1_1;  // ufix8
  wire [7:0] Constant8_out1_1;  // ufix8
  wire [7:0] Switch8_out1;  // ufix8
  wire Logical_Operator12_out1;  // ufix1
  wire [7:0] Switch9_out1;  // ufix8
  wire [7:0] Switch10_out1;  // ufix8
  wire [7:0] Constant9_out1;  // ufix8
  wire [7:0] Constant10_out1;  // ufix8
  wire [7:0] Switch12_out1;  // ufix8
  wire [7:0] Constant11_out1;  // ufix8
  wire [7:0] Constant12_out1;  // ufix8
  wire [7:0] Switch15_out1;  // ufix8
  wire [7:0] Switch16_out1;  // ufix8
  wire [7:0] Constant13_out1;  // ufix8
  wire [7:0] Constant14_out1;  // ufix8
  wire [7:0] Switch18_out1;  // ufix8
  wire [7:0] Constant15_out1;  // ufix8
  wire [7:0] Constant16_out1;  // ufix8
  wire [7:0] Switch20_out1;  // ufix8
  wire [7:0] Switch21_out1;  // ufix8
  wire [7:0] Switch13_out1;  // ufix8
  wire [7:0] Switch_out1_1;  // ufix8
  reg [7:0] Delay1_PS_3_out1;  // ufix8
  reg [7:0] Delay1_PS_4_out1;  // ufix8
  wire [10:0] Constant_out1_1;  // ufix11
  wire [11:0] Subtract_add_temp;  // ufix12
  wire [11:0] Subtract_1;  // ufix12
  wire [11:0] Subtract_2;  // ufix12
  wire signed [11:0] Subtract_out1;  // sfix12
  wire [10:0] Data_Type_Conversion_out1;  // ufix11
  reg [10:0] Delay3_PS_5_out1;  // ufix11
  wire [10:0] Constant_out1_2;  // ufix11
  wire [10:0] Switch1_out1_1;  // ufix11
  wire [10:0] Constant5_out1_1;  // ufix11
  wire [10:0] Switch5_out1;  // ufix11
  reg [10:0] Delay1_PS_6_out1;  // ufix11
  wire [7:0] Constant_out1_3;  // ufix8
  wire signed [8:0] Subtract_4;  // sfix9
  wire signed [8:0] Subtract_5;  // sfix9
  wire signed [8:0] Subtract_out1_1;  // sfix9
  reg signed [8:0] Delay1_PS_4_out1_1;  // sfix9
  wire signed [8:0] shift_arithmetic_zerosig;  // sfix9
  wire signed [8:0] shift_arithmetic_selsig;  // sfix9
  reg [15:0] reduced_reg [0:1];  // ufix16 [2]
  wire [15:0] reduced_reg_next [0:1];  // ufix16 [2]
  wire [15:0] Data_Type_Conversion2_out1_1;  // ufix16
  wire signed [8:0] shift_arithmetic_zerosig_1;  // sfix9
  wire signed [8:0] shift_arithmetic_selsig_1;  // sfix9
  wire signed [15:0] shift_arithmetic_1;  // int16
  wire [15:0] Shift_Arithmetic_out1;  // ufix16
  reg [15:0] Delay3_PS_5_out1_1;  // ufix16
  wire [14:0] Bit_Slice1_out1_2;  // ufix15
  wire [36:0] Constant_out1_4;  // ufix37
  wire [51:0] Bit_Concat_out1;  // ufix52
  wire [51:0] Constant1_out1_1;  // ufix52
  wire [51:0] Switch2_out1_1;  // ufix52
  wire [51:0] Constant6_out1_1;  // ufix52
  wire [51:0] Switch6_out1_1;  // ufix52
  reg [51:0] Delay3_PS_6_out1;  // ufix52
  wire [63:0] nfp_out_pack;  // ufix64
  reg signed [31:0] reduced_t_0_0;  // int32
  reg signed [31:0] reduced_t_1;  // int32


  assign Delay1_ctrl_const_out = 1'b1;

  always @(posedge clk or posedge reset)
    begin : Delay1_ctrl_delay_process
      if (reset == 1'b1) begin
        Delay1_ctrl_delay_out <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_ctrl_delay_out <= Delay1_ctrl_const_out;
        end
      end
    end

  assign Delay1_Initial_Val_out = 1'b1;

  assign Constant8_out1 = 1'b1;

  assign Delay4_ctrl_const_out = 1'b1;

  always @(posedge clk or posedge reset)
    begin : Delay4_ctrl_delay_process
      if (reset == 1'b1) begin
        Delay4_ctrl_delay_out <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay4_ctrl_delay_out <= Delay4_ctrl_const_out;
        end
      end
    end

  assign Delay4_Initial_Val_out = 1'b1;

  assign Constant7_out1 = 6'b000100;

  assign Delay4_out1 = (Delay4_ctrl_delay_out == 1'b0 ? Delay4_Initial_Val_out :
              Relational_Operator_out1);

  assign Logical_Operator_out1 = Constant8_out1 & Delay4_out1;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 6'b000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Add_out1;
        end
      end
    end

  assign Add_1 = {5'b0, Logical_Operator_out1};
  assign Add_out1 = Delay3_out1 + Add_1;

  assign Relational_Operator_out1_1 = Add_out1 <= Constant7_out1;

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        Relational_Operator_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Relational_Operator_out1 <= Relational_Operator_out1_1;
        end
      end
    end

  assign Delay1_out1 = (Delay1_ctrl_delay_out == 1'b0 ? Delay1_Initial_Val_out :
              Relational_Operator_out1);

  always @(posedge clk or posedge reset)
    begin : Delay_PS_1_process
      if (reset == 1'b1) begin
        Delay_PS_1_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_PS_1_out1 <= nfp_in;
        end
      end
    end

  assign CompareToZero1_out1 = Delay_PS_1_out1 == 16'b0000000000000000;

  always @(posedge clk or posedge reset)
    begin : Delay5_PS_2_5_process
      if (reset == 1'b1) begin
        Delay5_PS_2_5_reg <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          Delay5_PS_2_5_reg[0] <= CompareToZero1_out1;
          Delay5_PS_2_5_reg[32'sd3:32'sd1] <= Delay5_PS_2_5_reg[32'sd2:32'sd0];
        end
      end
    end

  assign Delay5_PS_2_5_out1 = Delay5_PS_2_5_reg[3];

  assign Constant3_out1 = 1'b0;

  assign Compare_To_Zero_out1 = 1'b0;

  assign Logical_Operator_out1_1 = Constant3_out1 & Compare_To_Zero_out1;

  always @(posedge clk or posedge reset)
    begin : Delay4_PS_2_5_process
      if (reset == 1'b1) begin
        Delay4_PS_2_5_reg <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          Delay4_PS_2_5_reg[0] <= Logical_Operator_out1_1;
          Delay4_PS_2_5_reg[32'sd3:32'sd1] <= Delay4_PS_2_5_reg[32'sd2:32'sd0];
        end
      end
    end

  assign Delay4_PS_2_5_out1 = Delay4_PS_2_5_reg[3];

  assign Constant2_out1 = 1'b0;

  assign Switch3_out1 = (Delay5_PS_2_5_out1 == 1'b0 ? Delay4_PS_2_5_out1 :
              Constant2_out1);

  assign Constant4_out1 = 1'b0;

  assign Switch4_out1 = (Delay1_out1 == 1'b0 ? Switch3_out1 :
              Constant4_out1);

  always @(posedge clk or posedge reset)
    begin : Delay2_PS_6_process
      if (reset == 1'b1) begin
        Delay2_PS_6_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay2_PS_6_out1 <= Switch4_out1;
        end
      end
    end

  assign Unary_Minus_1 = {1'b0, Delay_PS_1_out1};
  assign Unary_Minus_in0 =  - (Unary_Minus_1);
  assign Unary_Minus_out1 = Unary_Minus_in0[15:0];

  assign Switch_out1 = (Logical_Operator_out1_1 == 1'b0 ? Delay_PS_1_out1 :
              Unary_Minus_out1);

  always @(posedge clk or posedge reset)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        Data_Type_Conversion2_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Data_Type_Conversion2_out1 <= Switch_out1;
        end
      end
    end

  assign Bit_Slice1_out1 = Data_Type_Conversion2_out1[15:8];

  assign Bit_Slice16_out1 = Bit_Slice1_out1[7];

  assign Bit_Slice15_out1 = Bit_Slice1_out1[6];

  assign Logical_Operator5_out1 = Bit_Slice16_out1 | Bit_Slice15_out1;

  assign Bit_Slice14_out1 = Bit_Slice1_out1[5];

  assign Bit_Slice13_out1 = Bit_Slice1_out1[4];

  assign Logical_Operator7_out1 = Bit_Slice14_out1 | Bit_Slice13_out1;

  assign Logical_Operator6_out1 = Logical_Operator5_out1 | Logical_Operator7_out1;

  assign Bit_Slice12_out1 = Bit_Slice1_out1[3];

  assign Bit_Slice11_out1 = Bit_Slice1_out1[2];

  assign Logical_Operator4_out1 = Bit_Slice12_out1 | Bit_Slice11_out1;

  assign Bit_Slice10_out1 = Bit_Slice1_out1[1];

  assign Bit_Slice9_out1 = Bit_Slice1_out1[0];

  assign Logical_Operator14_out1 = Bit_Slice10_out1 | Bit_Slice9_out1;

  assign Logical_Operator13_out1 = Logical_Operator4_out1 | Logical_Operator14_out1;

  assign Bit_Slice4_out1 = Data_Type_Conversion2_out1[7:0];

  assign Bit_Slice8_out1 = Bit_Slice4_out1[7];

  assign Bit_Slice7_out1 = Bit_Slice4_out1[6];

  assign Logical_Operator1_out1 = Bit_Slice8_out1 | Bit_Slice7_out1;

  assign Bit_Slice6_out1 = Bit_Slice4_out1[5];

  assign Bit_Slice5_out1 = Bit_Slice4_out1[4];

  assign Logical_Operator3_out1 = Bit_Slice6_out1 | Bit_Slice5_out1;

  assign Bit_Slice3_out1 = Bit_Slice4_out1[3];

  assign Bit_Slice2_out1 = Bit_Slice4_out1[2];

  assign Bit_Slice4_out1_1 = Bit_Slice4_out1[0];

  assign Constant_out1 = 8'b00000000;

  assign Bit_Slice1_out1_1 = Bit_Slice4_out1[1];

  assign Constant1_out1 = 8'b00000001;

  assign Switch2_out1 = (Bit_Slice4_out1_1 == 1'b0 ? Constant_out1 :
              Constant1_out1);

  assign Logical_Operator_out1_2 = Bit_Slice3_out1 | Bit_Slice2_out1;

  assign Constant2_out1_1 = 8'b00000010;

  assign Switch1_out1 = (Bit_Slice1_out1_1 == 1'b0 ? Switch2_out1 :
              Constant2_out1_1);

  assign Constant3_out1_1 = 8'b00000011;

  assign Constant4_out1_1 = 8'b00000100;

  assign Logical_Operator2_out1 = Logical_Operator1_out1 | Logical_Operator3_out1;

  assign Switch3_out1_1 = (Bit_Slice3_out1 == 1'b0 ? Constant3_out1_1 :
              Constant4_out1_1);

  assign Switch4_out1_1 = (Logical_Operator_out1_2 == 1'b0 ? Switch1_out1 :
              Switch3_out1_1);

  assign Constant5_out1 = 8'b00000101;

  assign Constant6_out1 = 8'b00000110;

  assign Switch6_out1 = (Bit_Slice6_out1 == 1'b0 ? Constant5_out1 :
              Constant6_out1);

  assign Constant7_out1_1 = 8'b00000111;

  assign Constant8_out1_1 = 8'b00001000;

  assign Switch8_out1 = (Bit_Slice8_out1 == 1'b0 ? Constant7_out1_1 :
              Constant8_out1_1);

  assign Logical_Operator12_out1 = Logical_Operator6_out1 | Logical_Operator13_out1;

  assign Switch9_out1 = (Logical_Operator1_out1 == 1'b0 ? Switch6_out1 :
              Switch8_out1);

  assign Switch10_out1 = (Logical_Operator2_out1 == 1'b0 ? Switch4_out1_1 :
              Switch9_out1);

  assign Constant9_out1 = 8'b00001001;

  assign Constant10_out1 = 8'b00001010;

  assign Switch12_out1 = (Bit_Slice10_out1 == 1'b0 ? Constant9_out1 :
              Constant10_out1);

  assign Constant11_out1 = 8'b00001011;

  assign Constant12_out1 = 8'b00001100;

  assign Switch15_out1 = (Bit_Slice12_out1 == 1'b0 ? Constant11_out1 :
              Constant12_out1);

  assign Switch16_out1 = (Logical_Operator4_out1 == 1'b0 ? Switch12_out1 :
              Switch15_out1);

  assign Constant13_out1 = 8'b00001101;

  assign Constant14_out1 = 8'b00001110;

  assign Switch18_out1 = (Bit_Slice14_out1 == 1'b0 ? Constant13_out1 :
              Constant14_out1);

  assign Constant15_out1 = 8'b00001111;

  assign Constant16_out1 = 8'b00010000;

  assign Switch20_out1 = (Bit_Slice16_out1 == 1'b0 ? Constant15_out1 :
              Constant16_out1);

  assign Switch21_out1 = (Logical_Operator5_out1 == 1'b0 ? Switch18_out1 :
              Switch20_out1);

  assign Switch13_out1 = (Logical_Operator6_out1 == 1'b0 ? Switch16_out1 :
              Switch21_out1);

  assign Switch_out1_1 = (Logical_Operator12_out1 == 1'b0 ? Switch10_out1 :
              Switch13_out1);

  always @(posedge clk or posedge reset)
    begin : Delay1_PS_3_process
      if (reset == 1'b1) begin
        Delay1_PS_3_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay1_PS_3_out1 <= Switch_out1_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_PS_4_process
      if (reset == 1'b1) begin
        Delay1_PS_4_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay1_PS_4_out1 <= Delay1_PS_3_out1;
        end
      end
    end

  assign Constant_out1_1 = 11'b01111111110;

  assign Subtract_1 = {4'b0, Delay1_PS_4_out1};
  assign Subtract_2 = {1'b0, Constant_out1_1};
  assign Subtract_add_temp = Subtract_1 + Subtract_2;
  assign Subtract_out1 = Subtract_add_temp;

  assign Data_Type_Conversion_out1 = Subtract_out1[10:0];

  always @(posedge clk or posedge reset)
    begin : Delay3_PS_5_process
      if (reset == 1'b1) begin
        Delay3_PS_5_out1 <= 11'b00000000000;
      end
      else begin
        if (enb) begin
          Delay3_PS_5_out1 <= Data_Type_Conversion_out1;
        end
      end
    end

  assign Constant_out1_2 = 11'b00000000000;

  assign Switch1_out1_1 = (Delay5_PS_2_5_out1 == 1'b0 ? Delay3_PS_5_out1 :
              Constant_out1_2);

  assign Constant5_out1_1 = 11'b00000000000;

  assign Switch5_out1 = (Delay1_out1 == 1'b0 ? Switch1_out1_1 :
              Constant5_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay1_PS_6_process
      if (reset == 1'b1) begin
        Delay1_PS_6_out1 <= 11'b00000000000;
      end
      else begin
        if (enb) begin
          Delay1_PS_6_out1 <= Switch5_out1;
        end
      end
    end

  assign Constant_out1_3 = 8'b00010000;

  assign Subtract_4 = {1'b0, Constant_out1_3};
  assign Subtract_5 = {1'b0, Delay1_PS_3_out1};
  assign Subtract_out1_1 = Subtract_4 - Subtract_5;

  always @(posedge clk or posedge reset)
    begin : Delay1_PS_4_1_process
      if (reset == 1'b1) begin
        Delay1_PS_4_out1_1 <= 9'sb000000000;
      end
      else begin
        if (enb) begin
          Delay1_PS_4_out1_1 <= Subtract_out1_1;
        end
      end
    end

  assign shift_arithmetic_zerosig = 9'sb000000000;

  assign shift_arithmetic_selsig = (Delay1_PS_4_out1_1 >= shift_arithmetic_zerosig ? Delay1_PS_4_out1_1 :
              shift_arithmetic_zerosig);

  always @(posedge clk or posedge reset)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        for(reduced_t_1 = 32'sd0; reduced_t_1 <= 32'sd1; reduced_t_1 = reduced_t_1 + 32'sd1) begin
          reduced_reg[reduced_t_1] <= 16'b0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(reduced_t_0_0 = 32'sd0; reduced_t_0_0 <= 32'sd1; reduced_t_0_0 = reduced_t_0_0 + 32'sd1) begin
            reduced_reg[reduced_t_0_0] <= reduced_reg_next[reduced_t_0_0];
          end
        end
      end
    end

  assign Data_Type_Conversion2_out1_1 = reduced_reg[1];
  assign reduced_reg_next[0] = Data_Type_Conversion2_out1;
  assign reduced_reg_next[1] = reduced_reg[0];

  assign shift_arithmetic_zerosig_1 = 9'sb000000000;

  assign shift_arithmetic_selsig_1 = (shift_arithmetic_selsig >= shift_arithmetic_zerosig_1 ? shift_arithmetic_selsig :
              shift_arithmetic_zerosig_1);

  assign shift_arithmetic_1 = {{7{shift_arithmetic_selsig_1[8]}}, shift_arithmetic_selsig_1};
  assign Shift_Arithmetic_out1 = Data_Type_Conversion2_out1_1 <<< shift_arithmetic_1;

  always @(posedge clk or posedge reset)
    begin : Delay3_PS_5_1_process
      if (reset == 1'b1) begin
        Delay3_PS_5_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_PS_5_out1_1 <= Shift_Arithmetic_out1;
        end
      end
    end

  assign Bit_Slice1_out1_2 = Delay3_PS_5_out1_1[14:0];

  assign Constant_out1_4 = 37'h0000000000;

  assign Bit_Concat_out1 = {Bit_Slice1_out1_2, Constant_out1_4};

  assign Constant1_out1_1 = 52'h0000000000000;

  assign Switch2_out1_1 = (Delay5_PS_2_5_out1 == 1'b0 ? Bit_Concat_out1 :
              Constant1_out1_1);

  assign Constant6_out1_1 = 52'h0000000000000;

  assign Switch6_out1_1 = (Delay1_out1 == 1'b0 ? Switch2_out1_1 :
              Constant6_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay3_PS_6_process
      if (reset == 1'b1) begin
        Delay3_PS_6_out1 <= 52'h0000000000000;
      end
      else begin
        if (enb) begin
          Delay3_PS_6_out1 <= Switch6_out1_1;
        end
      end
    end

  // Combine FP sign, exponent, mantissa into 64 bit word
  assign nfp_out_pack = {Delay2_PS_6_out1, Delay1_PS_6_out1, Delay3_PS_6_out1};

  assign nfp_out = nfp_out_pack;

endmodule  // nfp_convert_fix_16_En0_to_double

