// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/OutBeatPack.sv
// Created: 2026-03-19 12:47:24
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: OutBeatPack
// Source Path: rmsNormalization/DUTPacked/OutBeatPack
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module OutBeatPack
          (  input logic [31:0] beat[0:7]  /* single [8] */,
             output logic [255:0] packedBeat  /* ufix256 */);


  vector_of_unsigned_logic_32 SingleToWords_out1 [0:7];  /* uint32 [8] */
  logic [255:0] packedBeat_1;  /* ufix256 */


  generate
    genvar k;
    for(k = 0; k < 8; k = k + 1) begin : u_nfp_wire_single_gen
      nfp_wire_single_block u_nfp_wire_single (.nfp_in(beat[k]),  /* ufix32 */
                                               .nfp_out(SingleToWords_out1[k])  /* ufix32 */
                                               );
    end
  endgenerate

  Pack u_Pack (.words(SingleToWords_out1),  /* uint32 [8] */
               .packedBeat(packedBeat_1)  /* ufix256 */
               );

  assign packedBeat = packedBeat_1;

endmodule  // OutBeatPack

