// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/Pack.sv
// Created: 2026-03-20 16:46:19
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Pack
// Source Path: rmsNormalization/DUTPacked/OutBeatPack/Pack
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Pack
          (  input vector_of_unsigned_logic_32 words[0:7]  /* uint32 [8] */,
             output logic [255:0] packedBeat  /* ufix256 */);


  logic [255:0] packedBeat_1;  /* ufix256 */
  vector_of_unsigned_logic_32 fivarargin [0:7];  /* ufix32 [8] */
  vector_of_unsigned_logic_32 Ci_1 [0:7];  /* uint32 [8] */
  logic signed [31:0] iter;  /* int32 */
  vector_of_unsigned_logic_32 oneCallIn [0:0];  /* uint32 [1] */
  vector_of_unsigned_logic_32 oneCallOut [0:0];  /* ufix32 [1] */


  always_comb begin
    Ci_1[0] = words[7];
    Ci_1[1] = words[6];
    Ci_1[2] = words[5];
    Ci_1[3] = words[4];
    Ci_1[4] = words[3];
    Ci_1[5] = words[2];
    Ci_1[6] = words[1];
    Ci_1[7] = words[0];

    for(iter = 32'sd0; iter <= 32'sd7; iter = iter + 32'sd1) begin
      oneCallIn[0] = Ci_1[iter];
      oneCallOut[0] = oneCallIn[0];
      fivarargin[iter] = oneCallOut[0];
    end

    packedBeat_1 = {fivarargin[0], fivarargin[1], fivarargin[2], fivarargin[3], fivarargin[4], fivarargin[5], fivarargin[6], fivarargin[7]};
  end

  assign packedBeat = packedBeat_1;

endmodule  // Pack

