// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/ScalarRsqrt.v
// Created: 2026-03-18 09:48:18
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ScalarRsqrt
// Source Path: rmsNormalization/DUT/ScalarRsqrt
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ScalarRsqrt
          (clk,
           reset,
           enb,
           rsqrtOperand,
           invRms);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] rsqrtOperand;  // single
  output  [31:0] invRms;  // single


  wire SqrtSingle_out1_timer;
  reg  [149:0] delayMatch_reg;  // ufix1 [150]
  wire SqrtSingle_out1_timer_1;
  wire [31:0] SqrtSingle_out1_default;  // ufix32
  wire [31:0] One_out1;  // ufix32
  wire [31:0] Sqrt_out1;  // ufix32
  wire [31:0] SqrtSingle_out1_zp;  // ufix32
  wire [31:0] Reciprocal_out1;  // ufix32


  assign SqrtSingle_out1_timer = 1'b1;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {150{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= SqrtSingle_out1_timer;
          delayMatch_reg[32'sd149:32'sd1] <= delayMatch_reg[32'sd148:32'sd0];
        end
      end
    end

  assign SqrtSingle_out1_timer_1 = delayMatch_reg[149];

  assign SqrtSingle_out1_default = 32'h3f800000;

  assign One_out1 = 32'h3f800000;
  nfp_sqrt_single u_nfp_sqrt_comp (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in(rsqrtOperand),  // single
                                   .nfp_out(Sqrt_out1)  // single
                                   );
  assign SqrtSingle_out1_zp = (SqrtSingle_out1_timer_1 == 1'b0 ? SqrtSingle_out1_default :
              Sqrt_out1);

  nfp_div_single u_nfp_div_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(One_out1),  // single
                                 .nfp_in2(SqrtSingle_out1_zp),  // single
                                 .nfp_out(Reciprocal_out1)  // single
                                 );
  assign invRms = Reciprocal_out1;

endmodule  // ScalarRsqrt

