// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/ScalarRsqrt.sv
// Created: 2026-03-19 12:47:24
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: ScalarRsqrt
// Source Path: rmsNormalization/DUTPacked/CoreDUT/ScalarRsqrt
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ScalarRsqrt
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] currentSum  /* single */,
             input logic currentSumValid,
             output logic [31:0] invRms  /* single */,
             output logic invRmsValid);


  logic SqrtSingle_out1_timer;
  logic [38:0] delayMatch_reg;  /* ufix1 [39] */
  logic SqrtSingle_out1_timer_1;
  logic [31:0] SqrtSingle_out1_default;  /* ufix32 */
  logic [31:0] Epsilon_out1;  /* ufix32 */
  logic [31:0] RsqrtOperandAdd_out1;  /* ufix32 */
  logic [31:0] One_out1;  /* ufix32 */
  logic [31:0] Sqrt_out1;  /* ufix32 */
  logic [31:0] SqrtSingle_out1_zp;  /* ufix32 */
  logic [31:0] Reciprocal_out1;  /* ufix32 */
  logic [70:0] delayMatch_reg_1;  /* ufix1 [71] */
  logic currentSumValid_1;


  assign SqrtSingle_out1_timer = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= '{39{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= SqrtSingle_out1_timer;
          delayMatch_reg[32'sd38:32'sd1] <= delayMatch_reg[32'sd37:32'sd0];
        end
      end
    end

  assign SqrtSingle_out1_timer_1 = delayMatch_reg[38];

  assign SqrtSingle_out1_default = 32'h3f800000;

  assign Epsilon_out1 = 32'h3ac9539c;

  nfp_add_single u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(currentSum),  /* single */
                                 .nfp_in2(Epsilon_out1),  /* single */
                                 .nfp_out(RsqrtOperandAdd_out1)  /* single */
                                 );

  assign One_out1 = 32'h3f800000;

  nfp_sqrt_single u_nfp_sqrt_comp (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .nfp_in(RsqrtOperandAdd_out1),  /* single */
                                   .nfp_out(Sqrt_out1)  /* single */
                                   );

  assign SqrtSingle_out1_zp = (SqrtSingle_out1_timer_1 == 1'b0 ? SqrtSingle_out1_default :
              Sqrt_out1);

  nfp_div_single u_nfp_div_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(One_out1),  /* single */
                                 .nfp_in2(SqrtSingle_out1_zp),  /* single */
                                 .nfp_out(Reciprocal_out1)  /* single */
                                 );

  assign invRms = Reciprocal_out1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_1_process
      if (reset == 1'b1) begin
        delayMatch_reg_1 <= '{71{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg_1[0] <= currentSumValid;
          delayMatch_reg_1[32'sd70:32'sd1] <= delayMatch_reg_1[32'sd69:32'sd0];
        end
      end
    end

  assign currentSumValid_1 = delayMatch_reg_1[70];

  assign invRmsValid = currentSumValid_1;

endmodule  // ScalarRsqrt

