// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/ScalarRsqrt.sv
// Created: 2026-03-20 10:42:02
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: ScalarRsqrt
// Source Path: rmsNormalization/DUTPacked/CoreDUT/ScalarRsqrt
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ScalarRsqrt
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] currentSum  /* single */,
             input logic currentSumValid,
             output logic [31:0] invRms  /* single */,
             output logic invRmsValid);


  logic [31:0] CurrentSumPipe_out1;  /* ufix32 */
  logic [31:0] Epsilon_out1;  /* ufix32 */
  logic [31:0] RsqrtOperandAdd_out1;  /* ufix32 */
  logic [31:0] ReciprocalSqrt_out1;  /* ufix32 */
  logic [2:0] InvRmsValidAlign_reg;  /* ufix1 [3] */
  logic InvRmsValidAlign_out1;
  logic [39:0] delayMatch_reg;  /* ufix1 [40] */
  logic InvRmsValidAlign_out1_1;


  always_ff @(posedge clk or posedge reset)
    begin : CurrentSumPipe_process
      if (reset == 1'b1) begin
        CurrentSumPipe_out1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          CurrentSumPipe_out1 <= currentSum;
        end
      end
    end

  assign Epsilon_out1 = 32'h3ac9539c;

  nfp_add_single u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(CurrentSumPipe_out1),  /* single */
                                 .nfp_in2(Epsilon_out1),  /* single */
                                 .nfp_out(RsqrtOperandAdd_out1)  /* single */
                                 );

  nfp_rsqrt_single u_nfp_rsqrt_comp (.clk(clk),
                                     .reset(reset),
                                     .enb(enb),
                                     .nfp_in(RsqrtOperandAdd_out1),  /* single */
                                     .nfp_out(ReciprocalSqrt_out1)  /* single */
                                     );

  assign invRms = ReciprocalSqrt_out1;

  always_ff @(posedge clk or posedge reset)
    begin : InvRmsValidAlign_process
      if (reset == 1'b1) begin
        InvRmsValidAlign_reg <= '{3{1'b0}};
      end
      else begin
        if (enb) begin
          InvRmsValidAlign_reg[0] <= currentSumValid;
          InvRmsValidAlign_reg[32'sd2:32'sd1] <= InvRmsValidAlign_reg[32'sd1:32'sd0];
        end
      end
    end

  assign InvRmsValidAlign_out1 = InvRmsValidAlign_reg[2];

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= '{40{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= InvRmsValidAlign_out1;
          delayMatch_reg[32'sd39:32'sd1] <= delayMatch_reg[32'sd38:32'sd0];
        end
      end
    end

  assign InvRmsValidAlign_out1_1 = delayMatch_reg[39];

  assign invRmsValid = InvRmsValidAlign_out1_1;

endmodule  // ScalarRsqrt

