// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/SquareBeat.v
// Created: 2026-03-18 09:48:18
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SquareBeat
// Source Path: rmsNormalization/DUT/SquareBeat
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SquareBeat
          (clk,
           reset,
           enb,
           ddrDataBeat_0,
           ddrDataBeat_1,
           ddrDataBeat_2,
           ddrDataBeat_3,
           ddrDataBeat_4,
           ddrDataBeat_5,
           ddrDataBeat_6,
           ddrDataBeat_7,
           squaredBeat_0,
           squaredBeat_1,
           squaredBeat_2,
           squaredBeat_3,
           squaredBeat_4,
           squaredBeat_5,
           squaredBeat_6,
           squaredBeat_7);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] ddrDataBeat_0;  // single
  input   [31:0] ddrDataBeat_1;  // single
  input   [31:0] ddrDataBeat_2;  // single
  input   [31:0] ddrDataBeat_3;  // single
  input   [31:0] ddrDataBeat_4;  // single
  input   [31:0] ddrDataBeat_5;  // single
  input   [31:0] ddrDataBeat_6;  // single
  input   [31:0] ddrDataBeat_7;  // single
  output  [31:0] squaredBeat_0;  // single
  output  [31:0] squaredBeat_1;  // single
  output  [31:0] squaredBeat_2;  // single
  output  [31:0] squaredBeat_3;  // single
  output  [31:0] squaredBeat_4;  // single
  output  [31:0] squaredBeat_5;  // single
  output  [31:0] squaredBeat_6;  // single
  output  [31:0] squaredBeat_7;  // single


  wire [31:0] ddrDataBeat [0:7];  // ufix32 [8]
  wire [31:0] Square_out1 [0:7];  // ufix32 [8]


  assign ddrDataBeat[0] = ddrDataBeat_0;
  assign ddrDataBeat[1] = ddrDataBeat_1;
  assign ddrDataBeat[2] = ddrDataBeat_2;
  assign ddrDataBeat[3] = ddrDataBeat_3;
  assign ddrDataBeat[4] = ddrDataBeat_4;
  assign ddrDataBeat[5] = ddrDataBeat_5;
  assign ddrDataBeat[6] = ddrDataBeat_6;
  assign ddrDataBeat[7] = ddrDataBeat_7;

  generate
    genvar k;
    for(k = 0; k < 8; k = k + 1) begin : u_nfp_mul_comp_gen
      nfp_mul_single u_nfp_mul_comp (.clk(clk),
                                     .reset(reset),
                                     .enb(enb),
                                     .nfp_in1(ddrDataBeat[k]),  // ufix32
                                     .nfp_in2(ddrDataBeat[k]),  // ufix32
                                     .nfp_out(Square_out1[k])  // ufix32
                                     );
    end
  endgenerate

  assign squaredBeat_0 = Square_out1[0];

  assign squaredBeat_1 = Square_out1[1];

  assign squaredBeat_2 = Square_out1[2];

  assign squaredBeat_3 = Square_out1[3];

  assign squaredBeat_4 = Square_out1[4];

  assign squaredBeat_5 = Square_out1[5];

  assign squaredBeat_6 = Square_out1[6];

  assign squaredBeat_7 = Square_out1[7];

endmodule  // SquareBeat

