// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/SquareBeat.sv
// Created: 2026-03-20 10:42:02
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: SquareBeat
// Source Path: rmsNormalization/DUTPacked/CoreDUT/SquareBeat
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SquareBeat
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] ddrDataBeat[0:7]  /* single [8] */,
             input logic ddrDataBeatValid,
             output logic [31:0] squaredBeat[0:7]  /* single [8] */,
             output logic squaredBeatValid);


  logic [31:0] Square_out1 [0:7];  /* ufix32 [8] */
  logic [7:0] delayMatch_reg;  /* ufix1 [8] */
  logic ddrDataBeatValid_1;


  generate
    genvar k;
    for(k = 0; k < 8; k = k + 1) begin : u_nfp_mul_comp_gen
      nfp_mul_single u_nfp_mul_comp (.clk(clk),
                                     .reset(reset),
                                     .enb(enb),
                                     .nfp_in1(ddrDataBeat[k]),  /* ufix32 */
                                     .nfp_in2(ddrDataBeat[k]),  /* ufix32 */
                                     .nfp_out(Square_out1[k])  /* ufix32 */
                                     );
    end
  endgenerate

  assign squaredBeat = Square_out1;

  always_ff @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= '{8{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= ddrDataBeatValid;
          delayMatch_reg[32'sd7:32'sd1] <= delayMatch_reg[32'sd6:32'sd0];
        end
      end
    end

  assign ddrDataBeatValid_1 = delayMatch_reg[7];

  assign squaredBeatValid = ddrDataBeatValid_1;

endmodule  // SquareBeat

