// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/SramCore.sv
// Created: 2026-03-20 16:46:18
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: SramCore
// Source Path: rmsNormalization/DUTPacked/CoreDUT/TokenSram/SramCore
// Hierarchy Level: 3
// Model version: 1.1
// 
// #codegen
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SramCore
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] writeBeat[0:7]  /* single [8] */,
             input logic [15:0] writeAddr  /* uint16 */,
             input logic writeBank,
             input logic writeValid,
             input logic [15:0] readAddr  /* uint16 */,
             input logic readBank,
             input logic readReq,
             output logic [31:0] readBeat[0:7]  /* single [8] */,
             output logic readValid);


  logic out0;
  logic [31:0] readBeat_1 [0:7];  /* ufix32 [8] */
  logic out0_1;
  logic out0_2;
  logic out0_3;
  logic out0_4;
  logic out0_5;
  logic out0_6;
  logic out0_7;
  logic out0_8;
  logic [15:0] baseIndex;  /* uint16 */
  logic [15:0] laneIndex;  /* uint16 */
  logic [16:0] adder_add_temp;  /* ufix17 */
  logic [16:0] adder_1;  /* ufix17 */
  logic [16:0] adder_2;  /* ufix17 */
  logic [15:0] out0_9;  /* uint16 */
  logic [15:0] const_expression;  /* uint16 */
  logic [16:0] adder_add_temp_1;  /* ufix17 */
  logic [16:0] adder_4;  /* ufix17 */
  logic [16:0] adder_5;  /* ufix17 */
  logic [15:0] out0_10;  /* uint16 */
  logic out0_11;
  logic out0_12;
  logic out0_13;
  logic out0_14;
  logic out0_15;
  logic out0_16;
  logic out0_17;
  logic out0_18;
  logic out0_19;
  logic [31:0] out0_20;  /* ufix32 */
  logic [15:0] baseIndex_1;  /* uint16 */
  logic [16:0] adder_add_temp_2;  /* ufix17 */
  logic [16:0] adder_7;  /* ufix17 */
  logic [16:0] adder_8;  /* ufix17 */
  logic [15:0] out0_21;  /* uint16 */
  logic [16:0] adder_add_temp_3;  /* ufix17 */
  logic [16:0] adder_10;  /* ufix17 */
  logic [16:0] adder_11;  /* ufix17 */
  logic [15:0] out0_22;  /* uint16 */
  logic [31:0] out0_23;  /* ufix32 */
  logic [15:0] laneIndex_1;  /* uint16 */
  logic [16:0] adder_add_temp_4;  /* ufix17 */
  logic [16:0] adder_13;  /* ufix17 */
  logic [16:0] adder_14;  /* ufix17 */
  logic [15:0] out0_24;  /* uint16 */
  logic [16:0] adder_add_temp_5;  /* ufix17 */
  logic [16:0] adder_16;  /* ufix17 */
  logic [16:0] adder_17;  /* ufix17 */
  logic [15:0] out0_25;  /* uint16 */
  logic [31:0] out0_26;  /* ufix32 */
  logic [15:0] laneIndex_2;  /* uint16 */
  logic [16:0] adder_add_temp_6;  /* ufix17 */
  logic [16:0] adder_19;  /* ufix17 */
  logic [16:0] adder_20;  /* ufix17 */
  logic [15:0] out0_27;  /* uint16 */
  logic [16:0] adder_add_temp_7;  /* ufix17 */
  logic [16:0] adder_22;  /* ufix17 */
  logic [16:0] adder_23;  /* ufix17 */
  logic [15:0] out0_28;  /* uint16 */
  logic [31:0] out0_29;  /* ufix32 */
  logic [15:0] laneIndex_3;  /* uint16 */
  logic [16:0] adder_add_temp_8;  /* ufix17 */
  logic [16:0] adder_25;  /* ufix17 */
  logic [16:0] adder_26;  /* ufix17 */
  logic [15:0] out0_30;  /* uint16 */
  logic [16:0] adder_add_temp_9;  /* ufix17 */
  logic [16:0] adder_28;  /* ufix17 */
  logic [16:0] adder_29;  /* ufix17 */
  logic [15:0] out0_31;  /* uint16 */
  logic [31:0] out0_32;  /* ufix32 */
  logic [15:0] laneIndex_4;  /* uint16 */
  logic [16:0] adder_add_temp_10;  /* ufix17 */
  logic [16:0] adder_31;  /* ufix17 */
  logic [16:0] adder_32;  /* ufix17 */
  logic [15:0] out0_33;  /* uint16 */
  logic [16:0] adder_add_temp_11;  /* ufix17 */
  logic [16:0] adder_34;  /* ufix17 */
  logic [16:0] adder_35;  /* ufix17 */
  logic [15:0] out0_34;  /* uint16 */
  logic [31:0] out0_35;  /* ufix32 */
  logic [15:0] laneIndex_5;  /* uint16 */
  logic [16:0] adder_add_temp_12;  /* ufix17 */
  logic [16:0] adder_37;  /* ufix17 */
  logic [16:0] adder_38;  /* ufix17 */
  logic [15:0] out0_36;  /* uint16 */
  logic [16:0] adder_add_temp_13;  /* ufix17 */
  logic [16:0] adder_40;  /* ufix17 */
  logic [16:0] adder_41;  /* ufix17 */
  logic [15:0] out0_37;  /* uint16 */
  logic [31:0] out0_38;  /* ufix32 */
  logic [15:0] laneIndex_6;  /* uint16 */
  logic [16:0] adder_add_temp_14;  /* ufix17 */
  logic [16:0] adder_43;  /* ufix17 */
  logic [16:0] adder_44;  /* ufix17 */
  logic [15:0] out0_39;  /* uint16 */
  logic [16:0] adder_add_temp_15;  /* ufix17 */
  logic [16:0] adder_46;  /* ufix17 */
  logic [16:0] adder_47;  /* ufix17 */
  logic [15:0] out0_40;  /* uint16 */
  logic [31:0] out0_41;  /* ufix32 */
  logic [15:0] laneIndex_7;  /* uint16 */
  logic [16:0] adder_add_temp_16;  /* ufix17 */
  logic [16:0] adder_49;  /* ufix17 */
  logic [16:0] adder_50;  /* ufix17 */
  logic [15:0] out0_42;  /* uint16 */
  logic [16:0] adder_add_temp_17;  /* ufix17 */
  logic [16:0] adder_52;  /* ufix17 */
  logic [16:0] adder_53;  /* ufix17 */
  logic [15:0] out0_43;  /* uint16 */
  logic [31:0] bankA [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_1 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_2 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_3 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_4 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_5 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_6 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_7 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_8 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_9 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_10 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_11 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_12 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_13 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_14 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_15 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_16 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankA_17 [0:1535];  /* ufix32 [1536] */
  logic signed [31:0] Selector_idx;  /* int32 */
  logic [31:0] out0_44;  /* ufix32 */
  logic [31:0] readBeat_2 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_18;  /* ufix17 */
  logic [16:0] adder_55;  /* ufix17 */
  logic [16:0] adder_56;  /* ufix17 */
  logic [15:0] out0_45;  /* uint16 */
  logic [16:0] adder_add_temp_19;  /* ufix17 */
  logic [16:0] adder_58;  /* ufix17 */
  logic [16:0] adder_59;  /* ufix17 */
  logic [15:0] out0_46;  /* uint16 */
  logic [31:0] out0_47;  /* ufix32 */
  logic [16:0] adder_add_temp_20;  /* ufix17 */
  logic [16:0] adder_61;  /* ufix17 */
  logic [16:0] adder_62;  /* ufix17 */
  logic [15:0] out0_48;  /* uint16 */
  logic [16:0] adder_add_temp_21;  /* ufix17 */
  logic [16:0] adder_64;  /* ufix17 */
  logic [16:0] adder_65;  /* ufix17 */
  logic [15:0] out0_49;  /* uint16 */
  logic [31:0] out0_50;  /* ufix32 */
  logic [16:0] adder_add_temp_22;  /* ufix17 */
  logic [16:0] adder_67;  /* ufix17 */
  logic [16:0] adder_68;  /* ufix17 */
  logic [15:0] out0_51;  /* uint16 */
  logic [16:0] adder_add_temp_23;  /* ufix17 */
  logic [16:0] adder_70;  /* ufix17 */
  logic [16:0] adder_71;  /* ufix17 */
  logic [15:0] out0_52;  /* uint16 */
  logic [31:0] out0_53;  /* ufix32 */
  logic [16:0] adder_add_temp_24;  /* ufix17 */
  logic [16:0] adder_73;  /* ufix17 */
  logic [16:0] adder_74;  /* ufix17 */
  logic [15:0] out0_54;  /* uint16 */
  logic [16:0] adder_add_temp_25;  /* ufix17 */
  logic [16:0] adder_76;  /* ufix17 */
  logic [16:0] adder_77;  /* ufix17 */
  logic [15:0] out0_55;  /* uint16 */
  logic [31:0] out0_56;  /* ufix32 */
  logic [16:0] adder_add_temp_26;  /* ufix17 */
  logic [16:0] adder_79;  /* ufix17 */
  logic [16:0] adder_80;  /* ufix17 */
  logic [15:0] out0_57;  /* uint16 */
  logic [16:0] adder_add_temp_27;  /* ufix17 */
  logic [16:0] adder_82;  /* ufix17 */
  logic [16:0] adder_83;  /* ufix17 */
  logic [15:0] out0_58;  /* uint16 */
  logic [31:0] out0_59;  /* ufix32 */
  logic [16:0] adder_add_temp_28;  /* ufix17 */
  logic [16:0] adder_85;  /* ufix17 */
  logic [16:0] adder_86;  /* ufix17 */
  logic [15:0] out0_60;  /* uint16 */
  logic [16:0] adder_add_temp_29;  /* ufix17 */
  logic [16:0] adder_88;  /* ufix17 */
  logic [16:0] adder_89;  /* ufix17 */
  logic [15:0] out0_61;  /* uint16 */
  logic [31:0] out0_62;  /* ufix32 */
  logic [16:0] adder_add_temp_30;  /* ufix17 */
  logic [16:0] adder_91;  /* ufix17 */
  logic [16:0] adder_92;  /* ufix17 */
  logic [15:0] out0_63;  /* uint16 */
  logic [16:0] adder_add_temp_31;  /* ufix17 */
  logic [16:0] adder_94;  /* ufix17 */
  logic [16:0] adder_95;  /* ufix17 */
  logic [15:0] out0_64;  /* uint16 */
  logic [31:0] out0_65;  /* ufix32 */
  logic [16:0] adder_add_temp_32;  /* ufix17 */
  logic [16:0] adder_97;  /* ufix17 */
  logic [16:0] adder_98;  /* ufix17 */
  logic [15:0] out0_66;  /* uint16 */
  logic [16:0] adder_add_temp_33;  /* ufix17 */
  logic [16:0] adder_100;  /* ufix17 */
  logic [16:0] adder_101;  /* ufix17 */
  logic [15:0] out0_67;  /* uint16 */
  logic [31:0] out0_68;  /* ufix32 */
  logic [16:0] adder_add_temp_34;  /* ufix17 */
  logic [16:0] adder_103;  /* ufix17 */
  logic [16:0] adder_104;  /* ufix17 */
  logic [15:0] out0_69;  /* uint16 */
  logic [16:0] adder_add_temp_35;  /* ufix17 */
  logic [16:0] adder_106;  /* ufix17 */
  logic [16:0] adder_107;  /* ufix17 */
  logic [15:0] out0_70;  /* uint16 */
  logic [31:0] bankB [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_1 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_2 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_3 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_4 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_5 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_6 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_7 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_8 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_9 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_10 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_11 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_12 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_13 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_14 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_15 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_16 [0:1535];  /* ufix32 [1536] */
  logic [31:0] bankB_17 [0:1535];  /* ufix32 [1536] */
  logic signed [31:0] Selector_idx_1;  /* int32 */
  logic [31:0] out0_71;  /* ufix32 */
  logic [31:0] readBeat_3 [0:7];  /* ufix32 [8] */
  logic [31:0] readBeat_4 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_36;  /* ufix17 */
  logic [16:0] adder_109;  /* ufix17 */
  logic [16:0] adder_110;  /* ufix17 */
  logic [15:0] out0_72;  /* uint16 */
  logic [16:0] adder_add_temp_37;  /* ufix17 */
  logic [16:0] adder_112;  /* ufix17 */
  logic [16:0] adder_113;  /* ufix17 */
  logic [15:0] out0_73;  /* uint16 */
  logic signed [31:0] Selector_idx_2;  /* int32 */
  logic [31:0] out0_74;  /* ufix32 */
  logic [31:0] readBeat_5 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_38;  /* ufix17 */
  logic [16:0] adder_115;  /* ufix17 */
  logic [16:0] adder_116;  /* ufix17 */
  logic [15:0] out0_75;  /* uint16 */
  logic [16:0] adder_add_temp_39;  /* ufix17 */
  logic [16:0] adder_118;  /* ufix17 */
  logic [16:0] adder_119;  /* ufix17 */
  logic [15:0] out0_76;  /* uint16 */
  logic signed [31:0] Selector_idx_3;  /* int32 */
  logic [31:0] out0_77;  /* ufix32 */
  logic [31:0] readBeat_6 [0:7];  /* ufix32 [8] */
  logic [31:0] readBeat_7 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_40;  /* ufix17 */
  logic [16:0] adder_121;  /* ufix17 */
  logic [16:0] adder_122;  /* ufix17 */
  logic [15:0] out0_78;  /* uint16 */
  logic [16:0] adder_add_temp_41;  /* ufix17 */
  logic [16:0] adder_124;  /* ufix17 */
  logic [16:0] adder_125;  /* ufix17 */
  logic [15:0] out0_79;  /* uint16 */
  logic signed [31:0] Selector_idx_4;  /* int32 */
  logic [31:0] out0_80;  /* ufix32 */
  logic [31:0] readBeat_8 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_42;  /* ufix17 */
  logic [16:0] adder_127;  /* ufix17 */
  logic [16:0] adder_128;  /* ufix17 */
  logic [15:0] out0_81;  /* uint16 */
  logic [16:0] adder_add_temp_43;  /* ufix17 */
  logic [16:0] adder_130;  /* ufix17 */
  logic [16:0] adder_131;  /* ufix17 */
  logic [15:0] out0_82;  /* uint16 */
  logic signed [31:0] Selector_idx_5;  /* int32 */
  logic [31:0] out0_83;  /* ufix32 */
  logic [31:0] readBeat_9 [0:7];  /* ufix32 [8] */
  logic [31:0] readBeat_10 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_44;  /* ufix17 */
  logic [16:0] adder_133;  /* ufix17 */
  logic [16:0] adder_134;  /* ufix17 */
  logic [15:0] out0_84;  /* uint16 */
  logic [16:0] adder_add_temp_45;  /* ufix17 */
  logic [16:0] adder_136;  /* ufix17 */
  logic [16:0] adder_137;  /* ufix17 */
  logic [15:0] out0_85;  /* uint16 */
  logic signed [31:0] Selector_idx_6;  /* int32 */
  logic [31:0] out0_86;  /* ufix32 */
  logic [31:0] readBeat_11 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_46;  /* ufix17 */
  logic [16:0] adder_139;  /* ufix17 */
  logic [16:0] adder_140;  /* ufix17 */
  logic [15:0] out0_87;  /* uint16 */
  logic [16:0] adder_add_temp_47;  /* ufix17 */
  logic [16:0] adder_142;  /* ufix17 */
  logic [16:0] adder_143;  /* ufix17 */
  logic [15:0] out0_88;  /* uint16 */
  logic signed [31:0] Selector_idx_7;  /* int32 */
  logic [31:0] out0_89;  /* ufix32 */
  logic [31:0] readBeat_12 [0:7];  /* ufix32 [8] */
  logic [31:0] readBeat_13 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_48;  /* ufix17 */
  logic [16:0] adder_145;  /* ufix17 */
  logic [16:0] adder_146;  /* ufix17 */
  logic [15:0] out0_90;  /* uint16 */
  logic [16:0] adder_add_temp_49;  /* ufix17 */
  logic [16:0] adder_148;  /* ufix17 */
  logic [16:0] adder_149;  /* ufix17 */
  logic [15:0] out0_91;  /* uint16 */
  logic signed [31:0] Selector_idx_8;  /* int32 */
  logic [31:0] out0_92;  /* ufix32 */
  logic [31:0] readBeat_14 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_50;  /* ufix17 */
  logic [16:0] adder_151;  /* ufix17 */
  logic [16:0] adder_152;  /* ufix17 */
  logic [15:0] out0_93;  /* uint16 */
  logic [16:0] adder_add_temp_51;  /* ufix17 */
  logic [16:0] adder_154;  /* ufix17 */
  logic [16:0] adder_155;  /* ufix17 */
  logic [15:0] out0_94;  /* uint16 */
  logic signed [31:0] Selector_idx_9;  /* int32 */
  logic [31:0] out0_95;  /* ufix32 */
  logic [31:0] readBeat_15 [0:7];  /* ufix32 [8] */
  logic [31:0] readBeat_16 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_52;  /* ufix17 */
  logic [16:0] adder_157;  /* ufix17 */
  logic [16:0] adder_158;  /* ufix17 */
  logic [15:0] out0_96;  /* uint16 */
  logic [16:0] adder_add_temp_53;  /* ufix17 */
  logic [16:0] adder_160;  /* ufix17 */
  logic [16:0] adder_161;  /* ufix17 */
  logic [15:0] out0_97;  /* uint16 */
  logic signed [31:0] Selector_idx_10;  /* int32 */
  logic [31:0] out0_98;  /* ufix32 */
  logic [31:0] readBeat_17 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_54;  /* ufix17 */
  logic [16:0] adder_163;  /* ufix17 */
  logic [16:0] adder_164;  /* ufix17 */
  logic [15:0] out0_99;  /* uint16 */
  logic [16:0] adder_add_temp_55;  /* ufix17 */
  logic [16:0] adder_166;  /* ufix17 */
  logic [16:0] adder_167;  /* ufix17 */
  logic [15:0] out0_100;  /* uint16 */
  logic signed [31:0] Selector_idx_11;  /* int32 */
  logic [31:0] out0_101;  /* ufix32 */
  logic [31:0] readBeat_18 [0:7];  /* ufix32 [8] */
  logic [31:0] readBeat_19 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_56;  /* ufix17 */
  logic [16:0] adder_169;  /* ufix17 */
  logic [16:0] adder_170;  /* ufix17 */
  logic [15:0] out0_102;  /* uint16 */
  logic [16:0] adder_add_temp_57;  /* ufix17 */
  logic [16:0] adder_172;  /* ufix17 */
  logic [16:0] adder_173;  /* ufix17 */
  logic [15:0] out0_103;  /* uint16 */
  logic signed [31:0] Selector_idx_12;  /* int32 */
  logic [31:0] out0_104;  /* ufix32 */
  logic [31:0] readBeat_20 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_58;  /* ufix17 */
  logic [16:0] adder_175;  /* ufix17 */
  logic [16:0] adder_176;  /* ufix17 */
  logic [15:0] out0_105;  /* uint16 */
  logic [16:0] adder_add_temp_59;  /* ufix17 */
  logic [16:0] adder_178;  /* ufix17 */
  logic [16:0] adder_179;  /* ufix17 */
  logic [15:0] out0_106;  /* uint16 */
  logic signed [31:0] Selector_idx_13;  /* int32 */
  logic [31:0] out0_107;  /* ufix32 */
  logic [31:0] readBeat_21 [0:7];  /* ufix32 [8] */
  logic [31:0] readBeat_22 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_60;  /* ufix17 */
  logic [16:0] adder_181;  /* ufix17 */
  logic [16:0] adder_182;  /* ufix17 */
  logic [15:0] out0_108;  /* uint16 */
  logic [16:0] adder_add_temp_61;  /* ufix17 */
  logic [16:0] adder_184;  /* ufix17 */
  logic [16:0] adder_185;  /* ufix17 */
  logic [15:0] out0_109;  /* uint16 */
  logic signed [31:0] Selector_idx_14;  /* int32 */
  logic [31:0] out0_110;  /* ufix32 */
  logic [31:0] readBeat_23 [0:7];  /* ufix32 [8] */
  logic [16:0] adder_add_temp_62;  /* ufix17 */
  logic [16:0] adder_187;  /* ufix17 */
  logic [16:0] adder_188;  /* ufix17 */
  logic [15:0] out0_111;  /* uint16 */
  logic [16:0] adder_add_temp_63;  /* ufix17 */
  logic [16:0] adder_190;  /* ufix17 */
  logic [16:0] adder_191;  /* ufix17 */
  logic [15:0] out0_112;  /* uint16 */
  logic signed [31:0] Selector_idx_15;  /* int32 */
  logic [31:0] out0_113;  /* ufix32 */
  logic [31:0] readBeat_24 [0:7];  /* ufix32 [8] */
  logic [31:0] readBeat_25 [0:7];  /* ufix32 [8] */
  logic readValid_1;
  logic readValid_2;
  logic signed [31:0] Assignment_i;  /* int32 */
  logic signed [31:0] Assignment_add_temp;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_1;  /* int32 */
  logic signed [31:0] Assignment_add_temp_1;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_1 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_2;  /* int32 */
  logic signed [31:0] Assignment_add_temp_2;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_2 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_3;  /* int32 */
  logic signed [31:0] Assignment_add_temp_3;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_3 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_4;  /* int32 */
  logic signed [31:0] Assignment_add_temp_4;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_4 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_5;  /* int32 */
  logic signed [31:0] Assignment_add_temp_5;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_5 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_6;  /* int32 */
  logic signed [31:0] Assignment_add_temp_6;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_6 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_7;  /* int32 */
  logic signed [31:0] Assignment_add_temp_7;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_7 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_8;  /* int32 */
  logic signed [31:0] Assignment_add_temp_8;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_8 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_9;  /* int32 */
  logic signed [31:0] Assignment_add_temp_9;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_9 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_10;  /* int32 */
  logic signed [31:0] Assignment_add_temp_10;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_10 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_11;  /* int32 */
  logic signed [31:0] Assignment_add_temp_11;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_11 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_12;  /* int32 */
  logic signed [31:0] Assignment_add_temp_12;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_12 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_13;  /* int32 */
  logic signed [31:0] Assignment_add_temp_13;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_13 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_14;  /* int32 */
  logic signed [31:0] Assignment_add_temp_14;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_14 [0:1535];  /* ufix16 [1536] */
  logic signed [31:0] Assignment_i_15;  /* int32 */
  logic signed [31:0] Assignment_add_temp_15;  /* int32 */
  vector_of_unsigned_logic_16 Assignment_t_0_15 [0:1535];  /* ufix16 [1536] */


  assign out0 = readReq != 1'b0;

  assign readBeat_1 = '{8{32'h00000000}};

  assign out0_1 = readBank != 1'b0;

  assign out0_2 = readBank != 1'b0;

  assign out0_3 = readBank != 1'b0;

  assign out0_4 = readBank != 1'b0;

  assign out0_5 = readBank != 1'b0;

  assign out0_6 = readBank != 1'b0;

  assign out0_7 = readBank != 1'b0;

  assign out0_8 = readBank != 1'b0;

  assign baseIndex = readAddr <<< 8'd3;

  assign laneIndex = 16'b0000000000000000;

  assign adder_1 = {1'b0, baseIndex};
  assign adder_2 = {1'b0, laneIndex};
  assign adder_add_temp = adder_1 + adder_2;
  assign out0_9 = (adder_add_temp[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp[15:0]);

  assign const_expression = 16'b0000000000000001;

  assign adder_4 = {1'b0, out0_9};
  assign adder_5 = {1'b0, const_expression};
  assign adder_add_temp_1 = adder_4 + adder_5;
  assign out0_10 = (adder_add_temp_1[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_1[15:0]);

  assign out0_11 = writeValid != 1'b0;

  assign out0_12 = writeBank != 1'b0;

  assign out0_13 = writeBank != 1'b0;

  assign out0_14 = writeBank != 1'b0;

  assign out0_15 = writeBank != 1'b0;

  assign out0_16 = writeBank != 1'b0;

  assign out0_17 = writeBank != 1'b0;

  assign out0_18 = writeBank != 1'b0;

  assign out0_19 = writeBank != 1'b0;

  assign out0_20 = writeBeat[0];

  assign baseIndex_1 = writeAddr <<< 8'd3;

  assign adder_7 = {1'b0, baseIndex_1};
  assign adder_8 = {1'b0, laneIndex};
  assign adder_add_temp_2 = adder_7 + adder_8;
  assign out0_21 = (adder_add_temp_2[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_2[15:0]);

  assign adder_10 = {1'b0, out0_21};
  assign adder_11 = {1'b0, const_expression};
  assign adder_add_temp_3 = adder_10 + adder_11;
  assign out0_22 = (adder_add_temp_3[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_3[15:0]);

  assign out0_23 = writeBeat[1];

  assign laneIndex_1 = 16'b0000000000000001;

  assign adder_13 = {1'b0, baseIndex_1};
  assign adder_14 = {1'b0, laneIndex_1};
  assign adder_add_temp_4 = adder_13 + adder_14;
  assign out0_24 = (adder_add_temp_4[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_4[15:0]);

  assign adder_16 = {1'b0, out0_24};
  assign adder_17 = {1'b0, const_expression};
  assign adder_add_temp_5 = adder_16 + adder_17;
  assign out0_25 = (adder_add_temp_5[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_5[15:0]);

  assign out0_26 = writeBeat[2];

  assign laneIndex_2 = 16'b0000000000000010;

  assign adder_19 = {1'b0, baseIndex_1};
  assign adder_20 = {1'b0, laneIndex_2};
  assign adder_add_temp_6 = adder_19 + adder_20;
  assign out0_27 = (adder_add_temp_6[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_6[15:0]);

  assign adder_22 = {1'b0, out0_27};
  assign adder_23 = {1'b0, const_expression};
  assign adder_add_temp_7 = adder_22 + adder_23;
  assign out0_28 = (adder_add_temp_7[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_7[15:0]);

  assign out0_29 = writeBeat[3];

  assign laneIndex_3 = 16'b0000000000000011;

  assign adder_25 = {1'b0, baseIndex_1};
  assign adder_26 = {1'b0, laneIndex_3};
  assign adder_add_temp_8 = adder_25 + adder_26;
  assign out0_30 = (adder_add_temp_8[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_8[15:0]);

  assign adder_28 = {1'b0, out0_30};
  assign adder_29 = {1'b0, const_expression};
  assign adder_add_temp_9 = adder_28 + adder_29;
  assign out0_31 = (adder_add_temp_9[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_9[15:0]);

  assign out0_32 = writeBeat[4];

  assign laneIndex_4 = 16'b0000000000000100;

  assign adder_31 = {1'b0, baseIndex_1};
  assign adder_32 = {1'b0, laneIndex_4};
  assign adder_add_temp_10 = adder_31 + adder_32;
  assign out0_33 = (adder_add_temp_10[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_10[15:0]);

  assign adder_34 = {1'b0, out0_33};
  assign adder_35 = {1'b0, const_expression};
  assign adder_add_temp_11 = adder_34 + adder_35;
  assign out0_34 = (adder_add_temp_11[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_11[15:0]);

  assign out0_35 = writeBeat[5];

  assign laneIndex_5 = 16'b0000000000000101;

  assign adder_37 = {1'b0, baseIndex_1};
  assign adder_38 = {1'b0, laneIndex_5};
  assign adder_add_temp_12 = adder_37 + adder_38;
  assign out0_36 = (adder_add_temp_12[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_12[15:0]);

  assign adder_40 = {1'b0, out0_36};
  assign adder_41 = {1'b0, const_expression};
  assign adder_add_temp_13 = adder_40 + adder_41;
  assign out0_37 = (adder_add_temp_13[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_13[15:0]);

  assign out0_38 = writeBeat[6];

  assign laneIndex_6 = 16'b0000000000000110;

  assign adder_43 = {1'b0, baseIndex_1};
  assign adder_44 = {1'b0, laneIndex_6};
  assign adder_add_temp_14 = adder_43 + adder_44;
  assign out0_39 = (adder_add_temp_14[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_14[15:0]);

  assign adder_46 = {1'b0, out0_39};
  assign adder_47 = {1'b0, const_expression};
  assign adder_add_temp_15 = adder_46 + adder_47;
  assign out0_40 = (adder_add_temp_15[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_15[15:0]);

  assign out0_41 = writeBeat[7];

  assign laneIndex_7 = 16'b0000000000000111;

  assign adder_49 = {1'b0, baseIndex_1};
  assign adder_50 = {1'b0, laneIndex_7};
  assign adder_add_temp_16 = adder_49 + adder_50;
  assign out0_42 = (adder_add_temp_16[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_16[15:0]);

  assign adder_52 = {1'b0, out0_42};
  assign adder_53 = {1'b0, const_expression};
  assign adder_add_temp_17 = adder_52 + adder_53;
  assign out0_43 = (adder_add_temp_17[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_17[15:0]);

  always_comb begin
    Assignment_add_temp = 32'sd0;

    for(Assignment_i = 32'sd0; Assignment_i <= 32'sd1535; Assignment_i = Assignment_i + 32'sd1) begin
      Assignment_add_temp = Assignment_i + 32'sd1;
      Assignment_t_0[Assignment_i] = Assignment_add_temp[15:0];
      if (out0_22 == Assignment_t_0[Assignment_i]) begin
        bankA_1[Assignment_i] = out0_20;
      end
      else begin
        bankA_1[Assignment_i] = bankA[Assignment_i];
      end
    end

  end

  assign bankA_2 = (out0_19 == 1'b0 ? bankA_1 :
              bankA);

  always_comb begin
    Assignment_add_temp_1 = 32'sd0;

    for(Assignment_i_1 = 32'sd0; Assignment_i_1 <= 32'sd1535; Assignment_i_1 = Assignment_i_1 + 32'sd1) begin
      Assignment_add_temp_1 = Assignment_i_1 + 32'sd1;
      Assignment_t_0_1[Assignment_i_1] = Assignment_add_temp_1[15:0];
      if (out0_25 == Assignment_t_0_1[Assignment_i_1]) begin
        bankA_3[Assignment_i_1] = out0_23;
      end
      else begin
        bankA_3[Assignment_i_1] = bankA_2[Assignment_i_1];
      end
    end

  end

  assign bankA_4 = (out0_18 == 1'b0 ? bankA_3 :
              bankA_2);

  always_comb begin
    Assignment_add_temp_2 = 32'sd0;

    for(Assignment_i_2 = 32'sd0; Assignment_i_2 <= 32'sd1535; Assignment_i_2 = Assignment_i_2 + 32'sd1) begin
      Assignment_add_temp_2 = Assignment_i_2 + 32'sd1;
      Assignment_t_0_2[Assignment_i_2] = Assignment_add_temp_2[15:0];
      if (out0_28 == Assignment_t_0_2[Assignment_i_2]) begin
        bankA_5[Assignment_i_2] = out0_26;
      end
      else begin
        bankA_5[Assignment_i_2] = bankA_4[Assignment_i_2];
      end
    end

  end

  assign bankA_6 = (out0_17 == 1'b0 ? bankA_5 :
              bankA_4);

  always_comb begin
    Assignment_add_temp_3 = 32'sd0;

    for(Assignment_i_3 = 32'sd0; Assignment_i_3 <= 32'sd1535; Assignment_i_3 = Assignment_i_3 + 32'sd1) begin
      Assignment_add_temp_3 = Assignment_i_3 + 32'sd1;
      Assignment_t_0_3[Assignment_i_3] = Assignment_add_temp_3[15:0];
      if (out0_31 == Assignment_t_0_3[Assignment_i_3]) begin
        bankA_7[Assignment_i_3] = out0_29;
      end
      else begin
        bankA_7[Assignment_i_3] = bankA_6[Assignment_i_3];
      end
    end

  end

  assign bankA_8 = (out0_16 == 1'b0 ? bankA_7 :
              bankA_6);

  always_comb begin
    Assignment_add_temp_4 = 32'sd0;

    for(Assignment_i_4 = 32'sd0; Assignment_i_4 <= 32'sd1535; Assignment_i_4 = Assignment_i_4 + 32'sd1) begin
      Assignment_add_temp_4 = Assignment_i_4 + 32'sd1;
      Assignment_t_0_4[Assignment_i_4] = Assignment_add_temp_4[15:0];
      if (out0_34 == Assignment_t_0_4[Assignment_i_4]) begin
        bankA_9[Assignment_i_4] = out0_32;
      end
      else begin
        bankA_9[Assignment_i_4] = bankA_8[Assignment_i_4];
      end
    end

  end

  assign bankA_10 = (out0_15 == 1'b0 ? bankA_9 :
              bankA_8);

  always_comb begin
    Assignment_add_temp_5 = 32'sd0;

    for(Assignment_i_5 = 32'sd0; Assignment_i_5 <= 32'sd1535; Assignment_i_5 = Assignment_i_5 + 32'sd1) begin
      Assignment_add_temp_5 = Assignment_i_5 + 32'sd1;
      Assignment_t_0_5[Assignment_i_5] = Assignment_add_temp_5[15:0];
      if (out0_37 == Assignment_t_0_5[Assignment_i_5]) begin
        bankA_11[Assignment_i_5] = out0_35;
      end
      else begin
        bankA_11[Assignment_i_5] = bankA_10[Assignment_i_5];
      end
    end

  end

  assign bankA_12 = (out0_14 == 1'b0 ? bankA_11 :
              bankA_10);

  always_comb begin
    Assignment_add_temp_6 = 32'sd0;

    for(Assignment_i_6 = 32'sd0; Assignment_i_6 <= 32'sd1535; Assignment_i_6 = Assignment_i_6 + 32'sd1) begin
      Assignment_add_temp_6 = Assignment_i_6 + 32'sd1;
      Assignment_t_0_6[Assignment_i_6] = Assignment_add_temp_6[15:0];
      if (out0_40 == Assignment_t_0_6[Assignment_i_6]) begin
        bankA_13[Assignment_i_6] = out0_38;
      end
      else begin
        bankA_13[Assignment_i_6] = bankA_12[Assignment_i_6];
      end
    end

  end

  assign bankA_14 = (out0_13 == 1'b0 ? bankA_13 :
              bankA_12);

  always_comb begin
    Assignment_add_temp_7 = 32'sd0;

    for(Assignment_i_7 = 32'sd0; Assignment_i_7 <= 32'sd1535; Assignment_i_7 = Assignment_i_7 + 32'sd1) begin
      Assignment_add_temp_7 = Assignment_i_7 + 32'sd1;
      Assignment_t_0_7[Assignment_i_7] = Assignment_add_temp_7[15:0];
      if (out0_43 == Assignment_t_0_7[Assignment_i_7]) begin
        bankA_15[Assignment_i_7] = out0_41;
      end
      else begin
        bankA_15[Assignment_i_7] = bankA_14[Assignment_i_7];
      end
    end

  end

  assign bankA_16 = (out0_12 == 1'b0 ? bankA_15 :
              bankA_14);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        bankA <= '{1536{32'h00000000}};
      end
      else begin
        if (enb) begin
          bankA <= bankA_17;
        end
      end
    end

  assign bankA_17 = (out0_11 == 1'b0 ? bankA :
              bankA_16);

  assign Selector_idx = {16'b0, out0_10};
  assign out0_44 = ((Selector_idx >= 32'sd1) && (Selector_idx <= 32'sd1536) ? bankA_17[Selector_idx - 32'sd1] :
              bankA_17[1535]);

  assign readBeat_2[0] = out0_44;
  assign readBeat_2[1] = readBeat_1[1];
  assign readBeat_2[2] = readBeat_1[2];
  assign readBeat_2[3] = readBeat_1[3];
  assign readBeat_2[4] = readBeat_1[4];
  assign readBeat_2[5] = readBeat_1[5];
  assign readBeat_2[6] = readBeat_1[6];
  assign readBeat_2[7] = readBeat_1[7];

  assign adder_55 = {1'b0, baseIndex};
  assign adder_56 = {1'b0, laneIndex};
  assign adder_add_temp_18 = adder_55 + adder_56;
  assign out0_45 = (adder_add_temp_18[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_18[15:0]);

  assign adder_58 = {1'b0, out0_45};
  assign adder_59 = {1'b0, const_expression};
  assign adder_add_temp_19 = adder_58 + adder_59;
  assign out0_46 = (adder_add_temp_19[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_19[15:0]);

  assign out0_47 = writeBeat[0];

  assign adder_61 = {1'b0, baseIndex_1};
  assign adder_62 = {1'b0, laneIndex};
  assign adder_add_temp_20 = adder_61 + adder_62;
  assign out0_48 = (adder_add_temp_20[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_20[15:0]);

  assign adder_64 = {1'b0, out0_48};
  assign adder_65 = {1'b0, const_expression};
  assign adder_add_temp_21 = adder_64 + adder_65;
  assign out0_49 = (adder_add_temp_21[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_21[15:0]);

  assign out0_50 = writeBeat[1];

  assign adder_67 = {1'b0, baseIndex_1};
  assign adder_68 = {1'b0, laneIndex_1};
  assign adder_add_temp_22 = adder_67 + adder_68;
  assign out0_51 = (adder_add_temp_22[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_22[15:0]);

  assign adder_70 = {1'b0, out0_51};
  assign adder_71 = {1'b0, const_expression};
  assign adder_add_temp_23 = adder_70 + adder_71;
  assign out0_52 = (adder_add_temp_23[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_23[15:0]);

  assign out0_53 = writeBeat[2];

  assign adder_73 = {1'b0, baseIndex_1};
  assign adder_74 = {1'b0, laneIndex_2};
  assign adder_add_temp_24 = adder_73 + adder_74;
  assign out0_54 = (adder_add_temp_24[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_24[15:0]);

  assign adder_76 = {1'b0, out0_54};
  assign adder_77 = {1'b0, const_expression};
  assign adder_add_temp_25 = adder_76 + adder_77;
  assign out0_55 = (adder_add_temp_25[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_25[15:0]);

  assign out0_56 = writeBeat[3];

  assign adder_79 = {1'b0, baseIndex_1};
  assign adder_80 = {1'b0, laneIndex_3};
  assign adder_add_temp_26 = adder_79 + adder_80;
  assign out0_57 = (adder_add_temp_26[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_26[15:0]);

  assign adder_82 = {1'b0, out0_57};
  assign adder_83 = {1'b0, const_expression};
  assign adder_add_temp_27 = adder_82 + adder_83;
  assign out0_58 = (adder_add_temp_27[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_27[15:0]);

  assign out0_59 = writeBeat[4];

  assign adder_85 = {1'b0, baseIndex_1};
  assign adder_86 = {1'b0, laneIndex_4};
  assign adder_add_temp_28 = adder_85 + adder_86;
  assign out0_60 = (adder_add_temp_28[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_28[15:0]);

  assign adder_88 = {1'b0, out0_60};
  assign adder_89 = {1'b0, const_expression};
  assign adder_add_temp_29 = adder_88 + adder_89;
  assign out0_61 = (adder_add_temp_29[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_29[15:0]);

  assign out0_62 = writeBeat[5];

  assign adder_91 = {1'b0, baseIndex_1};
  assign adder_92 = {1'b0, laneIndex_5};
  assign adder_add_temp_30 = adder_91 + adder_92;
  assign out0_63 = (adder_add_temp_30[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_30[15:0]);

  assign adder_94 = {1'b0, out0_63};
  assign adder_95 = {1'b0, const_expression};
  assign adder_add_temp_31 = adder_94 + adder_95;
  assign out0_64 = (adder_add_temp_31[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_31[15:0]);

  assign out0_65 = writeBeat[6];

  assign adder_97 = {1'b0, baseIndex_1};
  assign adder_98 = {1'b0, laneIndex_6};
  assign adder_add_temp_32 = adder_97 + adder_98;
  assign out0_66 = (adder_add_temp_32[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_32[15:0]);

  assign adder_100 = {1'b0, out0_66};
  assign adder_101 = {1'b0, const_expression};
  assign adder_add_temp_33 = adder_100 + adder_101;
  assign out0_67 = (adder_add_temp_33[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_33[15:0]);

  assign out0_68 = writeBeat[7];

  assign adder_103 = {1'b0, baseIndex_1};
  assign adder_104 = {1'b0, laneIndex_7};
  assign adder_add_temp_34 = adder_103 + adder_104;
  assign out0_69 = (adder_add_temp_34[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_34[15:0]);

  assign adder_106 = {1'b0, out0_69};
  assign adder_107 = {1'b0, const_expression};
  assign adder_add_temp_35 = adder_106 + adder_107;
  assign out0_70 = (adder_add_temp_35[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_35[15:0]);

  always_comb begin
    Assignment_add_temp_8 = 32'sd0;

    for(Assignment_i_8 = 32'sd0; Assignment_i_8 <= 32'sd1535; Assignment_i_8 = Assignment_i_8 + 32'sd1) begin
      Assignment_add_temp_8 = Assignment_i_8 + 32'sd1;
      Assignment_t_0_8[Assignment_i_8] = Assignment_add_temp_8[15:0];
      if (out0_70 == Assignment_t_0_8[Assignment_i_8]) begin
        bankB_1[Assignment_i_8] = out0_68;
      end
      else begin
        bankB_1[Assignment_i_8] = bankB[Assignment_i_8];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_9 = 32'sd0;

    for(Assignment_i_9 = 32'sd0; Assignment_i_9 <= 32'sd1535; Assignment_i_9 = Assignment_i_9 + 32'sd1) begin
      Assignment_add_temp_9 = Assignment_i_9 + 32'sd1;
      Assignment_t_0_9[Assignment_i_9] = Assignment_add_temp_9[15:0];
      if (out0_67 == Assignment_t_0_9[Assignment_i_9]) begin
        bankB_3[Assignment_i_9] = out0_65;
      end
      else begin
        bankB_3[Assignment_i_9] = bankB_2[Assignment_i_9];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_10 = 32'sd0;

    for(Assignment_i_10 = 32'sd0; Assignment_i_10 <= 32'sd1535; Assignment_i_10 = Assignment_i_10 + 32'sd1) begin
      Assignment_add_temp_10 = Assignment_i_10 + 32'sd1;
      Assignment_t_0_10[Assignment_i_10] = Assignment_add_temp_10[15:0];
      if (out0_64 == Assignment_t_0_10[Assignment_i_10]) begin
        bankB_5[Assignment_i_10] = out0_62;
      end
      else begin
        bankB_5[Assignment_i_10] = bankB_4[Assignment_i_10];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_11 = 32'sd0;

    for(Assignment_i_11 = 32'sd0; Assignment_i_11 <= 32'sd1535; Assignment_i_11 = Assignment_i_11 + 32'sd1) begin
      Assignment_add_temp_11 = Assignment_i_11 + 32'sd1;
      Assignment_t_0_11[Assignment_i_11] = Assignment_add_temp_11[15:0];
      if (out0_61 == Assignment_t_0_11[Assignment_i_11]) begin
        bankB_7[Assignment_i_11] = out0_59;
      end
      else begin
        bankB_7[Assignment_i_11] = bankB_6[Assignment_i_11];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_12 = 32'sd0;

    for(Assignment_i_12 = 32'sd0; Assignment_i_12 <= 32'sd1535; Assignment_i_12 = Assignment_i_12 + 32'sd1) begin
      Assignment_add_temp_12 = Assignment_i_12 + 32'sd1;
      Assignment_t_0_12[Assignment_i_12] = Assignment_add_temp_12[15:0];
      if (out0_58 == Assignment_t_0_12[Assignment_i_12]) begin
        bankB_9[Assignment_i_12] = out0_56;
      end
      else begin
        bankB_9[Assignment_i_12] = bankB_8[Assignment_i_12];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_13 = 32'sd0;

    for(Assignment_i_13 = 32'sd0; Assignment_i_13 <= 32'sd1535; Assignment_i_13 = Assignment_i_13 + 32'sd1) begin
      Assignment_add_temp_13 = Assignment_i_13 + 32'sd1;
      Assignment_t_0_13[Assignment_i_13] = Assignment_add_temp_13[15:0];
      if (out0_55 == Assignment_t_0_13[Assignment_i_13]) begin
        bankB_11[Assignment_i_13] = out0_53;
      end
      else begin
        bankB_11[Assignment_i_13] = bankB_10[Assignment_i_13];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_14 = 32'sd0;

    for(Assignment_i_14 = 32'sd0; Assignment_i_14 <= 32'sd1535; Assignment_i_14 = Assignment_i_14 + 32'sd1) begin
      Assignment_add_temp_14 = Assignment_i_14 + 32'sd1;
      Assignment_t_0_14[Assignment_i_14] = Assignment_add_temp_14[15:0];
      if (out0_52 == Assignment_t_0_14[Assignment_i_14]) begin
        bankB_13[Assignment_i_14] = out0_50;
      end
      else begin
        bankB_13[Assignment_i_14] = bankB_12[Assignment_i_14];
      end
    end

  end

  always_comb begin
    Assignment_add_temp_15 = 32'sd0;

    for(Assignment_i_15 = 32'sd0; Assignment_i_15 <= 32'sd1535; Assignment_i_15 = Assignment_i_15 + 32'sd1) begin
      Assignment_add_temp_15 = Assignment_i_15 + 32'sd1;
      Assignment_t_0_15[Assignment_i_15] = Assignment_add_temp_15[15:0];
      if (out0_49 == Assignment_t_0_15[Assignment_i_15]) begin
        bankB_15[Assignment_i_15] = out0_47;
      end
      else begin
        bankB_15[Assignment_i_15] = bankB_14[Assignment_i_15];
      end
    end

  end

  assign bankB_12 = (out0_19 == 1'b0 ? bankB_14 :
              bankB_15);

  assign bankB_10 = (out0_18 == 1'b0 ? bankB_12 :
              bankB_13);

  assign bankB_8 = (out0_17 == 1'b0 ? bankB_10 :
              bankB_11);

  assign bankB_6 = (out0_16 == 1'b0 ? bankB_8 :
              bankB_9);

  assign bankB_4 = (out0_15 == 1'b0 ? bankB_6 :
              bankB_7);

  assign bankB_2 = (out0_14 == 1'b0 ? bankB_4 :
              bankB_5);

  assign bankB = (out0_13 == 1'b0 ? bankB_2 :
              bankB_3);

  assign bankB_16 = (out0_12 == 1'b0 ? bankB :
              bankB_1);

  always_ff @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        bankB_14 <= '{1536{32'h00000000}};
      end
      else begin
        if (enb) begin
          bankB_14 <= bankB_17;
        end
      end
    end

  assign bankB_17 = (out0_11 == 1'b0 ? bankB_14 :
              bankB_16);

  assign Selector_idx_1 = {16'b0, out0_46};
  assign out0_71 = ((Selector_idx_1 >= 32'sd1) && (Selector_idx_1 <= 32'sd1536) ? bankB_17[Selector_idx_1 - 32'sd1] :
              bankB_17[1535]);

  assign readBeat_3[0] = out0_71;
  assign readBeat_3[1] = readBeat_1[1];
  assign readBeat_3[2] = readBeat_1[2];
  assign readBeat_3[3] = readBeat_1[3];
  assign readBeat_3[4] = readBeat_1[4];
  assign readBeat_3[5] = readBeat_1[5];
  assign readBeat_3[6] = readBeat_1[6];
  assign readBeat_3[7] = readBeat_1[7];

  assign readBeat_4 = (out0_8 == 1'b0 ? readBeat_2 :
              readBeat_3);

  assign adder_109 = {1'b0, baseIndex};
  assign adder_110 = {1'b0, laneIndex_1};
  assign adder_add_temp_36 = adder_109 + adder_110;
  assign out0_72 = (adder_add_temp_36[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_36[15:0]);

  assign adder_112 = {1'b0, out0_72};
  assign adder_113 = {1'b0, const_expression};
  assign adder_add_temp_37 = adder_112 + adder_113;
  assign out0_73 = (adder_add_temp_37[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_37[15:0]);

  assign Selector_idx_2 = {16'b0, out0_73};
  assign out0_74 = ((Selector_idx_2 >= 32'sd1) && (Selector_idx_2 <= 32'sd1536) ? bankA_17[Selector_idx_2 - 32'sd1] :
              bankA_17[1535]);

  assign readBeat_5[0] = readBeat_4[0];
  assign readBeat_5[1] = out0_74;
  assign readBeat_5[2] = readBeat_4[2];
  assign readBeat_5[3] = readBeat_4[3];
  assign readBeat_5[4] = readBeat_4[4];
  assign readBeat_5[5] = readBeat_4[5];
  assign readBeat_5[6] = readBeat_4[6];
  assign readBeat_5[7] = readBeat_4[7];

  assign adder_115 = {1'b0, baseIndex};
  assign adder_116 = {1'b0, laneIndex_1};
  assign adder_add_temp_38 = adder_115 + adder_116;
  assign out0_75 = (adder_add_temp_38[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_38[15:0]);

  assign adder_118 = {1'b0, out0_75};
  assign adder_119 = {1'b0, const_expression};
  assign adder_add_temp_39 = adder_118 + adder_119;
  assign out0_76 = (adder_add_temp_39[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_39[15:0]);

  assign Selector_idx_3 = {16'b0, out0_76};
  assign out0_77 = ((Selector_idx_3 >= 32'sd1) && (Selector_idx_3 <= 32'sd1536) ? bankB_17[Selector_idx_3 - 32'sd1] :
              bankB_17[1535]);

  assign readBeat_6[0] = readBeat_4[0];
  assign readBeat_6[1] = out0_77;
  assign readBeat_6[2] = readBeat_4[2];
  assign readBeat_6[3] = readBeat_4[3];
  assign readBeat_6[4] = readBeat_4[4];
  assign readBeat_6[5] = readBeat_4[5];
  assign readBeat_6[6] = readBeat_4[6];
  assign readBeat_6[7] = readBeat_4[7];

  assign readBeat_7 = (out0_7 == 1'b0 ? readBeat_5 :
              readBeat_6);

  assign adder_121 = {1'b0, baseIndex};
  assign adder_122 = {1'b0, laneIndex_2};
  assign adder_add_temp_40 = adder_121 + adder_122;
  assign out0_78 = (adder_add_temp_40[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_40[15:0]);

  assign adder_124 = {1'b0, out0_78};
  assign adder_125 = {1'b0, const_expression};
  assign adder_add_temp_41 = adder_124 + adder_125;
  assign out0_79 = (adder_add_temp_41[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_41[15:0]);

  assign Selector_idx_4 = {16'b0, out0_79};
  assign out0_80 = ((Selector_idx_4 >= 32'sd1) && (Selector_idx_4 <= 32'sd1536) ? bankA_17[Selector_idx_4 - 32'sd1] :
              bankA_17[1535]);

  assign readBeat_8[0] = readBeat_7[0];
  assign readBeat_8[1] = readBeat_7[1];
  assign readBeat_8[2] = out0_80;
  assign readBeat_8[3] = readBeat_7[3];
  assign readBeat_8[4] = readBeat_7[4];
  assign readBeat_8[5] = readBeat_7[5];
  assign readBeat_8[6] = readBeat_7[6];
  assign readBeat_8[7] = readBeat_7[7];

  assign adder_127 = {1'b0, baseIndex};
  assign adder_128 = {1'b0, laneIndex_2};
  assign adder_add_temp_42 = adder_127 + adder_128;
  assign out0_81 = (adder_add_temp_42[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_42[15:0]);

  assign adder_130 = {1'b0, out0_81};
  assign adder_131 = {1'b0, const_expression};
  assign adder_add_temp_43 = adder_130 + adder_131;
  assign out0_82 = (adder_add_temp_43[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_43[15:0]);

  assign Selector_idx_5 = {16'b0, out0_82};
  assign out0_83 = ((Selector_idx_5 >= 32'sd1) && (Selector_idx_5 <= 32'sd1536) ? bankB_17[Selector_idx_5 - 32'sd1] :
              bankB_17[1535]);

  assign readBeat_9[0] = readBeat_7[0];
  assign readBeat_9[1] = readBeat_7[1];
  assign readBeat_9[2] = out0_83;
  assign readBeat_9[3] = readBeat_7[3];
  assign readBeat_9[4] = readBeat_7[4];
  assign readBeat_9[5] = readBeat_7[5];
  assign readBeat_9[6] = readBeat_7[6];
  assign readBeat_9[7] = readBeat_7[7];

  assign readBeat_10 = (out0_6 == 1'b0 ? readBeat_8 :
              readBeat_9);

  assign adder_133 = {1'b0, baseIndex};
  assign adder_134 = {1'b0, laneIndex_3};
  assign adder_add_temp_44 = adder_133 + adder_134;
  assign out0_84 = (adder_add_temp_44[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_44[15:0]);

  assign adder_136 = {1'b0, out0_84};
  assign adder_137 = {1'b0, const_expression};
  assign adder_add_temp_45 = adder_136 + adder_137;
  assign out0_85 = (adder_add_temp_45[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_45[15:0]);

  assign Selector_idx_6 = {16'b0, out0_85};
  assign out0_86 = ((Selector_idx_6 >= 32'sd1) && (Selector_idx_6 <= 32'sd1536) ? bankA_17[Selector_idx_6 - 32'sd1] :
              bankA_17[1535]);

  assign readBeat_11[0] = readBeat_10[0];
  assign readBeat_11[1] = readBeat_10[1];
  assign readBeat_11[2] = readBeat_10[2];
  assign readBeat_11[3] = out0_86;
  assign readBeat_11[4] = readBeat_10[4];
  assign readBeat_11[5] = readBeat_10[5];
  assign readBeat_11[6] = readBeat_10[6];
  assign readBeat_11[7] = readBeat_10[7];

  assign adder_139 = {1'b0, baseIndex};
  assign adder_140 = {1'b0, laneIndex_3};
  assign adder_add_temp_46 = adder_139 + adder_140;
  assign out0_87 = (adder_add_temp_46[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_46[15:0]);

  assign adder_142 = {1'b0, out0_87};
  assign adder_143 = {1'b0, const_expression};
  assign adder_add_temp_47 = adder_142 + adder_143;
  assign out0_88 = (adder_add_temp_47[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_47[15:0]);

  assign Selector_idx_7 = {16'b0, out0_88};
  assign out0_89 = ((Selector_idx_7 >= 32'sd1) && (Selector_idx_7 <= 32'sd1536) ? bankB_17[Selector_idx_7 - 32'sd1] :
              bankB_17[1535]);

  assign readBeat_12[0] = readBeat_10[0];
  assign readBeat_12[1] = readBeat_10[1];
  assign readBeat_12[2] = readBeat_10[2];
  assign readBeat_12[3] = out0_89;
  assign readBeat_12[4] = readBeat_10[4];
  assign readBeat_12[5] = readBeat_10[5];
  assign readBeat_12[6] = readBeat_10[6];
  assign readBeat_12[7] = readBeat_10[7];

  assign readBeat_13 = (out0_5 == 1'b0 ? readBeat_11 :
              readBeat_12);

  assign adder_145 = {1'b0, baseIndex};
  assign adder_146 = {1'b0, laneIndex_4};
  assign adder_add_temp_48 = adder_145 + adder_146;
  assign out0_90 = (adder_add_temp_48[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_48[15:0]);

  assign adder_148 = {1'b0, out0_90};
  assign adder_149 = {1'b0, const_expression};
  assign adder_add_temp_49 = adder_148 + adder_149;
  assign out0_91 = (adder_add_temp_49[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_49[15:0]);

  assign Selector_idx_8 = {16'b0, out0_91};
  assign out0_92 = ((Selector_idx_8 >= 32'sd1) && (Selector_idx_8 <= 32'sd1536) ? bankA_17[Selector_idx_8 - 32'sd1] :
              bankA_17[1535]);

  assign readBeat_14[0] = readBeat_13[0];
  assign readBeat_14[1] = readBeat_13[1];
  assign readBeat_14[2] = readBeat_13[2];
  assign readBeat_14[3] = readBeat_13[3];
  assign readBeat_14[4] = out0_92;
  assign readBeat_14[5] = readBeat_13[5];
  assign readBeat_14[6] = readBeat_13[6];
  assign readBeat_14[7] = readBeat_13[7];

  assign adder_151 = {1'b0, baseIndex};
  assign adder_152 = {1'b0, laneIndex_4};
  assign adder_add_temp_50 = adder_151 + adder_152;
  assign out0_93 = (adder_add_temp_50[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_50[15:0]);

  assign adder_154 = {1'b0, out0_93};
  assign adder_155 = {1'b0, const_expression};
  assign adder_add_temp_51 = adder_154 + adder_155;
  assign out0_94 = (adder_add_temp_51[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_51[15:0]);

  assign Selector_idx_9 = {16'b0, out0_94};
  assign out0_95 = ((Selector_idx_9 >= 32'sd1) && (Selector_idx_9 <= 32'sd1536) ? bankB_17[Selector_idx_9 - 32'sd1] :
              bankB_17[1535]);

  assign readBeat_15[0] = readBeat_13[0];
  assign readBeat_15[1] = readBeat_13[1];
  assign readBeat_15[2] = readBeat_13[2];
  assign readBeat_15[3] = readBeat_13[3];
  assign readBeat_15[4] = out0_95;
  assign readBeat_15[5] = readBeat_13[5];
  assign readBeat_15[6] = readBeat_13[6];
  assign readBeat_15[7] = readBeat_13[7];

  assign readBeat_16 = (out0_4 == 1'b0 ? readBeat_14 :
              readBeat_15);

  assign adder_157 = {1'b0, baseIndex};
  assign adder_158 = {1'b0, laneIndex_5};
  assign adder_add_temp_52 = adder_157 + adder_158;
  assign out0_96 = (adder_add_temp_52[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_52[15:0]);

  assign adder_160 = {1'b0, out0_96};
  assign adder_161 = {1'b0, const_expression};
  assign adder_add_temp_53 = adder_160 + adder_161;
  assign out0_97 = (adder_add_temp_53[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_53[15:0]);

  assign Selector_idx_10 = {16'b0, out0_97};
  assign out0_98 = ((Selector_idx_10 >= 32'sd1) && (Selector_idx_10 <= 32'sd1536) ? bankA_17[Selector_idx_10 - 32'sd1] :
              bankA_17[1535]);

  assign readBeat_17[0] = readBeat_16[0];
  assign readBeat_17[1] = readBeat_16[1];
  assign readBeat_17[2] = readBeat_16[2];
  assign readBeat_17[3] = readBeat_16[3];
  assign readBeat_17[4] = readBeat_16[4];
  assign readBeat_17[5] = out0_98;
  assign readBeat_17[6] = readBeat_16[6];
  assign readBeat_17[7] = readBeat_16[7];

  assign adder_163 = {1'b0, baseIndex};
  assign adder_164 = {1'b0, laneIndex_5};
  assign adder_add_temp_54 = adder_163 + adder_164;
  assign out0_99 = (adder_add_temp_54[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_54[15:0]);

  assign adder_166 = {1'b0, out0_99};
  assign adder_167 = {1'b0, const_expression};
  assign adder_add_temp_55 = adder_166 + adder_167;
  assign out0_100 = (adder_add_temp_55[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_55[15:0]);

  assign Selector_idx_11 = {16'b0, out0_100};
  assign out0_101 = ((Selector_idx_11 >= 32'sd1) && (Selector_idx_11 <= 32'sd1536) ? bankB_17[Selector_idx_11 - 32'sd1] :
              bankB_17[1535]);

  assign readBeat_18[0] = readBeat_16[0];
  assign readBeat_18[1] = readBeat_16[1];
  assign readBeat_18[2] = readBeat_16[2];
  assign readBeat_18[3] = readBeat_16[3];
  assign readBeat_18[4] = readBeat_16[4];
  assign readBeat_18[5] = out0_101;
  assign readBeat_18[6] = readBeat_16[6];
  assign readBeat_18[7] = readBeat_16[7];

  assign readBeat_19 = (out0_3 == 1'b0 ? readBeat_17 :
              readBeat_18);

  assign adder_169 = {1'b0, baseIndex};
  assign adder_170 = {1'b0, laneIndex_6};
  assign adder_add_temp_56 = adder_169 + adder_170;
  assign out0_102 = (adder_add_temp_56[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_56[15:0]);

  assign adder_172 = {1'b0, out0_102};
  assign adder_173 = {1'b0, const_expression};
  assign adder_add_temp_57 = adder_172 + adder_173;
  assign out0_103 = (adder_add_temp_57[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_57[15:0]);

  assign Selector_idx_12 = {16'b0, out0_103};
  assign out0_104 = ((Selector_idx_12 >= 32'sd1) && (Selector_idx_12 <= 32'sd1536) ? bankA_17[Selector_idx_12 - 32'sd1] :
              bankA_17[1535]);

  assign readBeat_20[0] = readBeat_19[0];
  assign readBeat_20[1] = readBeat_19[1];
  assign readBeat_20[2] = readBeat_19[2];
  assign readBeat_20[3] = readBeat_19[3];
  assign readBeat_20[4] = readBeat_19[4];
  assign readBeat_20[5] = readBeat_19[5];
  assign readBeat_20[6] = out0_104;
  assign readBeat_20[7] = readBeat_19[7];

  assign adder_175 = {1'b0, baseIndex};
  assign adder_176 = {1'b0, laneIndex_6};
  assign adder_add_temp_58 = adder_175 + adder_176;
  assign out0_105 = (adder_add_temp_58[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_58[15:0]);

  assign adder_178 = {1'b0, out0_105};
  assign adder_179 = {1'b0, const_expression};
  assign adder_add_temp_59 = adder_178 + adder_179;
  assign out0_106 = (adder_add_temp_59[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_59[15:0]);

  assign Selector_idx_13 = {16'b0, out0_106};
  assign out0_107 = ((Selector_idx_13 >= 32'sd1) && (Selector_idx_13 <= 32'sd1536) ? bankB_17[Selector_idx_13 - 32'sd1] :
              bankB_17[1535]);

  assign readBeat_21[0] = readBeat_19[0];
  assign readBeat_21[1] = readBeat_19[1];
  assign readBeat_21[2] = readBeat_19[2];
  assign readBeat_21[3] = readBeat_19[3];
  assign readBeat_21[4] = readBeat_19[4];
  assign readBeat_21[5] = readBeat_19[5];
  assign readBeat_21[6] = out0_107;
  assign readBeat_21[7] = readBeat_19[7];

  assign readBeat_22 = (out0_2 == 1'b0 ? readBeat_20 :
              readBeat_21);

  assign adder_181 = {1'b0, baseIndex};
  assign adder_182 = {1'b0, laneIndex_7};
  assign adder_add_temp_60 = adder_181 + adder_182;
  assign out0_108 = (adder_add_temp_60[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_60[15:0]);

  assign adder_184 = {1'b0, out0_108};
  assign adder_185 = {1'b0, const_expression};
  assign adder_add_temp_61 = adder_184 + adder_185;
  assign out0_109 = (adder_add_temp_61[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_61[15:0]);

  assign Selector_idx_14 = {16'b0, out0_109};
  assign out0_110 = ((Selector_idx_14 >= 32'sd1) && (Selector_idx_14 <= 32'sd1536) ? bankA_17[Selector_idx_14 - 32'sd1] :
              bankA_17[1535]);

  assign readBeat_23[0] = readBeat_22[0];
  assign readBeat_23[1] = readBeat_22[1];
  assign readBeat_23[2] = readBeat_22[2];
  assign readBeat_23[3] = readBeat_22[3];
  assign readBeat_23[4] = readBeat_22[4];
  assign readBeat_23[5] = readBeat_22[5];
  assign readBeat_23[6] = readBeat_22[6];
  assign readBeat_23[7] = out0_110;

  assign adder_187 = {1'b0, baseIndex};
  assign adder_188 = {1'b0, laneIndex_7};
  assign adder_add_temp_62 = adder_187 + adder_188;
  assign out0_111 = (adder_add_temp_62[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_62[15:0]);

  assign adder_190 = {1'b0, out0_111};
  assign adder_191 = {1'b0, const_expression};
  assign adder_add_temp_63 = adder_190 + adder_191;
  assign out0_112 = (adder_add_temp_63[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_63[15:0]);

  assign Selector_idx_15 = {16'b0, out0_112};
  assign out0_113 = ((Selector_idx_15 >= 32'sd1) && (Selector_idx_15 <= 32'sd1536) ? bankB_17[Selector_idx_15 - 32'sd1] :
              bankB_17[1535]);

  assign readBeat_24[0] = readBeat_22[0];
  assign readBeat_24[1] = readBeat_22[1];
  assign readBeat_24[2] = readBeat_22[2];
  assign readBeat_24[3] = readBeat_22[3];
  assign readBeat_24[4] = readBeat_22[4];
  assign readBeat_24[5] = readBeat_22[5];
  assign readBeat_24[6] = readBeat_22[6];
  assign readBeat_24[7] = out0_113;

  assign readBeat_25 = (out0_1 == 1'b0 ? readBeat_23 :
              readBeat_24);

  assign readBeat = (out0 == 1'b0 ? readBeat_1 :
              readBeat_25);

  assign readValid_1 = 1'b0;

  assign readValid_2 = 1'b1;

  assign readValid = (out0 == 1'b0 ? readValid_1 :
              readValid_2);

endmodule  // SramCore

