// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/TokenSram.sv
// Created: 2026-03-20 16:46:18
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: TokenSram
// Source Path: rmsNormalization/DUTPacked/CoreDUT/TokenSram
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TokenSram
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] writeBeat[0:7]  /* single [8] */,
             input logic [15:0] writeAddr  /* uint16 */,
             input logic writeBank,
             input logic writeValid,
             input logic [15:0] readAddr  /* uint16 */,
             input logic readBank,
             input logic readReq,
             output logic [31:0] readBeat[0:7]  /* single [8] */,
             output logic readValid);




  SramCore u_SramCore (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .writeBeat(writeBeat),  /* single [8] */
                       .writeAddr(writeAddr),  /* uint16 */
                       .writeBank(writeBank),
                       .writeValid(writeValid),
                       .readAddr(readAddr),  /* uint16 */
                       .readBank(readBank),
                       .readReq(readReq),
                       .readBeat(readBeat),  /* single [8] */
                       .readValid(readValid)
                       );

endmodule  // TokenSram

