// -------------------------------------------------------------
// 
// File Name: /home/yang/Documents/prj/matlab_DL_transfromer/transformer_models_neo/work/hdl/simulink_rmsNormalization/rmsNormalization/Unpack.sv
// Created: 2026-03-20 10:42:02
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


import DUTPacked_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Unpack
// Source Path: rmsNormalization/DUTPacked/CfgBeatUnpack/Unpack
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Unpack
          (  input logic [255:0] packedBeat  /* ufix256 */,
             output vector_of_unsigned_logic_32 words[0:7]  /* uint32 [8] */);


  vector_of_unsigned_logic_32 words_1 [0:7];  /* uint32 [8] */


  always_comb begin
    words_1[0] = packedBeat[31:0];
    words_1[1] = packedBeat[63:32];
    words_1[2] = packedBeat[95:64];
    words_1[3] = packedBeat[127:96];
    words_1[4] = packedBeat[159:128];
    words_1[5] = packedBeat[191:160];
    words_1[6] = packedBeat[223:192];
    words_1[7] = packedBeat[255:224];
  end

  assign words = words_1;

endmodule  // Unpack

