function summary = hf_quant_generate(prompt, parameters, genOptions)
% HF_QUANT_GENERATE Internal subprocess backend for GPTQ/AWQ branches.

    arguments
        prompt (1,1) string
        parameters (1,1) struct
        genOptions.MaxNewTokens (1,1) {mustBeInteger, mustBePositive} = 50
        genOptions.Temperature (1,1) {mustBePositive} = 1.0
        genOptions.TopK (1,1) {mustBeInteger, mustBePositive} = 1
        genOptions.ForceReload (1,1) logical = false
    end

    thisFile = mfilename('fullpath');
    projectRoot = fileparts(fileparts(fileparts(thisFile)));
    pyExe = fullfile(projectRoot, '.venv', 'bin', 'python');
    if ~exist(pyExe, 'file')
        error('qwen2_quant:hf_quant_generate:PythonNotFound', ...
            'Python executable not found at %s', pyExe);
    end

    runner = fullfile(projectRoot, 'tools', 'qwen2_hf_quant_infer.py');
    if ~exist(runner, 'file')
        error('qwen2_quant:hf_quant_generate:RunnerNotFound', ...
            'Runner script not found: %s', runner);
    end

    req = struct();
    req.model_name = char(parameters.ModelName);
    req.backend_type = char(getFieldOr(parameters, 'BackendType', ''));
    req.local_files_only = logical(getFieldOr(parameters, 'LocalFilesOnly', true));
    req.auto_retry_online = logical(getFieldOr(parameters, 'AutoRetryOnline', true));
    req.hf_endpoint = char(string(getFieldOr(parameters, 'HFEndpoint', "https://hf-mirror.com")));
    req.trust_remote_code = logical(getFieldOr(parameters, 'TrustRemoteCode', true));
    req.use_gpu = logical(getFieldOr(parameters, 'UseGPU', true));
    req.force_reload = logical(genOptions.ForceReload);
    req.prompt = char(prompt);
    req.max_new_tokens = double(genOptions.MaxNewTokens);
    req.temperature = double(genOptions.Temperature);
    req.top_k = double(genOptions.TopK);

    reqFile = [tempname, '.json'];
    respFile = [tempname, '.json'];
    cleanupObj = onCleanup(@()cleanupFiles(reqFile, respFile)); %#ok<NASGU>

    fid = fopen(reqFile, 'w');
    if fid < 0
        error('qwen2_quant:hf_quant_generate:IOError', 'Failed to create request file.');
    end
    fwrite(fid, jsonencode(req), 'char');
    fclose(fid);

    cmd = sprintf('"%s" "%s" --request "%s" --response "%s"', ...
        pyExe, runner, reqFile, respFile);
    [status, out] = system(cmd);

    if ~exist(respFile, 'file')
        error('qwen2_quant:hf_quant_generate:NoResponse', ...
            'No response file generated by subprocess.');
    end

    respText = fileread(respFile);
    resp = jsondecode(respText);

    if status ~= 0
        if isfield(resp, 'error')
            errMsg = string(resp.error);
            if isfield(resp, 'traceback')
                errMsg = errMsg + newline + string(resp.traceback);
            end
            error('qwen2_quant:hf_quant_generate:PythonFailed', '%s', errMsg);
        else
            error('qwen2_quant:hf_quant_generate:PythonFailed', ...
                'HF quant subprocess failed. Output:\n%s', out);
        end
    end

    if isfield(resp, 'ok') && logical(resp.ok)
        summary = string(resp.summary);
    else
        if isfield(resp, 'error')
            errMsg = string(resp.error);
        else
            errMsg = "Unknown subprocess error";
        end
        error('qwen2_quant:hf_quant_generate:RemoteError', '%s', errMsg);
    end
end

function cleanupFiles(reqFile, respFile)
    if exist(reqFile, 'file')
        delete(reqFile);
    end
    if exist(respFile, 'file')
        delete(respFile);
    end
end

function out = getFieldOr(s, name, defaultValue)
    if isfield(s, name)
        out = s.(name);
    else
        out = defaultValue;
    end
end
